# Part 1

load the dataframe into memory and bring it to a valid input for unstructured

In [5]:
# load into memory
import sqlalchemy
import pandas as pd
# allow dataframe to show all columns
pd.set_option('display.max_columns', None)
# Create a database connection
engine = sqlalchemy.create_engine("sqlite:///docs/gold_autorizacao_database.sqlite")
merged_df_autorizacao_final = pd.read_sql("SELECT * FROM autorizacao", engine)

In [6]:
merged_df_autorizacao_final.head()

,CD_AVISO_CIRURGIA,DS_PROCEDIMENTO,CD_GUIA,CD_SENHA,DS_GUIA_PATH,DS_CONTATO
0,857416,"[{""code"":30101557,""description"":""EXCISAO E ROT...",19494856.0,None,https://cdns.overmind.ai/autorizacao-cemig-000...,\n Procedimento Autorizado\n Pacient...
1,857469,"[{""code"":30907136,""description"":""VARIZES - TRA...",19495507.0,J5VEYT7,https://cdns.overmind.ai/autorizacao-bradesco-...,\n Procedimento Autorizado\n Pacient...
2,857883,"[{""code"":30205050,""description"":""AMIGDALECTOMI...",19506292.0,J5VEW29,https://cdns.overmind.ai/autorizacao-bradesco-...,\n Procedimento Autorizado\n Pacient...
3,858036,"[{""code"":30205247,""description"":""UVULOPALATO-F...",19508906.0,J5VEWF9,https://cdns.overmind.ai/autorizacao-bradesco-...,\n Procedimento Parcialmente autorizado\n...
4,859112,"[{""code"":30501350,""description"":""RINOSSEPTOPLA...",19537543.0,5045663575,https://cdns.overmind.ai/autorizacao-sulameric...,\n Procedimento Autorizado\n Pacient...

In [7]:
import requests
import numpy as np
def fetch_pdf_bytes(url):
    try:
        response = requests.get(url, timeout=15)
        if response.status_code == 200 and 'application/pdf' in response.headers.get('content-type', ''):
            return response.content
        else:
            return np.nan
    except Exception as e:
        print(f"Error fetching {url}: {e}")
        return np.nan

# Apply to all links in DS_GUIA_PATH
merged_df_autorizacao_final['DS_PDF_BYTES'] = merged_df_autorizacao_final['DS_GUIA_PATH'].apply(fetch_pdf_bytes)
merged_df_autorizacao_final.head()

,CD_AVISO_CIRURGIA,DS_PROCEDIMENTO,CD_GUIA,CD_SENHA,DS_GUIA_PATH,DS_CONTATO,DS_PDF_BYTES
0,857416,"[{""code"":30101557,""description"":""EXCISAO E ROT...",19494856.0,None,https://cdns.overmind.ai/autorizacao-cemig-000...,\n Procedimento Autorizado\n Pacient...,b'%PDF-1.3\n%\xb7\xbe\xad\xaa\n1 0 obj\n<<\n/T...
1,857469,"[{""code"":30907136,""description"":""VARIZES - TRA...",19495507.0,J5VEYT7,https://cdns.overmind.ai/autorizacao-bradesco-...,\n Procedimento Autorizado\n Pacient...,b'%PDF-1.4\n%\xe2\xe3\xcf\xd3\n4 0 obj\n<</Len...
2,857883,"[{""code"":30205050,""description"":""AMIGDALECTOMI...",19506292.0,J5VEW29,https://cdns.overmind.ai/autorizacao-bradesco-...,\n Procedimento Autorizado\n Pacient...,b'%PDF-1.4\n%\xe2\xe3\xcf\xd3\n4 0 obj\n<</Len...
3,858036,"[{""code"":30205247,""description"":""UVULOPALATO-F...",19508906.0,J5VEWF9,https://cdns.overmind.ai/autorizacao-bradesco-...,\n Procedimento Parcialmente autorizado\n...,b'%PDF-1.4\n%\xe2\xe3\xcf\xd3\n4 0 obj\n<</Len...
4,859112,"[{""code"":30501350,""description"":""RINOSSEPTOPLA...",19537543.0,5045663575,https://cdns.overmind.ai/autorizacao-sulameric...,\n Procedimento Autorizado\n Pacient...,b'%PDF-1.4\n%\xf6\xe4\xfc\xdf\n1 0 obj\n<<\n/T...

In [8]:
# localize the value of DS_PROCEDIMENTO of df merged_df_autorizacao_final FOR CD_AVISO_CIRURGIA =
ds_contato = merged_df_autorizacao_final.loc[merged_df_autorizacao_final['CD_AVISO_CIRURGIA'] == 859112, 'DS_CONTATO'].values[0]
ds_contato

'\n      Procedimento Autorizado\n      Paciente: LEANDRO SALOMAO ROSA\n      CÓDIGO AUTORIZADO:\n      01009001 x 1\n,30501350 x 1\n,30501458 x 2\n\n      \n      SENHA: 5045663575\n      VALIDADE DA SENHA: 19/08/2025\n      OBSERVAÇÕES OPME: Pedido sem OPME\n      OBSERVAÇÕES GERAIS: Diária: 01\n      NOME USUÁRIO FINALIZOU O PEDIDO: TELMA\n    '

In [9]:
ds_procedimento = merged_df_autorizacao_final.loc[merged_df_autorizacao_final['CD_AVISO_CIRURGIA'] == 857469, 'DS_PROCEDIMENTO'].values[0]
ds_procedimento

'[{"code":30907136,"description":"VARIZES - TRATAMENTO CIRURGICO BILATERAL","isMain":true,"pro_fat_id":"30907136","procedure_code":30907136,"quantity":1,"surgery_id":2760}]'

In [34]:
# Create a new column with clickable links for DS_GUIA_PATH
def make_clickable(url):
    if pd.notna(url):
        return f'<a href="{url}" target="_blank">{url}</a>'
    return ""
merged_df_autorizacao_final['DS_GUIA_PATH_CLICKABLE'] = merged_df_autorizacao_final['DS_GUIA_PATH'].apply(make_clickable)
from IPython.display import display, HTML
display(HTML(merged_df_autorizacao_final[['DS_GUIA_PATH', 'DS_GUIA_PATH_CLICKABLE']].head(10).to_html(escape=False)))

In [7]:
# Extract ground truth fields from DS_CONTATO
import re

def extract_ds_contato_fields(ds_contato_text):
    """Extract structured fields from DS_CONTATO text using regex patterns"""
    if pd.isna(ds_contato_text):
        return {field + '_gt': None for field in ['paciente', 'codigo_autorizado', 'senha', 'validade_senha', 'observacoes_opme', 'observacoes_gerais', 'usuario_finalizador']}
    
    extracted = {}
    
    # Extract Paciente
    paciente_match = re.search(r'Paciente:\s*(.+?)(?=\n|CÓDIGO)', ds_contato_text, re.IGNORECASE)
    extracted['paciente_gt'] = paciente_match.group(1).strip() if paciente_match else None
    
    # Extract CÓDIGO AUTORIZADO
    codigo_match = re.search(r'CÓDIGO AUTORIZADO:\s*(.+?)(?=\n\n|SENHA)', ds_contato_text, re.DOTALL | re.IGNORECASE)
    extracted['codigo_autorizado_gt'] = codigo_match.group(1).strip() if codigo_match else None
    
    # Extract SENHA
    senha_match = re.search(r'SENHA:\s*(.+?)(?=\n|VALIDADE)', ds_contato_text, re.IGNORECASE)
    extracted['senha_gt'] = senha_match.group(1).strip() if senha_match else None
    
    # Extract VALIDADE DA SENHA
    validade_match = re.search(r'VALIDADE DA SENHA:\s*(.+?)(?=\n|OBSERVAÇÕES)', ds_contato_text, re.IGNORECASE)
    extracted['validade_senha_gt'] = validade_match.group(1).strip() if validade_match else None
    
    # Extract OBSERVAÇÕES OPME
    opme_match = re.search(r'OBSERVAÇÕES OPME:\s*(.+?)(?=\n|OBSERVAÇÕES GERAIS)', ds_contato_text, re.IGNORECASE)
    extracted['observacoes_opme_gt'] = opme_match.group(1).strip() if opme_match else None
    
    # Extract OBSERVAÇÕES GERAIS
    gerais_match = re.search(r'OBSERVAÇÕES GERAIS:\s*(.+?)(?=\n|NOME USUÁRIO)', ds_contato_text, re.IGNORECASE)
    extracted['observacoes_gerais_gt'] = gerais_match.group(1).strip() if gerais_match else None
    
    # Extract NOME USUÁRIO FINALIZOU O PEDIDO
    usuario_match = re.search(r'NOME USUÁRIO FINALIZOU O PEDIDO:\s*(.+?)(?=\n|$)', ds_contato_text, re.IGNORECASE)
    extracted['usuario_finalizador_gt'] = usuario_match.group(1).strip() if usuario_match else None
    
    return extracted

# Apply extraction to all rows in eval_df
gt_columns = ['paciente_gt', 'codigo_autorizado_gt', 'senha_gt', 'validade_senha_gt', 'observacoes_opme_gt', 'observacoes_gerais_gt', 'usuario_finalizador_gt']

# Initialize ground truth columns
for col in gt_columns:
    merged_df_autorizacao_final[col] = None

# Extract fields for each row
for idx, row in merged_df_autorizacao_final.iterrows():
    extracted_fields = extract_ds_contato_fields(row['DS_CONTATO'])
    for field_name, value in extracted_fields.items():
        merged_df_autorizacao_final.at[idx, field_name] = value

print("Ground truth extraction completed!")
print("\nSample of extracted fields:")
merged_df_autorizacao_final[['CD_AVISO_CIRURGIA'] + gt_columns].head()

Ground truth extraction completed!

Sample of extracted fields:

,CD_AVISO_CIRURGIA,paciente_gt,codigo_autorizado_gt,senha_gt,validade_senha_gt,observacoes_opme_gt,observacoes_gerais_gt,usuario_finalizador_gt
0,857416,SALETE EMILIA DOS SANTOS LIMA,"01009001 x 1\n,30101557 x 1",000120250700053801,10/08/2025,Pedido sem OPME,None,Deisiane
1,857469,BARBARA ARAUJO SCHNNEPPEL CORREA,"01009001 x 1\n,30907136 x 1",J5VEYT7,07/01/2026,Pedido sem OPME,Diária: 01,TELMA
2,857883,MILENA RAFAELA TRINDADE,"01009001 x 1\n,30205050 x 1\n,30205271 x 1\n,3...",J5VEW29,07/01/2026,Pedido sem OPME,None,ANA
3,858036,DIONE RAIMUNDO CARVALHO PINTO,"30502349 x 0\n,30205247 x 1\n,30501369 x 1\n,3...",J5VEWF9,06/01/2026,Pedido sem OPME,None,BRUNA FERNANDA
4,859112,LEANDRO SALOMAO ROSA,"01009001 x 1\n,30501350 x 1\n,30501458 x 2",5045663575,19/08/2025,Pedido sem OPME,Diária: 01,TELMA

In [8]:
merged_df_autorizacao_final.head()

,CD_AVISO_CIRURGIA,DS_PROCEDIMENTO,CD_GUIA,CD_SENHA,DS_GUIA_PATH,DS_CONTATO,DS_PDF_BYTES,paciente_gt,codigo_autorizado_gt,senha_gt,validade_senha_gt,observacoes_opme_gt,observacoes_gerais_gt,usuario_finalizador_gt
0,857416,"[{""code"":30101557,""description"":""EXCISAO E ROT...",19494856.0,None,https://cdns.overmind.ai/autorizacao-cemig-000...,\n Procedimento Autorizado\n Pacient...,b'%PDF-1.3\n%\xb7\xbe\xad\xaa\n1 0 obj\n<<\n/T...,SALETE EMILIA DOS SANTOS LIMA,"01009001 x 1\n,30101557 x 1",000120250700053801,10/08/2025,Pedido sem OPME,None,Deisiane
1,857469,"[{""code"":30907136,""description"":""VARIZES - TRA...",19495507.0,J5VEYT7,https://cdns.overmind.ai/autorizacao-bradesco-...,\n Procedimento Autorizado\n Pacient...,b'%PDF-1.4\n%\xe2\xe3\xcf\xd3\n4 0 obj\n<</Len...,BARBARA ARAUJO SCHNNEPPEL CORREA,"01009001 x 1\n,30907136 x 1",J5VEYT7,07/01/2026,Pedido sem OPME,Diária: 01,TELMA
2,857883,"[{""code"":30205050,""description"":""AMIGDALECTOMI...",19506292.0,J5VEW29,https://cdns.overmind.ai/autorizacao-bradesco-...,\n Procedimento Autorizado\n Pacient...,b'%PDF-1.4\n%\xe2\xe3\xcf\xd3\n4 0 obj\n<</Len...,MILENA RAFAELA TRINDADE,"01009001 x 1\n,30205050 x 1\n,30205271 x 1\n,3...",J5VEW29,07/01/2026,Pedido sem OPME,None,ANA
3,858036,"[{""code"":30205247,""description"":""UVULOPALATO-F...",19508906.0,J5VEWF9,https://cdns.overmind.ai/autorizacao-bradesco-...,\n Procedimento Parcialmente autorizado\n...,b'%PDF-1.4\n%\xe2\xe3\xcf\xd3\n4 0 obj\n<</Len...,DIONE RAIMUNDO CARVALHO PINTO,"30502349 x 0\n,30205247 x 1\n,30501369 x 1\n,3...",J5VEWF9,06/01/2026,Pedido sem OPME,None,BRUNA FERNANDA
4,859112,"[{""code"":30501350,""description"":""RINOSSEPTOPLA...",19537543.0,5045663575,https://cdns.overmind.ai/autorizacao-sulameric...,\n Procedimento Autorizado\n Pacient...,b'%PDF-1.4\n%\xf6\xe4\xfc\xdf\n1 0 obj\n<<\n/T...,LEANDRO SALOMAO ROSA,"01009001 x 1\n,30501350 x 1\n,30501458 x 2",5045663575,19/08/2025,Pedido sem OPME,Diária: 01,TELMA

In [9]:
# save to sql db merged_autorizacao.sqlite
import sqlalchemy

# Create a database connection to the correct database
engine = sqlalchemy.create_engine("sqlite:///merged_autorizacao_database.sqlite")

# Save the DataFrame to the autorizacao table
merged_df_autorizacao_final.to_sql("autorizacao", engine, if_exists="replace", index=False)

# load

merged_df_autorizacao_final = pd.read_sql("SELECT * FROM autorizacao", engine)

# Part 2 - processing with unstructured

In [8]:
import io
from unstructured.partition.pdf import partition_pdf

# Get the PDF bytes for the desired row
pdf_bytes = merged_df_autorizacao_final["DS_PDF_BYTES"][merged_df_autorizacao_final['CD_AVISO_CIRURGIA'] == 857469].values[0]

# Wrap the bytes in a BytesIO object
pdf_file_like = io.BytesIO(pdf_bytes)

# Now pass to partition_pdf
elements = partition_pdf(file=pdf_file_like, languages=["portuguese"])

# Join the text
full_text = "\n".join([el.text for el in elements if el.text])

/home/joao/projects/company_projects/autorizacoes-api/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [9]:
print(full_text)

Bradesco Seguros
Guia de Solicitação de Internação 2 - N° Guia no Prestador
1 - Registro ANS 005711
3 - Número da Guia Atribuído pela Operadora 121223221
4 - Data da Autorização 11/07/2025
5 - Senha
J5VEYT7
6 - Data de Validade da Senha
Dados do Beneficiário
7 - Número da Carteira 775432013269019
8 - Validade da Carteira
9 - Atendimento a RN Não
50 - Nome Social
10 - Nome BARBARA ARAUJO SCHNNEPPEL CORREA
Dados do Contratado Solicitante
12 - Código na Operadora 426512
13 - Nome do Contratado HOSPITAL MATER DEI
14 - Nome do Profissional Solicitante MATEUS ALVES BORGES CRISTINO
15 - Conselho Profissional
CRM
16 - Número do Conselho
43236
17 - UF
MG
18 - Código CBO
292 MEDICO CLINICO
Dados do Hospital / Local Solicitado / Dados da Internação
19 - Código na Operadora / CNPJ 426512
20 - Nome do Hospital/ Local Solicitado HOSPITAL MATER DEI
21 - Data Sugerida para Internação (Real) 12/07/2025
22 - Caráter do
23 -Tipo de
24 - Regime de Internação
25 - Qtde. Diárias
26 - Previsão de uso de OPME
27 - Previsão de uso de Quimioterápico
ELETIVO
2
HOSPITALAR
1
28 - Indicação Clínica
DN: ; DC: ; DA: ; I: ; P: ; GR: ; A: ; UTI: N; RV: N; OBS: Solicitacao de autorizacao -
29 - CID 10 Principal
30 - CID 10 (2)
31 - CID 10 (3)
32 - CID 10 (4)
33 - Indicação de Acidente (acidente ou doença
Procedimentos ou Itens Assistenciais Adicionais
34 - Tabela
35 - Código do Procedimento ou Item Assistencial
36 - Descrição
37 - Qtde. Solic.
38 - Qtde. Aut.
16
30907136
VARIZES - TRATAMENTO CIRURGICO DE DOIS MEMBROS
1
1
Dados de Autorização
39 - Data Provável da Admissão
40 - Qtde. Diárias Autorizadas
41 - Tipo da Acomodação Autorizada
12/07/2025
1
QUARTO PARTICULAR
42 - Código na Operadora / CNPJ autorizado
43 - Nome do Hospital / Local Autorizado
44 - Código CNES
45 - Observação / Justificativa - ADM(PL. EMPRESARIAL - NACIONAL II(227)) MED(AUTORIZADO INTEGRAL. PROCEDIMENTOS E OPMEs AUTORIZADOS CONFORME SOLICITAÇÃO MÉDICA. ) FIN(s/acomp)
46 - Data da Solicitação 11/07/2025
47 - Assinatura do Profissional Solicitante
48 - Assinatura do Beneficiário ou Responsável
49 - Assinatura do Responsável pela Autorização
Gerado em: 11/07/2025 09:32

In [10]:
# taking this output and processing trough a llm

import sys

# add app to path so we dont get the error ModuleNotFoundError: No module named 'app'
from pathlib import Path
sys.path.append(str(Path.cwd().parent))
from app.utils.llm_service import AnthropicLLMService
from app.utils.aws_services_handler import create_boto3_client
from app.utils.config import load_config, AppConstants
from app.utils.logger import get_logger
from app.utils.system_prompts.autorizacao_prompt import Prompts


logger = get_logger(name=__name__)
config_vars = load_config()

In [11]:
app_constants = AppConstants()
bedrock_client = create_boto3_client("bedrock-runtime", config_vars)
autorizacao_prompt = Prompts.autorizacao_extraction_prompt

llm_instance = AnthropicLLMService(
    model_id=app_constants.BEDROCK_DEFAULT_MODEL_ID,
    model_version=app_constants.BEDROCK_DEFAULT_MODEL_VERSION,
    client=bedrock_client,
    system_prompt=autorizacao_prompt,
    max_tokens=app_constants.MAX_TOKENS,
    temperature=app_constants.TEMPERATURE,
    budget_tokens=app_constants.BUDGET_TOKENS
)

{"timestamp": "2025-08-20T10:43:38", "level": "INFO", "name": "app.utils.aws_services_handler", "message": "Criando cliente BEDROCK-RUNTIME para a região: us-east-1...", "filename": "aws_services_handler.py", "lineno": 17}
{"timestamp": "2025-08-20T10:43:38", "level": "INFO", "name": "app.utils.aws_services_handler", "message": "Cliente BEDROCK-RUNTIME criado com sucesso.", "filename": "aws_services_handler.py", "lineno": 26}
{"timestamp": "2025-08-20T10:43:38", "level": "INFO", "name": "app.utils.aws_services_handler", "message": "Cliente BEDROCK-RUNTIME criado com sucesso.", "filename": "aws_services_handler.py", "lineno": 26}

In [12]:
# testing a single answer of the llm

results = llm_instance.invoke_model(
    input_str=full_text
)

In [13]:
results

{'procedimento_autorizado': 'VARIZES - TRATAMENTO CIRURGICO DE DOIS MEMBROS',
 'paciente': 'BARBARA ARAUJO SCHNNEPPEL CORREA',
 'codigo_autorizado': '30907136 - 1',
 'senha': 'J5VEYT7',
 'validade_senha': '12/07/2025',
 'observacoes_opme': 'OPMEs AUTORIZADOS CONFORME SOLICITAÇÃO MÉDICA',
 'observacoes_gerais': 'DN: ; DC: ; DA: ; I: ; P: ; GR: ; A: ; UTI: N; RV: N; OBS: Solicitacao de autorizacao -',
 'usuario_finalizador': 'MATEUS ALVES BORGES CRISTINO'}

In [14]:
type(results)

dict

In [15]:
import re

results["codigo_autorizado"] = re.sub(r'[^a-zA-Z0-9]', '', results["codigo_autorizado"])
results["senha"] = re.sub(r'[^a-zA-Z0-9]', '', results["senha"])
results

{'procedimento_autorizado': 'VARIZES - TRATAMENTO CIRURGICO DE DOIS MEMBROS',
 'paciente': 'BARBARA ARAUJO SCHNNEPPEL CORREA',
 'codigo_autorizado': '309071361',
 'senha': 'J5VEYT7',
 'validade_senha': '12/07/2025',
 'observacoes_opme': 'OPMEs AUTORIZADOS CONFORME SOLICITAÇÃO MÉDICA',
 'observacoes_gerais': 'DN: ; DC: ; DA: ; I: ; P: ; GR: ; A: ; UTI: N; RV: N; OBS: Solicitacao de autorizacao -',
 'usuario_finalizador': 'MATEUS ALVES BORGES CRISTINO'}

In [16]:
results["senha"] == "J5VEYT7"

True

# part 2.5 
build a pipeline for evaluation

PS: what fields to evaluate?

In [17]:
# Step 1: Create subset of first 5 examples
eval_df = merged_df_autorizacao_final[:5].copy()
print(f"Created evaluation dataset with {len(eval_df)} rows")

# Initialize new columns for LLM results
llm_columns = [
    'procedimento_autorizado_llm',
    'paciente_llm', 
    'codigo_autorizado_llm',
    'senha_llm',
    'validade_senha_llm',
    'observacoes_opme_llm',
    'observacoes_gerais_llm',
    'usuario_finalizador_llm'
]

for col in llm_columns:
    eval_df[col] = None

print("Initialized LLM result columns")
eval_df.head()

Created evaluation dataset with 5 rows
Initialized LLM result columns

,CD_AVISO_CIRURGIA,DS_PROCEDIMENTO,CD_GUIA,CD_SENHA,DS_GUIA_PATH,DS_CONTATO,DS_PDF_BYTES,DS_GUIA_PATH_CLICKABLE,procedimento_autorizado_llm,paciente_llm,codigo_autorizado_llm,senha_llm,validade_senha_llm,observacoes_opme_llm,observacoes_gerais_llm,usuario_finalizador_llm
0,857416,"[{""code"":30101557,""description"":""EXCISAO E ROT...",19494856.0,None,https://cdns.overmind.ai/autorizacao-cemig-000...,\n Procedimento Autorizado\n Pacient...,b'%PDF-1.3\n%\xb7\xbe\xad\xaa\n1 0 obj\n<<\n/T...,"<a href=""https://cdns.overmind.ai/autorizacao-...",None,None,None,None,None,None,None,None
1,857469,"[{""code"":30907136,""description"":""VARIZES - TRA...",19495507.0,J5VEYT7,https://cdns.overmind.ai/autorizacao-bradesco-...,\n Procedimento Autorizado\n Pacient...,b'%PDF-1.4\n%\xe2\xe3\xcf\xd3\n4 0 obj\n<</Len...,"<a href=""https://cdns.overmind.ai/autorizacao-...",None,None,None,None,None,None,None,None
2,857883,"[{""code"":30205050,""description"":""AMIGDALECTOMI...",19506292.0,J5VEW29,https://cdns.overmind.ai/autorizacao-bradesco-...,\n Procedimento Autorizado\n Pacient...,b'%PDF-1.4\n%\xe2\xe3\xcf\xd3\n4 0 obj\n<</Len...,"<a href=""https://cdns.overmind.ai/autorizacao-...",None,None,None,None,None,None,None,None
3,858036,"[{""code"":30205247,""description"":""UVULOPALATO-F...",19508906.0,J5VEWF9,https://cdns.overmind.ai/autorizacao-bradesco-...,\n Procedimento Parcialmente autorizado\n...,b'%PDF-1.4\n%\xe2\xe3\xcf\xd3\n4 0 obj\n<</Len...,"<a href=""https://cdns.overmind.ai/autorizacao-...",None,None,None,None,None,None,None,None
4,859112,"[{""code"":30501350,""description"":""RINOSSEPTOPLA...",19537543.0,5045663575,https://cdns.overmind.ai/autorizacao-sulameric...,\n Procedimento Autorizado\n Pacient...,b'%PDF-1.4\n%\xf6\xe4\xfc\xdf\n1 0 obj\n<<\n/T...,"<a href=""https://cdns.overmind.ai/autorizacao-...",None,None,None,None,None,None,None,None

In [18]:
# Step 2 & 3: Process each row through the pipeline
import re
from tqdm import tqdm

def process_single_row(row_index, pdf_bytes):
    """Process a single row through the PDF->Text->LLM pipeline"""
    try:
        # Convert PDF bytes to text using unstructured
        pdf_file_like = io.BytesIO(pdf_bytes)
        elements = partition_pdf(file=pdf_file_like, languages=["portuguese"])
        full_text = "\n".join([el.text for el in elements if el.text])
        
        # Send to LLM
        results = llm_instance.invoke_model(input_str=full_text)
        
        # Clean special characters from specific fields
        if 'codigo_autorizado' in results:
            results["codigo_autorizado"] = re.sub(r'[^a-zA-Z0-9]', '', results["codigo_autorizado"])
        if 'senha' in results:
            results["senha"] = re.sub(r'[^a-zA-Z0-9]', '', results["senha"])
            
        return results
        
    except Exception as e:
        print(f"Error processing row {row_index}: {e}")
        return {col.replace('_llm', ''): None for col in llm_columns}

# Process each row
for idx, row in tqdm(eval_df.iterrows(), total=len(eval_df), desc="Processing PDFs"):
    pdf_bytes = row['DS_PDF_BYTES']
    
    # Skip if no PDF bytes available
    if pd.isna(pdf_bytes):
        print(f"Skipping row {idx}: No PDF bytes available")
        continue
        
    # Process the row
    llm_results = process_single_row(idx, pdf_bytes)
    
    # Add results to dataframe
    for field_name, value in llm_results.items():
        col_name = f"{field_name}_llm"
        if col_name in eval_df.columns:
            eval_df.at[idx, col_name] = value
    
    print(f"Completed row {idx} - CD_AVISO_CIRURGIA: {row['CD_AVISO_CIRURGIA']}")

print("Pipeline processing completed!")
eval_df[['CD_AVISO_CIRURGIA'] + llm_columns].head()

Processing PDFs:  20%|██        | 1/5 [00:11<00:45, 11.25s/it]

Completed row 0 - CD_AVISO_CIRURGIA: 857416

Processing PDFs:  40%|████      | 2/5 [00:26<00:40, 13.61s/it]

Completed row 1 - CD_AVISO_CIRURGIA: 857469

Processing PDFs:  60%|██████    | 3/5 [00:37<00:25, 12.51s/it]

Completed row 2 - CD_AVISO_CIRURGIA: 857883

Processing PDFs:  80%|████████  | 4/5 [00:56<00:15, 15.04s/it]

Completed row 3 - CD_AVISO_CIRURGIA: 858036

Processing PDFs: 100%|██████████| 5/5 [01:07<00:00, 13.46s/it]

Completed row 4 - CD_AVISO_CIRURGIA: 859112
Pipeline processing completed!

,CD_AVISO_CIRURGIA,procedimento_autorizado_llm,paciente_llm,codigo_autorizado_llm,senha_llm,validade_senha_llm,observacoes_opme_llm,observacoes_gerais_llm,usuario_finalizador_llm
0,857416,"EXTENSOS FERIMENTOS, CICATRIZES OU TUMORES - E...",SALETE EMILIA DOS SANTOS LIMA,301015571,000120250700053801,10/08/25,Pedido sem OPME,Solicitacao de autorizacao,KAYO VIEIRA TEODORAK PÊGO
1,857469,VARIZES - TRATAMENTO CIRURGICO DE DOIS MEMBROS,BARBARA ARAUJO SCHNNEPPEL CORREA,309071361,J5VEYT7,None,PROCEDIMENTOS E OPMEs AUTORIZADOS CONFORME SOL...,DN: ; DC: ; DA: ; I: ; P: ; GR: ; A: ; UTI: N;...,MATEUS ALVES BORGES CRISTINO
2,857883,AMIGDALECTOMIA DAS PALATINAS,MILENA RAFAELA TRINDADE,302050501,J5VEW29,None,Pedido sem OPME,DN: ; DC: ; DA: ; I: ; P: ; GR: ; A: ; UTI: N;...,AURELIA ALBUQUERQUE MARTINS
3,858036,AMIGDALECTOMIA DAS PALATINAS,DIONE RAIMUNDO CARVALHO PINTO,302050501,J5VEWF9,None,Pedido sem OPME,DN: ; DC: ; DA: ; I: ; P: ; GR: ; A: ; UTI: N;...,LUCAS EDUARDO DE OLIVEIRA
4,859112,SEPTOPLASTIA TURBINECTOMIA,LEANDRO S ROSA,65300114QtAut01,5045663575,19/08/2025,Pedido sem OPME,None,None

### expanding the eval dataframe so we can get the field DS_CONTATO values into new cols

In [19]:
# Extract ground truth fields from DS_CONTATO
import re

def extract_ds_contato_fields(ds_contato_text):
    """Extract structured fields from DS_CONTATO text using regex patterns"""
    if pd.isna(ds_contato_text):
        return {field + '_gt': None for field in ['paciente', 'codigo_autorizado', 'senha', 'validade_senha', 'observacoes_opme', 'observacoes_gerais', 'usuario_finalizador']}
    
    extracted = {}
    
    # Extract Paciente
    paciente_match = re.search(r'Paciente:\s*(.+?)(?=\n|CÓDIGO)', ds_contato_text, re.IGNORECASE)
    extracted['paciente_gt'] = paciente_match.group(1).strip() if paciente_match else None
    
    # Extract CÓDIGO AUTORIZADO
    codigo_match = re.search(r'CÓDIGO AUTORIZADO:\s*(.+?)(?=\n\n|SENHA)', ds_contato_text, re.DOTALL | re.IGNORECASE)
    extracted['codigo_autorizado_gt'] = codigo_match.group(1).strip() if codigo_match else None
    
    # Extract SENHA
    senha_match = re.search(r'SENHA:\s*(.+?)(?=\n|VALIDADE)', ds_contato_text, re.IGNORECASE)
    extracted['senha_gt'] = senha_match.group(1).strip() if senha_match else None
    
    # Extract VALIDADE DA SENHA
    validade_match = re.search(r'VALIDADE DA SENHA:\s*(.+?)(?=\n|OBSERVAÇÕES)', ds_contato_text, re.IGNORECASE)
    extracted['validade_senha_gt'] = validade_match.group(1).strip() if validade_match else None
    
    # Extract OBSERVAÇÕES OPME
    opme_match = re.search(r'OBSERVAÇÕES OPME:\s*(.+?)(?=\n|OBSERVAÇÕES GERAIS)', ds_contato_text, re.IGNORECASE)
    extracted['observacoes_opme_gt'] = opme_match.group(1).strip() if opme_match else None
    
    # Extract OBSERVAÇÕES GERAIS
    gerais_match = re.search(r'OBSERVAÇÕES GERAIS:\s*(.+?)(?=\n|NOME USUÁRIO)', ds_contato_text, re.IGNORECASE)
    extracted['observacoes_gerais_gt'] = gerais_match.group(1).strip() if gerais_match else None
    
    # Extract NOME USUÁRIO FINALIZOU O PEDIDO
    usuario_match = re.search(r'NOME USUÁRIO FINALIZOU O PEDIDO:\s*(.+?)(?=\n|$)', ds_contato_text, re.IGNORECASE)
    extracted['usuario_finalizador_gt'] = usuario_match.group(1).strip() if usuario_match else None
    
    return extracted

# Apply extraction to all rows in eval_df
gt_columns = ['paciente_gt', 'codigo_autorizado_gt', 'senha_gt', 'validade_senha_gt', 'observacoes_opme_gt', 'observacoes_gerais_gt', 'usuario_finalizador_gt']

# Initialize ground truth columns
for col in gt_columns:
    eval_df[col] = None

# Extract fields for each row
for idx, row in eval_df.iterrows():
    extracted_fields = extract_ds_contato_fields(row['DS_CONTATO'])
    for field_name, value in extracted_fields.items():
        eval_df.at[idx, field_name] = value

print("Ground truth extraction completed!")
print("\nSample of extracted fields:")
eval_df[['CD_AVISO_CIRURGIA'] + gt_columns].head()

Ground truth extraction completed!

Sample of extracted fields:

,CD_AVISO_CIRURGIA,paciente_gt,codigo_autorizado_gt,senha_gt,validade_senha_gt,observacoes_opme_gt,observacoes_gerais_gt,usuario_finalizador_gt
0,857416,SALETE EMILIA DOS SANTOS LIMA,"01009001 x 1\n,30101557 x 1",000120250700053801,10/08/2025,Pedido sem OPME,None,Deisiane
1,857469,BARBARA ARAUJO SCHNNEPPEL CORREA,"01009001 x 1\n,30907136 x 1",J5VEYT7,07/01/2026,Pedido sem OPME,Diária: 01,TELMA
2,857883,MILENA RAFAELA TRINDADE,"01009001 x 1\n,30205050 x 1\n,30205271 x 1\n,3...",J5VEW29,07/01/2026,Pedido sem OPME,None,ANA
3,858036,DIONE RAIMUNDO CARVALHO PINTO,"30502349 x 0\n,30205247 x 1\n,30501369 x 1\n,3...",J5VEWF9,06/01/2026,Pedido sem OPME,None,BRUNA FERNANDA
4,859112,LEANDRO SALOMAO ROSA,"01009001 x 1\n,30501350 x 1\n,30501458 x 2",5045663575,19/08/2025,Pedido sem OPME,Diária: 01,TELMA

In [21]:
eval_df.head()

,CD_AVISO_CIRURGIA,DS_PROCEDIMENTO,CD_GUIA,CD_SENHA,DS_GUIA_PATH,DS_CONTATO,DS_PDF_BYTES,DS_GUIA_PATH_CLICKABLE,procedimento_autorizado_llm,paciente_llm,codigo_autorizado_llm,senha_llm,validade_senha_llm,observacoes_opme_llm,observacoes_gerais_llm,usuario_finalizador_llm,paciente_gt,codigo_autorizado_gt,senha_gt,validade_senha_gt,observacoes_opme_gt,observacoes_gerais_gt,usuario_finalizador_gt
0,857416,"[{""code"":30101557,""description"":""EXCISAO E ROT...",19494856.0,None,https://cdns.overmind.ai/autorizacao-cemig-000...,\n Procedimento Autorizado\n Pacient...,b'%PDF-1.3\n%\xb7\xbe\xad\xaa\n1 0 obj\n<<\n/T...,"<a href=""https://cdns.overmind.ai/autorizacao-...","EXTENSOS FERIMENTOS, CICATRIZES OU TUMORES - E...",SALETE EMILIA DOS SANTOS LIMA,301015571,000120250700053801,10/08/25,Pedido sem OPME,Solicitacao de autorizacao,KAYO VIEIRA TEODORAK PÊGO,SALETE EMILIA DOS SANTOS LIMA,"01009001 x 1\n,30101557 x 1",000120250700053801,10/08/2025,Pedido sem OPME,None,Deisiane
1,857469,"[{""code"":30907136,""description"":""VARIZES - TRA...",19495507.0,J5VEYT7,https://cdns.overmind.ai/autorizacao-bradesco-...,\n Procedimento Autorizado\n Pacient...,b'%PDF-1.4\n%\xe2\xe3\xcf\xd3\n4 0 obj\n<</Len...,"<a href=""https://cdns.overmind.ai/autorizacao-...",VARIZES - TRATAMENTO CIRURGICO DE DOIS MEMBROS,BARBARA ARAUJO SCHNNEPPEL CORREA,309071361,J5VEYT7,None,PROCEDIMENTOS E OPMEs AUTORIZADOS CONFORME SOL...,DN: ; DC: ; DA: ; I: ; P: ; GR: ; A: ; UTI: N;...,MATEUS ALVES BORGES CRISTINO,BARBARA ARAUJO SCHNNEPPEL CORREA,"01009001 x 1\n,30907136 x 1",J5VEYT7,07/01/2026,Pedido sem OPME,Diária: 01,TELMA
2,857883,"[{""code"":30205050,""description"":""AMIGDALECTOMI...",19506292.0,J5VEW29,https://cdns.overmind.ai/autorizacao-bradesco-...,\n Procedimento Autorizado\n Pacient...,b'%PDF-1.4\n%\xe2\xe3\xcf\xd3\n4 0 obj\n<</Len...,"<a href=""https://cdns.overmind.ai/autorizacao-...",AMIGDALECTOMIA DAS PALATINAS,MILENA RAFAELA TRINDADE,302050501,J5VEW29,None,Pedido sem OPME,DN: ; DC: ; DA: ; I: ; P: ; GR: ; A: ; UTI: N;...,AURELIA ALBUQUERQUE MARTINS,MILENA RAFAELA TRINDADE,"01009001 x 1\n,30205050 x 1\n,30205271 x 1\n,3...",J5VEW29,07/01/2026,Pedido sem OPME,None,ANA
3,858036,"[{""code"":30205247,""description"":""UVULOPALATO-F...",19508906.0,J5VEWF9,https://cdns.overmind.ai/autorizacao-bradesco-...,\n Procedimento Parcialmente autorizado\n...,b'%PDF-1.4\n%\xe2\xe3\xcf\xd3\n4 0 obj\n<</Len...,"<a href=""https://cdns.overmind.ai/autorizacao-...",AMIGDALECTOMIA DAS PALATINAS,DIONE RAIMUNDO CARVALHO PINTO,302050501,J5VEWF9,None,Pedido sem OPME,DN: ; DC: ; DA: ; I: ; P: ; GR: ; A: ; UTI: N;...,LUCAS EDUARDO DE OLIVEIRA,DIONE RAIMUNDO CARVALHO PINTO,"30502349 x 0\n,30205247 x 1\n,30501369 x 1\n,3...",J5VEWF9,06/01/2026,Pedido sem OPME,None,BRUNA FERNANDA
4,859112,"[{""code"":30501350,""description"":""RINOSSEPTOPLA...",19537543.0,5045663575,https://cdns.overmind.ai/autorizacao-sulameric...,\n Procedimento Autorizado\n Pacient...,b'%PDF-1.4\n%\xf6\xe4\xfc\xdf\n1 0 obj\n<<\n/T...,"<a href=""https://cdns.overmind.ai/autorizacao-...",SEPTOPLASTIA TURBINECTOMIA,LEANDRO S ROSA,65300114QtAut01,5045663575,19/08/2025,Pedido sem OPME,None,None,LEANDRO SALOMAO ROSA,"01009001 x 1\n,30501350 x 1\n,30501458 x 2",5045663575,19/08/2025,Pedido sem OPME,Diária: 01,TELMA

In [24]:
"000120250700053801" ==  "000120250700053801"

True

# Part 3 - processing with textract pdf extractor

final df should be textract_eval_df

In [10]:

# load
import sqlalchemy
import pandas as pd
# Create a database connection to the correct database
engine = sqlalchemy.create_engine("sqlite:///merged_autorizacao_database.sqlite")


merged_df_autorizacao_final = pd.read_sql("SELECT * FROM autorizacao", engine)

In [11]:
# trying to use the mudular code to get the workflow feeling
import sys

# add app to path so we dont get the error ModuleNotFoundError: No module named 'app'
from pathlib import Path
sys.path.append(str(Path.cwd().parent))
from app.utils.process_images import process_blobs
from app.utils.textract_service import TextractPDFAnalyzer
from app.utils.llm_service import AnthropicLLMService
from app.utils.aws_services_handler import create_boto3_client
from app.utils.config import load_config, AppConstants
from app.utils.logger import get_logger
from app.utils.system_prompts.autorizacao_prompt import Prompts


logger = get_logger(name=__name__)
config_vars = load_config()

In [12]:
app_constants = AppConstants()
textract_client = create_boto3_client("textract", config_vars)
bedrock_client = create_boto3_client("bedrock-runtime", config_vars)
s3_client = create_boto3_client("s3", config_vars)
bucket_name = "autorizacoes"

# Initialize the TextractPDFAnalyzer
pdf_analyzer = TextractPDFAnalyzer(
    textract_client=textract_client,
    s3_client=s3_client,
    bucket_name="autorizacoes-textract",
    bucket_folder="guias-pdf"
)

autorizacao_prompt = Prompts.autorizacao_extraction_prompt


llm_instance = AnthropicLLMService(
    model_id=app_constants.BEDROCK_DEFAULT_MODEL_ID,
    model_version=app_constants.BEDROCK_DEFAULT_MODEL_VERSION,
    client=bedrock_client,
    system_prompt=autorizacao_prompt,
    max_tokens=app_constants.MAX_TOKENS,
    temperature=app_constants.TEMPERATURE,
    budget_tokens=app_constants.BUDGET_TOKENS
)

{"timestamp": "2025-08-20T16:10:29", "level": "INFO", "name": "app.utils.aws_services_handler", "message": "Criando cliente TEXTRACT para a região: us-east-1...", "filename": "aws_services_handler.py", "lineno": 17}
{"timestamp": "2025-08-20T16:10:29", "level": "INFO", "name": "app.utils.aws_services_handler", "message": "Cliente TEXTRACT criado com sucesso.", "filename": "aws_services_handler.py", "lineno": 26}
{"timestamp": "2025-08-20T16:10:29", "level": "INFO", "name": "app.utils.aws_services_handler", "message": "Criando cliente BEDROCK-RUNTIME para a região: us-east-1...", "filename": "aws_services_handler.py", "lineno": 17}
{"timestamp": "2025-08-20T16:10:29", "level": "INFO", "name": "app.utils.aws_services_handler", "message": "Cliente TEXTRACT criado com sucesso.", "filename": "aws_services_handler.py", "lineno": 26}
{"timestamp": "2025-08-20T16:10:29", "level": "INFO", "name": "app.utils.aws_services_handler", "message": "Criando cliente BEDROCK-RUNTIME para a região: us-east-1...", "filename": "aws_services_handler.py", "lineno": 17}
{"timestamp": "2025-08-20T16:10:29", "level": "INFO", "name": "app.utils.aws_services_handler", "message": "Cliente BEDROCK-RUNTIME criado com sucesso.", "filename": "aws_services_handler.py", "lineno": 26}
{"timestamp": "2025-08-20T16:10:29", "level": "INFO", "name": "app.utils.aws_services_handler", "message": "Criando cliente S3 para a região: us-east-1...", "filename": "aws_services_handler.py", "lineno": 17}
{"timestamp": "2025-08-20T16:10:29", "level": "INFO", "name": "app.utils.aws_services_handler", "message": "Cliente BEDROCK-RUNTIME criado com sucesso.", "filename": "aws_services_handler.py", "lineno": 26}
{"timestamp": "2025-08-20T16:10:29", "level": "INFO", "name": "app.utils.aws_services_handler", "message": "Criando cliente S3 para a região: us-east-1...", "filename": "aws_services_handler.py", "lineno": 17}
{"timestamp": "2025-08-20T16:10:29", "level": "INFO", "name": "app.utils.aws_services_handler", "message": "Cliente S3 criado com sucesso.", "filename": "aws_services_handler.py", "lineno": 26}
{"timestamp": "2025-08-20T16:10:29", "level": "INFO", "name": "app.utils.aws_services_handler", "message": "Cliente S3 criado com sucesso.", "filename": "aws_services_handler.py", "lineno": 26}

In [38]:
textract_results = {}
llm_results = {}

# Process first 3 rows from the dataframe
for index, row in merged_df_autorizacao_final.iterrows():
    pdf_bytes = row['DS_PDF_BYTES']
    file_id = str(row['CD_AVISO_CIRURGIA'])
    
    if pd.isna(pdf_bytes):
        print(f"Skipping row {index}: No PDF bytes available")
        continue
    
    # Extract forms data using Textract
    forms_data = pdf_analyzer.extract_forms_data_from_pdf(
        pdf_bytes=pdf_bytes,
        file_id=file_id
    )
    
    textract_results[file_id] = forms_data
    
    # Process with LLM
    forms_data_str = str(forms_data)
    llm_response = llm_instance.invoke_model(input_str=forms_data_str)
    llm_results[file_id] = llm_response

# Save to dataframes
textract_results_df = pd.DataFrame.from_dict(textract_results, orient="index")
textract_results_df.index.name = "CD_AVISO_CIRURGIA"
textract_results_df = textract_results_df.reset_index()

llm_results_df = pd.DataFrame.from_dict(llm_results, orient="index")
llm_results_df.index.name = "CD_AVISO_CIRURGIA"
llm_results_df = llm_results_df.reset_index()

# Expand LLM results into separate columns
llm_expanded_df = pd.json_normalize(llm_results_df.iloc[:, 1:].to_dict('records'))
llm_expanded_df['CD_AVISO_CIRURGIA'] = llm_results_df['CD_AVISO_CIRURGIA']

# Add suffix to distinguish LLM columns
llm_expanded_df = llm_expanded_df.add_suffix('_llm').rename(columns={'CD_AVISO_CIRURGIA_llm': 'CD_AVISO_CIRURGIA'})

# Convert CD_AVISO_CIRURGIA to int to match the original dataframe type
llm_expanded_df['CD_AVISO_CIRURGIA'] = llm_expanded_df['CD_AVISO_CIRURGIA'].astype(int)

# Inner join with original dataframe
textract_eval_df = merged_df_autorizacao_final.merge(
    llm_expanded_df, 
    on='CD_AVISO_CIRURGIA', 
    how='inner'
)

print(f"Processing completed! Created textract_eval_df with {len(textract_eval_df)} rows")
print(f"LLM columns added: {[col for col in textract_eval_df.columns if col.endswith('_llm')]}")
textract_eval_df.head()

{"timestamp": "2025-08-20T17:01:46", "level": "INFO", "name": "app.utils.textract_service", "message": "PDF uploaded to S3: s3://autorizacoes-textract/guias-pdf/textract_pdfs/857416_20250820_170145_ae0c54d2.pdf", "filename": "textract_service.py", "lineno": 177}
{"timestamp": "2025-08-20T17:01:47", "level": "INFO", "name": "app.utils.textract_service", "message": "Started PDF analysis with JobId: 940808dbb7f19a02fbaaa9784674dd1ea2a096f55e5c83b901ac73862799087a", "filename": "textract_service.py", "lineno": 210}
{"timestamp": "2025-08-20T17:01:47", "level": "INFO", "name": "app.utils.textract_service", "message": "PDF analysis in progress for JobId: 940808dbb7f19a02fbaaa9784674dd1ea2a096f55e5c83b901ac73862799087a", "filename": "textract_service.py", "lineno": 264}
{"timestamp": "2025-08-20T17:01:52", "level": "INFO", "name": "app.utils.textract_service", "message": "PDF analysis in progress for JobId: 940808dbb7f19a02fbaaa9784674dd1ea2a096f55e5c83b901ac73862799087a", "filename": "textract_service.py", "lineno": 264}
{"timestamp": "2025-08-20T17:01:58", "level": "INFO", "name": "app.utils.textract_service", "message": "PDF analysis completed successfully for JobId: 940808dbb7f19a02fbaaa9784674dd1ea2a096f55e5c83b901ac73862799087a", "filename": "textract_service.py", "lineno": 238}
{"timestamp": "2025-08-20T17:01:58", "level": "INFO", "name": "app.utils.textract_service", "message": "Cleaned up S3 object: s3://autorizacoes-textract/guias-pdf/textract_pdfs/857416_20250820_170145_ae0c54d2.pdf", "filename": "textract_service.py", "lineno": 464}
{"timestamp": "2025-08-20T17:01:58", "level": "INFO", "name": "app.utils.textract_service", "message": "Successfully extracted data from PDF. Found 36 key-value pairs and 7 tables", "filename": "textract_service.py", "lineno": 331}
{"timestamp": "2025-08-20T17:03:08", "level": "INFO", "name": "app.utils.textract_service", "message": "PDF uploaded to S3: s3://autorizacoes-textract/guias-pdf/textract_pdfs/857469_20250820_170308_db31a5c7.pdf", "filename": "textract_service.py", "lineno": 177}
{"timestamp": "2025-08-20T17:03:09", "level": "INFO", "name": "app.utils.textract_service", "message": "Started PDF analysis with JobId: f5b8cabc133ec19ac12cd74b86f25e2c2c6cd692d1650bee5c2215daeaf4d701", "filename": "textract_service.py", "lineno": 210}
{"timestamp": "2025-08-20T17:03:09", "level": "INFO", "name": "app.utils.textract_service", "message": "PDF analysis in progress for JobId: f5b8cabc133ec19ac12cd74b86f25e2c2c6cd692d1650bee5c2215daeaf4d701", "filename": "textract_service.py", "lineno": 264}
{"timestamp": "2025-08-20T17:03:15", "level": "INFO", "name": "app.utils.textract_service", "message": "PDF analysis in progress for JobId: f5b8cabc133ec19ac12cd74b86f25e2c2c6cd692d1650bee5c2215daeaf4d701", "filename": "textract_service.py", "lineno": 264}
{"timestamp": "2025-08-20T17:03:21", "level": "INFO", "name": "app.utils.textract_service", "message": "PDF analysis completed successfully for JobId: f5b8cabc133ec19ac12cd74b86f25e2c2c6cd692d1650bee5c2215daeaf4d701", "filename": "textract_service.py", "lineno": 238}
{"timestamp": "2025-08-20T17:03:21", "level": "INFO", "name": "app.utils.textract_service", "message": "Cleaned up S3 object: s3://autorizacoes-textract/guias-pdf/textract_pdfs/857469_20250820_170308_db31a5c7.pdf", "filename": "textract_service.py", "lineno": 464}
{"timestamp": "2025-08-20T17:03:21", "level": "INFO", "name": "app.utils.textract_service", "message": "Successfully extracted data from PDF. Found 31 key-value pairs and 1 tables", "filename": "textract_service.py", "lineno": 331}
{"timestamp": "2025-08-20T17:03:33", "level": "INFO", "name": "app.utils.textract_service", "message": "PDF uploaded to S3: s3://autorizacoes-textract/guias-pdf/textract_pdfs/857883_20250820_170332_b6ee46be.pdf", "filename": "textract_service.py", "lineno": 177}
{"timestamp": "2025-08-20T17:03:34", "level": "INFO", "name": "app.utils.textract_service", "message": "Started PDF analysis with JobId: 2b7bd2d5e9199dd9fe22a1704ff4fc00f5cf03458016e1151cad5c742184da97", "filename": "textract_service.py", "lineno": 210}
{"timestamp": "2025-08-20T17:03:34", "level": "INFO", "name": "app.utils.textract_service", "message": "PDF analysis in progress for JobId: 2b7bd2d5e9199dd9fe22a1704ff4fc00f5cf03458016e1151cad5c742184da97", "filename": "textract_service.py", "lineno": 264}
{"timestamp": "2025-08-20T17:03:37", "level": "INFO", "name": "app.utils.textract_service", "message": "PDF analysis completed successfully for JobId: 2b7bd2d5e9199dd9fe22a1704ff4fc00f5cf03458016e1151cad5c742184da97", "filename": "textract_service.py", "lineno": 238}
{"timestamp": "2025-08-20T17:03:39", "level": "INFO", "name": "app.utils.textract_service", "message": "Cleaned up S3 object: s3://autorizacoes-textract/guias-pdf/textract_pdfs/857883_20250820_170332_b6ee46be.pdf", "filename": "textract_service.py", "lineno": 464}
{"timestamp": "2025-08-20T17:03:39", "level": "INFO", "name": "app.utils.textract_service", "message": "Successfully extracted data from PDF. Found 29 key-value pairs and 1 tables", "filename": "textract_service.py", "lineno": 331}
{"timestamp": "2025-08-20T17:03:55", "level": "INFO", "name": "app.utils.textract_service", "message": "PDF uploaded to S3: s3://autorizacoes-textract/guias-pdf/textract_pdfs/858036_20250820_170354_54609102.pdf", "filename": "textract_service.py", "lineno": 177}
{"timestamp": "2025-08-20T17:03:56", "level": "INFO", "name": "app.utils.textract_service", "message": "Started PDF analysis with JobId: b07ed052e60adf642e7f40384227670ccda6966d6a27a344903604bec1d3fb14", "filename": "textract_service.py", "lineno": 210}
{"timestamp": "2025-08-20T17:03:56", "level": "INFO", "name": "app.utils.textract_service", "message": "PDF analysis in progress for JobId: b07ed052e60adf642e7f40384227670ccda6966d6a27a344903604bec1d3fb14", "filename": "textract_service.py", "lineno": 264}
{"timestamp": "2025-08-20T17:04:02", "level": "INFO", "name": "app.utils.textract_service", "message": "PDF analysis completed successfully for JobId: b07ed052e60adf642e7f40384227670ccda6966d6a27a344903604bec1d3fb14", "filename": "textract_service.py", "lineno": 238}
{"timestamp": "2025-08-20T17:04:03", "level": "INFO", "name": "app.utils.textract_service", "message": "Cleaned up S3 object: s3://autorizacoes-textract/guias-pdf/textract_pdfs/858036_20250820_170354_54609102.pdf", "filename": "textract_service.py", "lineno": 464}
{"timestamp": "2025-08-20T17:04:03", "level": "INFO", "name": "app.utils.textract_service", "message": "Successfully extracted data from PDF. Found 30 key-value pairs and 1 tables", "filename": "textract_service.py", "lineno": 331}
{"timestamp": "2025-08-20T17:04:21", "level": "INFO", "name": "app.utils.textract_service", "message": "PDF uploaded to S3: s3://autorizacoes-textract/guias-pdf/textract_pdfs/859112_20250820_170420_3a03131e.pdf", "filename": "textract_service.py", "lineno": 177}
{"timestamp": "2025-08-20T17:04:22", "level": "INFO", "name": "app.utils.textract_service", "message": "Started PDF analysis with JobId: a9b7c665dde97ae2e40bf15162efde579f49e4d8dd00b21ee2a6cd4112908ff5", "filename": "textract_service.py", "lineno": 210}
{"timestamp": "2025-08-20T17:04:22", "level": "INFO", "name": "app.utils.textract_service", "message": "PDF analysis in progress for JobId: a9b7c665dde97ae2e40bf15162efde579f49e4d8dd00b21ee2a6cd4112908ff5", "filename": "textract_service.py", "lineno": 264}
{"timestamp": "2025-08-20T17:04:27", "level": "INFO", "name": "app.utils.textract_service", "message": "PDF analysis in progress for JobId: a9b7c665dde97ae2e40bf15162efde579f49e4d8dd00b21ee2a6cd4112908ff5", "filename": "textract_service.py", "lineno": 264}
{"timestamp": "2025-08-20T17:04:32", "level": "INFO", "name": "app.utils.textract_service", "message": "PDF analysis in progress for JobId: a9b7c665dde97ae2e40bf15162efde579f49e4d8dd00b21ee2a6cd4112908ff5", "filename": "textract_service.py", "lineno": 264}
{"timestamp": "2025-08-20T17:04:35", "level": "INFO", "name": "app.utils.textract_service", "message": "PDF analysis completed successfully for JobId: a9b7c665dde97ae2e40bf15162efde579f49e4d8dd00b21ee2a6cd4112908ff5", "filename": "textract_service.py", "lineno": 238}
{"timestamp": "2025-08-20T17:04:36", "level": "INFO", "name": "app.utils.textract_service", "message": "Cleaned up S3 object: s3://autorizacoes-textract/guias-pdf/textract_pdfs/859112_20250820_170420_3a03131e.pdf", "filename": "textract_service.py", "lineno": 464}
{"timestamp": "2025-08-20T17:04:36", "level": "INFO", "name": "app.utils.textract_service", "message": "Successfully extracted data from PDF. Found 29 key-value pairs and 2 tables", "filename": "textract_service.py", "lineno": 331}
{"timestamp": "2025-08-20T17:04:50", "level": "INFO", "name": "app.utils.textract_service", "message": "PDF uploaded to S3: s3://autorizacoes-textract/guias-pdf/textract_pdfs/859185_20250820_170449_9b9e3fa7.pdf", "filename": "textract_service.py", "lineno": 177}
{"timestamp": "2025-08-20T17:04:51", "level": "INFO", "name": "app.utils.textract_service", "message": "Started PDF analysis with JobId: 3e9a2d279135bba2469d8548d42d10df084ebf9836206c56ad9db6df2ef87682", "filename": "textract_service.py", "lineno": 210}
{"timestamp": "2025-08-20T17:04:52", "level": "INFO", "name": "app.utils.textract_service", "message": "PDF analysis in progress for JobId: 3e9a2d279135bba2469d8548d42d10df084ebf9836206c56ad9db6df2ef87682", "filename": "textract_service.py", "lineno": 264}
{"timestamp": "2025-08-20T17:04:57", "level": "INFO", "name": "app.utils.textract_service", "message": "PDF analysis in progress for JobId: 3e9a2d279135bba2469d8548d42d10df084ebf9836206c56ad9db6df2ef87682", "filename": "textract_service.py", "lineno": 264}
{"timestamp": "2025-08-20T17:05:03", "level": "INFO", "name": "app.utils.textract_service", "message": "PDF analysis completed successfully for JobId: 3e9a2d279135bba2469d8548d42d10df084ebf9836206c56ad9db6df2ef87682", "filename": "textract_service.py", "lineno": 238}
{"timestamp": "2025-08-20T17:05:02", "level": "INFO", "name": "app.utils.textract_service", "message": "Cleaned up S3 object: s3://autorizacoes-textract/guias-pdf/textract_pdfs/859185_20250820_170449_9b9e3fa7.pdf", "filename": "textract_service.py", "lineno": 464}
{"timestamp": "2025-08-20T17:05:02", "level": "INFO", "name": "app.utils.textract_service", "message": "Successfully extracted data from PDF. Found 92 key-value pairs and 17 tables", "filename": "textract_service.py", "lineno": 331}
{"timestamp": "2025-08-20T17:05:23", "level": "INFO", "name": "app.utils.textract_service", "message": "PDF uploaded to S3: s3://autorizacoes-textract/guias-pdf/textract_pdfs/859989_20250820_170522_591ff891.pdf", "filename": "textract_service.py", "lineno": 177}
{"timestamp": "2025-08-20T17:05:24", "level": "INFO", "name": "app.utils.textract_service", "message": "Started PDF analysis with JobId: b3a3eee859b4e011815a0d732a4ca4a1be25e1be38a6b46252eb725297f090ea", "filename": "textract_service.py", "lineno": 210}
{"timestamp": "2025-08-20T17:05:24", "level": "INFO", "name": "app.utils.textract_service", "message": "PDF analysis in progress for JobId: b3a3eee859b4e011815a0d732a4ca4a1be25e1be38a6b46252eb725297f090ea", "filename": "textract_service.py", "lineno": 264}
{"timestamp": "2025-08-20T17:05:29", "level": "INFO", "name": "app.utils.textract_service", "message": "PDF analysis in progress for JobId: b3a3eee859b4e011815a0d732a4ca4a1be25e1be38a6b46252eb725297f090ea", "filename": "textract_service.py", "lineno": 264}
{"timestamp": "2025-08-20T17:05:32", "level": "INFO", "name": "app.utils.textract_service", "message": "PDF analysis completed successfully for JobId: b3a3eee859b4e011815a0d732a4ca4a1be25e1be38a6b46252eb725297f090ea", "filename": "textract_service.py", "lineno": 238}
{"timestamp": "2025-08-20T17:05:33", "level": "INFO", "name": "app.utils.textract_service", "message": "Cleaned up S3 object: s3://autorizacoes-textract/guias-pdf/textract_pdfs/859989_20250820_170522_591ff891.pdf", "filename": "textract_service.py", "lineno": 464}
{"timestamp": "2025-08-20T17:05:33", "level": "INFO", "name": "app.utils.textract_service", "message": "Successfully extracted data from PDF. Found 29 key-value pairs and 1 tables", "filename": "textract_service.py", "lineno": 331}
{"timestamp": "2025-08-20T17:05:46", "level": "INFO", "name": "app.utils.textract_service", "message": "PDF uploaded to S3: s3://autorizacoes-textract/guias-pdf/textract_pdfs/861063_20250820_170545_41395699.pdf", "filename": "textract_service.py", "lineno": 177}
{"timestamp": "2025-08-20T17:05:47", "level": "INFO", "name": "app.utils.textract_service", "message": "Started PDF analysis with JobId: e37baf5936c06d080827f9375a4813b432e8a11f9a197227ef2856b936a89cd1", "filename": "textract_service.py", "lineno": 210}
{"timestamp": "2025-08-20T17:05:47", "level": "INFO", "name": "app.utils.textract_service", "message": "PDF analysis in progress for JobId: e37baf5936c06d080827f9375a4813b432e8a11f9a197227ef2856b936a89cd1", "filename": "textract_service.py", "lineno": 264}
{"timestamp": "2025-08-20T17:05:52", "level": "INFO", "name": "app.utils.textract_service", "message": "PDF analysis in progress for JobId: e37baf5936c06d080827f9375a4813b432e8a11f9a197227ef2856b936a89cd1", "filename": "textract_service.py", "lineno": 264}
{"timestamp": "2025-08-20T17:05:58", "level": "INFO", "name": "app.utils.textract_service", "message": "PDF analysis completed successfully for JobId: e37baf5936c06d080827f9375a4813b432e8a11f9a197227ef2856b936a89cd1", "filename": "textract_service.py", "lineno": 238}
{"timestamp": "2025-08-20T17:05:59", "level": "INFO", "name": "app.utils.textract_service", "message": "Cleaned up S3 object: s3://autorizacoes-textract/guias-pdf/textract_pdfs/861063_20250820_170545_41395699.pdf", "filename": "textract_service.py", "lineno": 464}
{"timestamp": "2025-08-20T17:05:59", "level": "INFO", "name": "app.utils.textract_service", "message": "Successfully extracted data from PDF. Found 33 key-value pairs and 1 tables", "filename": "textract_service.py", "lineno": 331}
{"timestamp": "2025-08-20T17:06:11", "level": "INFO", "name": "app.utils.textract_service", "message": "PDF uploaded to S3: s3://autorizacoes-textract/guias-pdf/textract_pdfs/861179_20250820_170610_8eb70940.pdf", "filename": "textract_service.py", "lineno": 177}
{"timestamp": "2025-08-20T17:06:12", "level": "INFO", "name": "app.utils.textract_service", "message": "Started PDF analysis with JobId: 74b3ab300f05bc21d4ff37ef8814e6b27a9a2490047c5e793ec167c065819aa6", "filename": "textract_service.py", "lineno": 210}
{"timestamp": "2025-08-20T17:06:12", "level": "INFO", "name": "app.utils.textract_service", "message": "PDF analysis in progress for JobId: 74b3ab300f05bc21d4ff37ef8814e6b27a9a2490047c5e793ec167c065819aa6", "filename": "textract_service.py", "lineno": 264}
{"timestamp": "2025-08-20T17:06:17", "level": "INFO", "name": "app.utils.textract_service", "message": "PDF analysis in progress for JobId: 74b3ab300f05bc21d4ff37ef8814e6b27a9a2490047c5e793ec167c065819aa6", "filename": "textract_service.py", "lineno": 264}
{"timestamp": "2025-08-20T17:06:23", "level": "INFO", "name": "app.utils.textract_service", "message": "PDF analysis completed successfully for JobId: 74b3ab300f05bc21d4ff37ef8814e6b27a9a2490047c5e793ec167c065819aa6", "filename": "textract_service.py", "lineno": 238}
{"timestamp": "2025-08-20T17:06:24", "level": "INFO", "name": "app.utils.textract_service", "message": "Cleaned up S3 object: s3://autorizacoes-textract/guias-pdf/textract_pdfs/861179_20250820_170610_8eb70940.pdf", "filename": "textract_service.py", "lineno": 464}
{"timestamp": "2025-08-20T17:06:24", "level": "INFO", "name": "app.utils.textract_service", "message": "Successfully extracted data from PDF. Found 31 key-value pairs and 0 tables", "filename": "textract_service.py", "lineno": 331}
{"timestamp": "2025-08-20T17:06:35", "level": "INFO", "name": "app.utils.textract_service", "message": "PDF uploaded to S3: s3://autorizacoes-textract/guias-pdf/textract_pdfs/861465_20250820_170634_fd90731e.pdf", "filename": "textract_service.py", "lineno": 177}
{"timestamp": "2025-08-20T17:06:36", "level": "INFO", "name": "app.utils.textract_service", "message": "Started PDF analysis with JobId: 07b5ab9b141283105963ae0981d84315c310f173962f43602e2340382fa753b5", "filename": "textract_service.py", "lineno": 210}
{"timestamp": "2025-08-20T17:06:36", "level": "INFO", "name": "app.utils.textract_service", "message": "PDF analysis in progress for JobId: 07b5ab9b141283105963ae0981d84315c310f173962f43602e2340382fa753b5", "filename": "textract_service.py", "lineno": 264}
{"timestamp": "2025-08-20T17:06:41", "level": "INFO", "name": "app.utils.textract_service", "message": "PDF analysis in progress for JobId: 07b5ab9b141283105963ae0981d84315c310f173962f43602e2340382fa753b5", "filename": "textract_service.py", "lineno": 264}
{"timestamp": "2025-08-20T17:06:47", "level": "INFO", "name": "app.utils.textract_service", "message": "PDF analysis completed successfully for JobId: 07b5ab9b141283105963ae0981d84315c310f173962f43602e2340382fa753b5", "filename": "textract_service.py", "lineno": 238}
{"timestamp": "2025-08-20T17:06:48", "level": "INFO", "name": "app.utils.textract_service", "message": "Cleaned up S3 object: s3://autorizacoes-textract/guias-pdf/textract_pdfs/861465_20250820_170634_fd90731e.pdf", "filename": "textract_service.py", "lineno": 464}
{"timestamp": "2025-08-20T17:06:48", "level": "INFO", "name": "app.utils.textract_service", "message": "Successfully extracted data from PDF. Found 30 key-value pairs and 2 tables", "filename": "textract_service.py", "lineno": 331}
{"timestamp": "2025-08-20T17:07:00", "level": "INFO", "name": "app.utils.textract_service", "message": "PDF uploaded to S3: s3://autorizacoes-textract/guias-pdf/textract_pdfs/861565_20250820_170700_00ccb771.pdf", "filename": "textract_service.py", "lineno": 177}
{"timestamp": "2025-08-20T17:07:01", "level": "INFO", "name": "app.utils.textract_service", "message": "Started PDF analysis with JobId: 5ade873ed089151947382bb71ee5535922fff8702bb1a3d8ced49b5042a648f6", "filename": "textract_service.py", "lineno": 210}
{"timestamp": "2025-08-20T17:07:02", "level": "INFO", "name": "app.utils.textract_service", "message": "PDF analysis in progress for JobId: 5ade873ed089151947382bb71ee5535922fff8702bb1a3d8ced49b5042a648f6", "filename": "textract_service.py", "lineno": 264}
{"timestamp": "2025-08-20T17:07:07", "level": "INFO", "name": "app.utils.textract_service", "message": "PDF analysis in progress for JobId: 5ade873ed089151947382bb71ee5535922fff8702bb1a3d8ced49b5042a648f6", "filename": "textract_service.py", "lineno": 264}
{"timestamp": "2025-08-20T17:07:13", "level": "INFO", "name": "app.utils.textract_service", "message": "PDF analysis completed successfully for JobId: 5ade873ed089151947382bb71ee5535922fff8702bb1a3d8ced49b5042a648f6", "filename": "textract_service.py", "lineno": 238}
{"timestamp": "2025-08-20T17:07:13", "level": "INFO", "name": "app.utils.textract_service", "message": "Cleaned up S3 object: s3://autorizacoes-textract/guias-pdf/textract_pdfs/861565_20250820_170700_00ccb771.pdf", "filename": "textract_service.py", "lineno": 464}
{"timestamp": "2025-08-20T17:07:13", "level": "INFO", "name": "app.utils.textract_service", "message": "Successfully extracted data from PDF. Found 32 key-value pairs and 1 tables", "filename": "textract_service.py", "lineno": 331}
{"timestamp": "2025-08-20T17:07:36", "level": "INFO", "name": "app.utils.textract_service", "message": "PDF uploaded to S3: s3://autorizacoes-textract/guias-pdf/textract_pdfs/862378_20250820_170735_56b4ab36.pdf", "filename": "textract_service.py", "lineno": 177}

Processing completed! Created textract_eval_df with 60 rows
LLM columns added: ['procedimento_autorizado_llm', 'paciente_llm', 'codigo_autorizado_llm', 'senha_llm', 'validade_senha_llm', 'observacoes_opme_llm', 'observacoes_gerais_llm', 'profissional_solicitante_llm']

,CD_AVISO_CIRURGIA,DS_PROCEDIMENTO,CD_GUIA,CD_SENHA,DS_GUIA_PATH,DS_CONTATO,DS_PDF_BYTES,paciente_gt,codigo_autorizado_gt,senha_gt,validade_senha_gt,observacoes_opme_gt,observacoes_gerais_gt,usuario_finalizador_gt,procedimento_autorizado_llm,paciente_llm,codigo_autorizado_llm,senha_llm,validade_senha_llm,observacoes_opme_llm,observacoes_gerais_llm,profissional_solicitante_llm
0,857416,"[{""code"":30101557,""description"":""EXCISAO E ROT...",19494856.0,None,https://cdns.overmind.ai/autorizacao-cemig-000...,\n Procedimento Autorizado\n Pacient...,b'%PDF-1.3\n%\xb7\xbe\xad\xaa\n1 0 obj\n<<\n/T...,SALETE EMILIA DOS SANTOS LIMA,"01009001 x 1\n,30101557 x 1",000120250700053801,10/08/2025,Pedido sem OPME,None,Deisiane,"EXTENSOS FERIMENTOS, CICATRIZES OU TUMORES EXE...",SALETE EMILIA DOS SANTOS LIMA,30101557 x 1,0001.2025.07-00053801,10/08/25,Pedido sem OPME,Solicitacao de autorizacao,KAYO VIEIRA TEODORAK PÊGO
1,857469,"[{""code"":30907136,""description"":""VARIZES - TRA...",19495507.0,J5VEYT7,https://cdns.overmind.ai/autorizacao-bradesco-...,\n Procedimento Autorizado\n Pacient...,b'%PDF-1.4\n%\xe2\xe3\xcf\xd3\n4 0 obj\n<</Len...,BARBARA ARAUJO SCHNNEPPEL CORREA,"01009001 x 1\n,30907136 x 1",J5VEYT7,07/01/2026,Pedido sem OPME,Diária: 01,TELMA,VARIZES TRATAMENTO CIRURGICO DE DOIS MEMBROS,BARBARA ARAUJO SCHNNEPPEL CORREA,30907136 x 1,J5VEYT7,None,Pedido sem OPME,Diária: 1,MATEUS ALVES BORGES CRISTINO
2,857883,"[{""code"":30205050,""description"":""AMIGDALECTOMI...",19506292.0,J5VEW29,https://cdns.overmind.ai/autorizacao-bradesco-...,\n Procedimento Autorizado\n Pacient...,b'%PDF-1.4\n%\xe2\xe3\xcf\xd3\n4 0 obj\n<</Len...,MILENA RAFAELA TRINDADE,"01009001 x 1\n,30205050 x 1\n,30205271 x 1\n,3...",J5VEW29,07/01/2026,Pedido sem OPME,None,ANA,AMIGDALECTOMIA DAS PALATINAS,MILENA RAFAELA TRINDADE,"30205050 x 1, 30205069 x 1, 30205271 x 1, 3050...",J5VEW29,None,Pedido sem OPME,ADM(REDE NACIONAL (0) PL. ADM(REDE NACIONAL (0...,AURELIA ALBUQUERQUE MARTINS
3,858036,"[{""code"":30205247,""description"":""UVULOPALATO-F...",19508906.0,J5VEWF9,https://cdns.overmind.ai/autorizacao-bradesco-...,\n Procedimento Parcialmente autorizado\n...,b'%PDF-1.4\n%\xe2\xe3\xcf\xd3\n4 0 obj\n<</Len...,DIONE RAIMUNDO CARVALHO PINTO,"30502349 x 0\n,30205247 x 1\n,30501369 x 1\n,3...",J5VEWF9,06/01/2026,Pedido sem OPME,None,BRUNA FERNANDA,AMIGDALECTOMIA DAS PALATINAS,DIONE RAIMUNDO CARVALHO PINTO,"30205050 x 1, 30205069 x 1, 30205247 x 1, 3050...",J5VEWF9,None,Pedido sem OPME,ADM(REDE NACIONAL (0) PL. ADM(REDE NACIONAL (0...,LUCAS EDUARDO DE OLIVEIRA
4,859112,"[{""code"":30501350,""description"":""RINOSSEPTOPLA...",19537543.0,5045663575,https://cdns.overmind.ai/autorizacao-sulameric...,\n Procedimento Autorizado\n Pacient...,b'%PDF-1.4\n%\xf6\xe4\xfc\xdf\n1 0 obj\n<<\n/T...,LEANDRO SALOMAO ROSA,"01009001 x 1\n,30501350 x 1\n,30501458 x 2",5045663575,19/08/2025,Pedido sem OPME,Diária: 01,TELMA,SEPTOPLASTIA TURBINECTOMIA,LEANDRO S ROSA,"65300114 x 1, 30501458 x 2, 30501350 x 1",5045663575,19/08/2025,Pedido sem OPME,Diária: 01,None

In [41]:
# able to see all pandas cols
pd.set_option('display.max_columns', None)
# apply cleaning on the value from cols senha_llm using re to clean white spaces and special characters
import re

def clean_text(text):
    if pd.notna(text):
        text = re.sub(r'\s+', ' ', text)  # Replace multiple spaces with a single space
        text = re.sub(r'[^\w\s]', '', text)  # Remove special characters
        return text.strip()
    return ""

textract_eval_df['senha_llm'] = textract_eval_df['senha_llm'].apply(clean_text)
textract_eval_df.head()

,CD_AVISO_CIRURGIA,DS_PROCEDIMENTO,CD_GUIA,CD_SENHA,DS_GUIA_PATH,DS_CONTATO,DS_PDF_BYTES,paciente_gt,codigo_autorizado_gt,senha_gt,validade_senha_gt,observacoes_opme_gt,observacoes_gerais_gt,usuario_finalizador_gt,procedimento_autorizado_llm,paciente_llm,codigo_autorizado_llm,senha_llm,validade_senha_llm,observacoes_opme_llm,observacoes_gerais_llm,profissional_solicitante_llm
0,857416,"[{""code"":30101557,""description"":""EXCISAO E ROT...",19494856.0,None,https://cdns.overmind.ai/autorizacao-cemig-000...,\n Procedimento Autorizado\n Pacient...,b'%PDF-1.3\n%\xb7\xbe\xad\xaa\n1 0 obj\n<<\n/T...,SALETE EMILIA DOS SANTOS LIMA,"01009001 x 1\n,30101557 x 1",000120250700053801,10/08/2025,Pedido sem OPME,None,Deisiane,"EXTENSOS FERIMENTOS, CICATRIZES OU TUMORES EXE...",SALETE EMILIA DOS SANTOS LIMA,30101557 x 1,000120250700053801,10/08/25,Pedido sem OPME,Solicitacao de autorizacao,KAYO VIEIRA TEODORAK PÊGO
1,857469,"[{""code"":30907136,""description"":""VARIZES - TRA...",19495507.0,J5VEYT7,https://cdns.overmind.ai/autorizacao-bradesco-...,\n Procedimento Autorizado\n Pacient...,b'%PDF-1.4\n%\xe2\xe3\xcf\xd3\n4 0 obj\n<</Len...,BARBARA ARAUJO SCHNNEPPEL CORREA,"01009001 x 1\n,30907136 x 1",J5VEYT7,07/01/2026,Pedido sem OPME,Diária: 01,TELMA,VARIZES TRATAMENTO CIRURGICO DE DOIS MEMBROS,BARBARA ARAUJO SCHNNEPPEL CORREA,30907136 x 1,J5VEYT7,None,Pedido sem OPME,Diária: 1,MATEUS ALVES BORGES CRISTINO
2,857883,"[{""code"":30205050,""description"":""AMIGDALECTOMI...",19506292.0,J5VEW29,https://cdns.overmind.ai/autorizacao-bradesco-...,\n Procedimento Autorizado\n Pacient...,b'%PDF-1.4\n%\xe2\xe3\xcf\xd3\n4 0 obj\n<</Len...,MILENA RAFAELA TRINDADE,"01009001 x 1\n,30205050 x 1\n,30205271 x 1\n,3...",J5VEW29,07/01/2026,Pedido sem OPME,None,ANA,AMIGDALECTOMIA DAS PALATINAS,MILENA RAFAELA TRINDADE,"30205050 x 1, 30205069 x 1, 30205271 x 1, 3050...",J5VEW29,None,Pedido sem OPME,ADM(REDE NACIONAL (0) PL. ADM(REDE NACIONAL (0...,AURELIA ALBUQUERQUE MARTINS
3,858036,"[{""code"":30205247,""description"":""UVULOPALATO-F...",19508906.0,J5VEWF9,https://cdns.overmind.ai/autorizacao-bradesco-...,\n Procedimento Parcialmente autorizado\n...,b'%PDF-1.4\n%\xe2\xe3\xcf\xd3\n4 0 obj\n<</Len...,DIONE RAIMUNDO CARVALHO PINTO,"30502349 x 0\n,30205247 x 1\n,30501369 x 1\n,3...",J5VEWF9,06/01/2026,Pedido sem OPME,None,BRUNA FERNANDA,AMIGDALECTOMIA DAS PALATINAS,DIONE RAIMUNDO CARVALHO PINTO,"30205050 x 1, 30205069 x 1, 30205247 x 1, 3050...",J5VEWF9,None,Pedido sem OPME,ADM(REDE NACIONAL (0) PL. ADM(REDE NACIONAL (0...,LUCAS EDUARDO DE OLIVEIRA
4,859112,"[{""code"":30501350,""description"":""RINOSSEPTOPLA...",19537543.0,5045663575,https://cdns.overmind.ai/autorizacao-sulameric...,\n Procedimento Autorizado\n Pacient...,b'%PDF-1.4\n%\xf6\xe4\xfc\xdf\n1 0 obj\n<<\n/T...,LEANDRO SALOMAO ROSA,"01009001 x 1\n,30501350 x 1\n,30501458 x 2",5045663575,19/08/2025,Pedido sem OPME,Diária: 01,TELMA,SEPTOPLASTIA TURBINECTOMIA,LEANDRO S ROSA,"65300114 x 1, 30501458 x 2, 30501350 x 1",5045663575,19/08/2025,Pedido sem OPME,Diária: 01,None

In [42]:
#save textract_eval_df to sql
import sqlalchemy
eval_engine = sqlalchemy.create_engine("sqlite:///textract_eval_database.sqlite")
textract_eval_df.to_sql("textract_eval", con=eval_engine, if_exists="replace", index=False)

60

# 4 evaluation on extract and curated data df from llm

In [ ]:
# load textract_eval_df
import sqlalchemy
import pandas as pd

eval_engine = sqlalchemy.create_engine("sqlite:///textract_eval_database.sqlite")
textract_eval_df = pd.read_sql("SELECT * FROM textract_eval", con=eval_engine)

In [43]:
# display the df in html format so we can click of the link
# Create a new column with clickable links for DS_GUIA_PATH
def make_clickable(url):
    if pd.notna(url):
        return f'<a href="{url}" target="_blank">{url}</a>'
    return ""
textract_eval_df['DS_GUIA_PATH_CLICKABLE'] = textract_eval_df['DS_GUIA_PATH'].apply(make_clickable)
from IPython.display import display, HTML
display(HTML(textract_eval_df[['CD_AVISO_CIRURGIA','DS_GUIA_PATH', 'DS_GUIA_PATH_CLICKABLE']].head(10).to_html(escape=False)))

In [44]:
aviso = 861465	
print(textract_eval_df[textract_eval_df['CD_AVISO_CIRURGIA'] == aviso]["DS_CONTATO"].values)
print(50*"-")
print("paciente")
print(textract_eval_df[textract_eval_df['CD_AVISO_CIRURGIA'] == aviso]["paciente_llm"].values)

print("codigo autorizacoes e quantidade autorizada")
print(textract_eval_df[textract_eval_df['CD_AVISO_CIRURGIA'] == aviso]["codigo_autorizado_llm"].values)

print("senha")
print(textract_eval_df[textract_eval_df['CD_AVISO_CIRURGIA'] == aviso]["senha_llm"].values)

print("validade da senha")
print(textract_eval_df[textract_eval_df['CD_AVISO_CIRURGIA'] == aviso]["validade_senha_llm"].values)

print("observacoes opme")
print(textract_eval_df[textract_eval_df['CD_AVISO_CIRURGIA'] == aviso]["observacoes_opme_llm"].values)

['\n      Procedimento Autorizado\n      Paciente: JOICILANE MARTINS CAMPOS E FAGUNDES\n      CÓDIGO AUTORIZADO:\n      30301181 x 2\n,30301050 x 2\n,30313015 x 2\n,01009012 x 1\n\n      \n      SENHA: 5046174148\n      VALIDADE DA SENHA: 05/09/2025\n      OBSERVAÇÕES OPME: Pedido sem OPME\n      \n      NOME USUÁRIO FINALIZOU O PEDIDO: LEILA\n    ']
--------------------------------------------------
paciente
['JOICILANE MARTINS c E FAGUNDES']
codigo autorizacoes e quantidade autorizada
['30313015 x 2, 30301181 x 2, 30301050 x 2']
senha
['5046174148']
validade da senha
['05/09/2025']
observacoes opme
['Pedido sem OPME']