# Part 1

load the dataframe into memory and bring it to a valid input for unstructured

In [1]:
# load into memory
import sqlalchemy
import pandas as pd
# allow dataframe to show all columns
pd.set_option('display.max_columns', None)
# Create a database connection
engine = sqlalchemy.create_engine("sqlite:///docs/gold_autorizacao_database.sqlite")
merged_df_autorizacao_final = pd.read_sql("SELECT * FROM autorizacao", engine)

In [2]:
merged_df_autorizacao_final.head()

,CD_AVISO_CIRURGIA,DS_PROCEDIMENTO,CD_GUIA,CD_SENHA,DS_GUIA_PATH,DS_CONTATO
0,857416,"[{""code"":30101557,""description"":""EXCISAO E ROT...",19494856.0,None,https://cdns.overmind.ai/autorizacao-cemig-000...,\n Procedimento Autorizado\n Pacient...
1,857469,"[{""code"":30907136,""description"":""VARIZES - TRA...",19495507.0,J5VEYT7,https://cdns.overmind.ai/autorizacao-bradesco-...,\n Procedimento Autorizado\n Pacient...
2,857883,"[{""code"":30205050,""description"":""AMIGDALECTOMI...",19506292.0,J5VEW29,https://cdns.overmind.ai/autorizacao-bradesco-...,\n Procedimento Autorizado\n Pacient...
3,858036,"[{""code"":30205247,""description"":""UVULOPALATO-F...",19508906.0,J5VEWF9,https://cdns.overmind.ai/autorizacao-bradesco-...,\n Procedimento Parcialmente autorizado\n...
4,859112,"[{""code"":30501350,""description"":""RINOSSEPTOPLA...",19537543.0,5045663575,https://cdns.overmind.ai/autorizacao-sulameric...,\n Procedimento Autorizado\n Pacient...

In [3]:
import requests
import numpy as np
def fetch_pdf_bytes(url):
    try:
        response = requests.get(url, timeout=15)
        if response.status_code == 200 and 'application/pdf' in response.headers.get('content-type', ''):
            return response.content
        else:
            return np.nan
    except Exception as e:
        print(f"Error fetching {url}: {e}")
        return np.nan

# Apply to all links in DS_GUIA_PATH
merged_df_autorizacao_final['DS_PDF_BYTES'] = merged_df_autorizacao_final['DS_GUIA_PATH'].apply(fetch_pdf_bytes)
merged_df_autorizacao_final.head()

,CD_AVISO_CIRURGIA,DS_PROCEDIMENTO,CD_GUIA,CD_SENHA,DS_GUIA_PATH,DS_CONTATO,DS_PDF_BYTES
0,857416,"[{""code"":30101557,""description"":""EXCISAO E ROT...",19494856.0,None,https://cdns.overmind.ai/autorizacao-cemig-000...,\n Procedimento Autorizado\n Pacient...,b'%PDF-1.3\n%\xb7\xbe\xad\xaa\n1 0 obj\n<<\n/T...
1,857469,"[{""code"":30907136,""description"":""VARIZES - TRA...",19495507.0,J5VEYT7,https://cdns.overmind.ai/autorizacao-bradesco-...,\n Procedimento Autorizado\n Pacient...,b'%PDF-1.4\n%\xe2\xe3\xcf\xd3\n4 0 obj\n<</Len...
2,857883,"[{""code"":30205050,""description"":""AMIGDALECTOMI...",19506292.0,J5VEW29,https://cdns.overmind.ai/autorizacao-bradesco-...,\n Procedimento Autorizado\n Pacient...,b'%PDF-1.4\n%\xe2\xe3\xcf\xd3\n4 0 obj\n<</Len...
3,858036,"[{""code"":30205247,""description"":""UVULOPALATO-F...",19508906.0,J5VEWF9,https://cdns.overmind.ai/autorizacao-bradesco-...,\n Procedimento Parcialmente autorizado\n...,b'%PDF-1.4\n%\xe2\xe3\xcf\xd3\n4 0 obj\n<</Len...
4,859112,"[{""code"":30501350,""description"":""RINOSSEPTOPLA...",19537543.0,5045663575,https://cdns.overmind.ai/autorizacao-sulameric...,\n Procedimento Autorizado\n Pacient...,b'%PDF-1.4\n%\xf6\xe4\xfc\xdf\n1 0 obj\n<<\n/T...

In [4]:
# localize the value of DS_PROCEDIMENTO of df merged_df_autorizacao_final FOR CD_AVISO_CIRURGIA =
ds_contato = merged_df_autorizacao_final.loc[merged_df_autorizacao_final['CD_AVISO_CIRURGIA'] == 859112, 'DS_CONTATO'].values[0]
ds_contato

'\n      Procedimento Autorizado\n      Paciente: LEANDRO SALOMAO ROSA\n      CÓDIGO AUTORIZADO:\n      01009001 x 1\n,30501350 x 1\n,30501458 x 2\n\n      \n      SENHA: 5045663575\n      VALIDADE DA SENHA: 19/08/2025\n      OBSERVAÇÕES OPME: Pedido sem OPME\n      OBSERVAÇÕES GERAIS: Diária: 01\n      NOME USUÁRIO FINALIZOU O PEDIDO: TELMA\n    '

In [5]:
ds_procedimento = merged_df_autorizacao_final.loc[merged_df_autorizacao_final['CD_AVISO_CIRURGIA'] == 857469, 'DS_PROCEDIMENTO'].values[0]
ds_procedimento

'[{"code":30907136,"description":"VARIZES - TRATAMENTO CIRURGICO BILATERAL","isMain":true,"pro_fat_id":"30907136","procedure_code":30907136,"quantity":1,"surgery_id":2760}]'

In [6]:
# Create a new column with clickable links for DS_GUIA_PATH
def make_clickable(url):
    if pd.notna(url):
        return f'<a href="{url}" target="_blank">{url}</a>'
    return ""
merged_df_autorizacao_final['DS_GUIA_PATH_CLICKABLE'] = merged_df_autorizacao_final['DS_GUIA_PATH'].apply(make_clickable)
from IPython.display import display, HTML
display(HTML(merged_df_autorizacao_final[['DS_GUIA_PATH', 'DS_GUIA_PATH_CLICKABLE']].head(10).to_html(escape=False)))

# 1.9 save dataframe to sql db

In [35]:
# save merged df
import sqlalchemy

# Create a database connection
engine = sqlalchemy.create_engine("sqlite:///merged_autorizacao.sqlite")


# Save the DataFrame to a SQLite table
merged_df_autorizacao_final.to_sql("merged_aut", engine, if_exists="replace", index=False)

60

In [34]:
merged_df_autorizacao_final.head()

,CD_AVISO_CIRURGIA,DS_PROCEDIMENTO,CD_GUIA,CD_SENHA,DS_GUIA_PATH,DS_CONTATO,DS_PDF_BYTES,DS_GUIA_PATH_CLICKABLE
0,857416,"[{""code"":30101557,""description"":""EXCISAO E ROT...",19494856.0,None,https://cdns.overmind.ai/autorizacao-cemig-000...,\n Procedimento Autorizado\n Pacient...,b'%PDF-1.3\n%\xb7\xbe\xad\xaa\n1 0 obj\n<<\n/T...,"<a href=""https://cdns.overmind.ai/autorizacao-..."
1,857469,"[{""code"":30907136,""description"":""VARIZES - TRA...",19495507.0,J5VEYT7,https://cdns.overmind.ai/autorizacao-bradesco-...,\n Procedimento Autorizado\n Pacient...,b'%PDF-1.4\n%\xe2\xe3\xcf\xd3\n4 0 obj\n<</Len...,"<a href=""https://cdns.overmind.ai/autorizacao-..."
2,857883,"[{""code"":30205050,""description"":""AMIGDALECTOMI...",19506292.0,J5VEW29,https://cdns.overmind.ai/autorizacao-bradesco-...,\n Procedimento Autorizado\n Pacient...,b'%PDF-1.4\n%\xe2\xe3\xcf\xd3\n4 0 obj\n<</Len...,"<a href=""https://cdns.overmind.ai/autorizacao-..."
3,858036,"[{""code"":30205247,""description"":""UVULOPALATO-F...",19508906.0,J5VEWF9,https://cdns.overmind.ai/autorizacao-bradesco-...,\n Procedimento Parcialmente autorizado\n...,b'%PDF-1.4\n%\xe2\xe3\xcf\xd3\n4 0 obj\n<</Len...,"<a href=""https://cdns.overmind.ai/autorizacao-..."
4,859112,"[{""code"":30501350,""description"":""RINOSSEPTOPLA...",19537543.0,5045663575,https://cdns.overmind.ai/autorizacao-sulameric...,\n Procedimento Autorizado\n Pacient...,b'%PDF-1.4\n%\xf6\xe4\xfc\xdf\n1 0 obj\n<<\n/T...,"<a href=""https://cdns.overmind.ai/autorizacao-..."

# Part 2 - processing with unstructured

In [7]:
import io
from unstructured.partition.pdf import partition_pdf

# Get the PDF bytes for the desired row
pdf_bytes = merged_df_autorizacao_final["DS_PDF_BYTES"][merged_df_autorizacao_final['CD_AVISO_CIRURGIA'] == 857469].values[0]

# Wrap the bytes in a BytesIO object
pdf_file_like = io.BytesIO(pdf_bytes)

# Now pass to partition_pdf
elements = partition_pdf(file=pdf_file_like, languages=["portuguese"])

# Join the text
full_text = "\n".join([el.text for el in elements if el.text])

/home/joao/projects/company_projects/autorizacoes-api/.venv/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [8]:
print(full_text)

Bradesco Seguros
Guia de Solicitação de Internação 2 - N° Guia no Prestador
1 - Registro ANS 005711
3 - Número da Guia Atribuído pela Operadora 121223221
4 - Data da Autorização 11/07/2025
5 - Senha
J5VEYT7
6 - Data de Validade da Senha
Dados do Beneficiário
7 - Número da Carteira 775432013269019
8 - Validade da Carteira
9 - Atendimento a RN Não
50 - Nome Social
10 - Nome BARBARA ARAUJO SCHNNEPPEL CORREA
Dados do Contratado Solicitante
12 - Código na Operadora 426512
13 - Nome do Contratado HOSPITAL MATER DEI
14 - Nome do Profissional Solicitante MATEUS ALVES BORGES CRISTINO
15 - Conselho Profissional
CRM
16 - Número do Conselho
43236
17 - UF
MG
18 - Código CBO
292 MEDICO CLINICO
Dados do Hospital / Local Solicitado / Dados da Internação
19 - Código na Operadora / CNPJ 426512
20 - Nome do Hospital/ Local Solicitado HOSPITAL MATER DEI
21 - Data Sugerida para Internação (Real) 12/07/2025
22 - Caráter do
23 -Tipo de
24 - Regime de Internação
25 - Qtde. Diárias
26 - Previsão de uso de OPME
27 - Previsão de uso de Quimioterápico
ELETIVO
2
HOSPITALAR
1
28 - Indicação Clínica
DN: ; DC: ; DA: ; I: ; P: ; GR: ; A: ; UTI: N; RV: N; OBS: Solicitacao de autorizacao -
29 - CID 10 Principal
30 - CID 10 (2)
31 - CID 10 (3)
32 - CID 10 (4)
33 - Indicação de Acidente (acidente ou doença
Procedimentos ou Itens Assistenciais Adicionais
34 - Tabela
35 - Código do Procedimento ou Item Assistencial
36 - Descrição
37 - Qtde. Solic.
38 - Qtde. Aut.
16
30907136
VARIZES - TRATAMENTO CIRURGICO DE DOIS MEMBROS
1
1
Dados de Autorização
39 - Data Provável da Admissão
40 - Qtde. Diárias Autorizadas
41 - Tipo da Acomodação Autorizada
12/07/2025
1
QUARTO PARTICULAR
42 - Código na Operadora / CNPJ autorizado
43 - Nome do Hospital / Local Autorizado
44 - Código CNES
45 - Observação / Justificativa - ADM(PL. EMPRESARIAL - NACIONAL II(227)) MED(AUTORIZADO INTEGRAL. PROCEDIMENTOS E OPMEs AUTORIZADOS CONFORME SOLICITAÇÃO MÉDICA. ) FIN(s/acomp)
46 - Data da Solicitação 11/07/2025
47 - Assinatura do Profissional Solicitante
48 - Assinatura do Beneficiário ou Responsável
49 - Assinatura do Responsável pela Autorização
Gerado em: 11/07/2025 09:32

In [9]:
# taking this output and processing trough a llm

import sys

# add app to path so we dont get the error ModuleNotFoundError: No module named 'app'
from pathlib import Path
sys.path.append(str(Path.cwd().parent))
from app.utils.llm_service import AnthropicLLMService
from app.utils.aws_services_handler import create_boto3_client
from app.utils.config import load_config, AppConstants
from app.utils.logger import get_logger
from app.utils.system_prompts.autorizacao_prompt import Prompts


logger = get_logger(name=__name__)
config_vars = load_config()

In [10]:
app_constants = AppConstants()
bedrock_client = create_boto3_client("bedrock-runtime", config_vars)
autorizacao_prompt = Prompts.autorizacao_extraction_prompt

llm_instance = AnthropicLLMService(
    model_id=app_constants.BEDROCK_DEFAULT_MODEL_ID,
    model_version=app_constants.BEDROCK_DEFAULT_MODEL_VERSION,
    client=bedrock_client,
    system_prompt=autorizacao_prompt,
    max_tokens=app_constants.MAX_TOKENS,
    temperature=app_constants.TEMPERATURE,
    budget_tokens=app_constants.BUDGET_TOKENS
)

{"timestamp": "2025-08-20T12:28:08", "level": "INFO", "name": "app.utils.aws_services_handler", "message": "Criando cliente BEDROCK-RUNTIME para a região: us-east-1...", "filename": "aws_services_handler.py", "lineno": 17}
{"timestamp": "2025-08-20T12:28:08", "level": "INFO", "name": "app.utils.aws_services_handler", "message": "Cliente BEDROCK-RUNTIME criado com sucesso.", "filename": "aws_services_handler.py", "lineno": 26}

In [11]:
# testing a single answer of the llm

results = llm_instance.invoke_model(
    input_str=full_text
)

In [12]:
results

{'procedimento_autorizado': 'VARIZES - TRATAMENTO CIRURGICO DE DOIS MEMBROS',
 'paciente': 'BARBARA ARAUJO SCHNNEPPEL CORREA',
 'codigo_autorizado': '30907136 - 1',
 'senha': 'J5VEYT7',
 'validade_senha': None,
 'observacoes_opme': 'OPMEs AUTORIZADOS CONFORME SOLICITAÇÃO MÉDICA',
 'observacoes_gerais': 'DN: ; DC: ; DA: ; I: ; P: ; GR: ; A: ; UTI: N; RV: N; OBS: Solicitacao de autorizacao -',
 'profissional_solicitante': 'MATEUS ALVES BORGES CRISTINO'}

In [13]:
type(results)

dict

In [14]:
import re

results["codigo_autorizado"] = re.sub(r'[^a-zA-Z0-9]', '', results["codigo_autorizado"])
results["senha"] = re.sub(r'[^a-zA-Z0-9]', '', results["senha"])
results

{'procedimento_autorizado': 'VARIZES - TRATAMENTO CIRURGICO DE DOIS MEMBROS',
 'paciente': 'BARBARA ARAUJO SCHNNEPPEL CORREA',
 'codigo_autorizado': '309071361',
 'senha': 'J5VEYT7',
 'validade_senha': None,
 'observacoes_opme': 'OPMEs AUTORIZADOS CONFORME SOLICITAÇÃO MÉDICA',
 'observacoes_gerais': 'DN: ; DC: ; DA: ; I: ; P: ; GR: ; A: ; UTI: N; RV: N; OBS: Solicitacao de autorizacao -',
 'profissional_solicitante': 'MATEUS ALVES BORGES CRISTINO'}

In [15]:
results["senha"] == "J5VEYT7"

True

# part 2.5 
build a pipeline for evaluation

PS: what fields to evaluate?

In [16]:
# Step 1: Create subset of first 5 examples
eval_df = merged_df_autorizacao_final[:5].copy()
print(f"Created evaluation dataset with {len(eval_df)} rows")

# Initialize new columns for LLM results
llm_columns = [
    'procedimento_autorizado_llm',
    'paciente_llm', 
    'codigo_autorizado_llm',
    'senha_llm',
    'validade_senha_llm',
    'observacoes_opme_llm',
    'observacoes_gerais_llm',
    'usuario_finalizador_llm'
]

for col in llm_columns:
    eval_df[col] = None

print("Initialized LLM result columns")
eval_df.head()

Created evaluation dataset with 5 rows
Initialized LLM result columns

,CD_AVISO_CIRURGIA,DS_PROCEDIMENTO,CD_GUIA,CD_SENHA,DS_GUIA_PATH,DS_CONTATO,DS_PDF_BYTES,DS_GUIA_PATH_CLICKABLE,procedimento_autorizado_llm,paciente_llm,codigo_autorizado_llm,senha_llm,validade_senha_llm,observacoes_opme_llm,observacoes_gerais_llm,usuario_finalizador_llm
0,857416,"[{""code"":30101557,""description"":""EXCISAO E ROT...",19494856.0,None,https://cdns.overmind.ai/autorizacao-cemig-000...,\n Procedimento Autorizado\n Pacient...,b'%PDF-1.3\n%\xb7\xbe\xad\xaa\n1 0 obj\n<<\n/T...,"<a href=""https://cdns.overmind.ai/autorizacao-...",None,None,None,None,None,None,None,None
1,857469,"[{""code"":30907136,""description"":""VARIZES - TRA...",19495507.0,J5VEYT7,https://cdns.overmind.ai/autorizacao-bradesco-...,\n Procedimento Autorizado\n Pacient...,b'%PDF-1.4\n%\xe2\xe3\xcf\xd3\n4 0 obj\n<</Len...,"<a href=""https://cdns.overmind.ai/autorizacao-...",None,None,None,None,None,None,None,None
2,857883,"[{""code"":30205050,""description"":""AMIGDALECTOMI...",19506292.0,J5VEW29,https://cdns.overmind.ai/autorizacao-bradesco-...,\n Procedimento Autorizado\n Pacient...,b'%PDF-1.4\n%\xe2\xe3\xcf\xd3\n4 0 obj\n<</Len...,"<a href=""https://cdns.overmind.ai/autorizacao-...",None,None,None,None,None,None,None,None
3,858036,"[{""code"":30205247,""description"":""UVULOPALATO-F...",19508906.0,J5VEWF9,https://cdns.overmind.ai/autorizacao-bradesco-...,\n Procedimento Parcialmente autorizado\n...,b'%PDF-1.4\n%\xe2\xe3\xcf\xd3\n4 0 obj\n<</Len...,"<a href=""https://cdns.overmind.ai/autorizacao-...",None,None,None,None,None,None,None,None
4,859112,"[{""code"":30501350,""description"":""RINOSSEPTOPLA...",19537543.0,5045663575,https://cdns.overmind.ai/autorizacao-sulameric...,\n Procedimento Autorizado\n Pacient...,b'%PDF-1.4\n%\xf6\xe4\xfc\xdf\n1 0 obj\n<<\n/T...,"<a href=""https://cdns.overmind.ai/autorizacao-...",None,None,None,None,None,None,None,None

In [17]:
# Step 2 & 3: Process each row through the pipeline
import re
from tqdm import tqdm

def process_single_row(row_index, pdf_bytes):
    """Process a single row through the PDF->Text->LLM pipeline"""
    try:
        # Convert PDF bytes to text using unstructured
        pdf_file_like = io.BytesIO(pdf_bytes)
        elements = partition_pdf(file=pdf_file_like, languages=["portuguese"])
        full_text = "\n".join([el.text for el in elements if el.text])
        
        # Send to LLM
        results = llm_instance.invoke_model(input_str=full_text)
        
        # Clean special characters from specific fields
        if 'codigo_autorizado' in results:
            results["codigo_autorizado"] = re.sub(r'[^a-zA-Z0-9]', '', results["codigo_autorizado"])
        if 'senha' in results:
            results["senha"] = re.sub(r'[^a-zA-Z0-9]', '', results["senha"])
            
        return results
        
    except Exception as e:
        print(f"Error processing row {row_index}: {e}")
        return {col.replace('_llm', ''): None for col in llm_columns}

# Process each row
for idx, row in tqdm(eval_df.iterrows(), total=len(eval_df), desc="Processing PDFs"):
    pdf_bytes = row['DS_PDF_BYTES']
    
    # Skip if no PDF bytes available
    if pd.isna(pdf_bytes):
        print(f"Skipping row {idx}: No PDF bytes available")
        continue
        
    # Process the row
    llm_results = process_single_row(idx, pdf_bytes)
    
    # Add results to dataframe
    for field_name, value in llm_results.items():
        col_name = f"{field_name}_llm"
        if col_name in eval_df.columns:
            eval_df.at[idx, col_name] = value
    
    print(f"Completed row {idx} - CD_AVISO_CIRURGIA: {row['CD_AVISO_CIRURGIA']}")

print("Pipeline processing completed!")
eval_df[['CD_AVISO_CIRURGIA'] + llm_columns].head()

Processing PDFs:  20%|██        | 1/5 [00:16<01:05, 16.38s/it]

Completed row 0 - CD_AVISO_CIRURGIA: 857416

Processing PDFs:  40%|████      | 2/5 [00:27<00:39, 13.27s/it]

Completed row 1 - CD_AVISO_CIRURGIA: 857469

Processing PDFs:  60%|██████    | 3/5 [00:42<00:27, 13.85s/it]

Completed row 2 - CD_AVISO_CIRURGIA: 857883

Processing PDFs:  80%|████████  | 4/5 [00:59<00:15, 15.16s/it]

Completed row 3 - CD_AVISO_CIRURGIA: 858036

Processing PDFs: 100%|██████████| 5/5 [01:13<00:00, 14.63s/it]

Completed row 4 - CD_AVISO_CIRURGIA: 859112
Pipeline processing completed!

,CD_AVISO_CIRURGIA,procedimento_autorizado_llm,paciente_llm,codigo_autorizado_llm,senha_llm,validade_senha_llm,observacoes_opme_llm,observacoes_gerais_llm,usuario_finalizador_llm
0,857416,"EXTENSOS FERIMENTOS, CICATRIZES OU TUMORES - E...",SALETE EMILIA DOS SANTOS LIMA,301015571,000120250700053801,10/08/25,Pedido sem OPME,Solicitacao de autorizacao,None
1,857469,VARIZES - TRATAMENTO CIRURGICO DE DOIS MEMBROS,BARBARA ARAUJO SCHNNEPPEL CORREA,309071361,J5VEYT7,None,OPMEs AUTORIZADOS CONFORME SOLICITAÇÃO MÉDICA,DN: ; DC: ; DA: ; I: ; P: ; GR: ; A: ; UTI: N;...,None
2,857883,AMIGDALECTOMIA DAS PALATINAS,MILENA RAFAELA TRINDADE,302050501,J5VEW29,25/07/2025,Pedido sem OPME,DN: ; DC: ; DA: ; I: ; P: ; GR: ; A: ; UTI: N;...,None
3,858036,AMIGDALECTOMIA DAS PALATINAS,DIONE RAIMUNDO CARVALHO PINTO,30205050Qtde1,J5VEWF9,29/07/2025,Pedido sem OPME,DN: ; DC: ; DA: ; I: ; P: ; GR: ; A: ; UTI: N;...,None
4,859112,SEPTOPLASTIA TURBINECTOMIA,LEANDRO S ROSA,65300114Qt01,5045663575,19/08/2025,Pedido sem OPME,None,None

### expanding the eval dataframe so we can get the field DS_CONTATO values into new cols

In [18]:
# Extract ground truth fields from DS_CONTATO
import re

def extract_ds_contato_fields(ds_contato_text):
    """Extract structured fields from DS_CONTATO text using regex patterns"""
    if pd.isna(ds_contato_text):
        return {field + '_gt': None for field in ['paciente', 'codigo_autorizado', 'senha', 'validade_senha', 'observacoes_opme', 'observacoes_gerais', 'usuario_finalizador']}
    
    extracted = {}
    
    # Extract Paciente
    paciente_match = re.search(r'Paciente:\s*(.+?)(?=\n|CÓDIGO)', ds_contato_text, re.IGNORECASE)
    extracted['paciente_gt'] = paciente_match.group(1).strip() if paciente_match else None
    
    # Extract CÓDIGO AUTORIZADO
    codigo_match = re.search(r'CÓDIGO AUTORIZADO:\s*(.+?)(?=\n\n|SENHA)', ds_contato_text, re.DOTALL | re.IGNORECASE)
    extracted['codigo_autorizado_gt'] = codigo_match.group(1).strip() if codigo_match else None
    
    # Extract SENHA
    senha_match = re.search(r'SENHA:\s*(.+?)(?=\n|VALIDADE)', ds_contato_text, re.IGNORECASE)
    extracted['senha_gt'] = senha_match.group(1).strip() if senha_match else None
    
    # Extract VALIDADE DA SENHA
    validade_match = re.search(r'VALIDADE DA SENHA:\s*(.+?)(?=\n|OBSERVAÇÕES)', ds_contato_text, re.IGNORECASE)
    extracted['validade_senha_gt'] = validade_match.group(1).strip() if validade_match else None
    
    # Extract OBSERVAÇÕES OPME
    opme_match = re.search(r'OBSERVAÇÕES OPME:\s*(.+?)(?=\n|OBSERVAÇÕES GERAIS)', ds_contato_text, re.IGNORECASE)
    extracted['observacoes_opme_gt'] = opme_match.group(1).strip() if opme_match else None
    
    # Extract OBSERVAÇÕES GERAIS
    gerais_match = re.search(r'OBSERVAÇÕES GERAIS:\s*(.+?)(?=\n|NOME USUÁRIO)', ds_contato_text, re.IGNORECASE)
    extracted['observacoes_gerais_gt'] = gerais_match.group(1).strip() if gerais_match else None
    
    # Extract NOME USUÁRIO FINALIZOU O PEDIDO
    usuario_match = re.search(r'NOME USUÁRIO FINALIZOU O PEDIDO:\s*(.+?)(?=\n|$)', ds_contato_text, re.IGNORECASE)
    extracted['usuario_finalizador_gt'] = usuario_match.group(1).strip() if usuario_match else None
    
    return extracted

# Apply extraction to all rows in eval_df
gt_columns = ['paciente_gt', 'codigo_autorizado_gt', 'senha_gt', 'validade_senha_gt', 'observacoes_opme_gt', 'observacoes_gerais_gt', 'usuario_finalizador_gt']

# Initialize ground truth columns
for col in gt_columns:
    eval_df[col] = None

# Extract fields for each row
for idx, row in eval_df.iterrows():
    extracted_fields = extract_ds_contato_fields(row['DS_CONTATO'])
    for field_name, value in extracted_fields.items():
        eval_df.at[idx, field_name] = value

print("Ground truth extraction completed!")
print("\nSample of extracted fields:")
eval_df[['CD_AVISO_CIRURGIA'] + gt_columns].head()

Ground truth extraction completed!

Sample of extracted fields:

,CD_AVISO_CIRURGIA,paciente_gt,codigo_autorizado_gt,senha_gt,validade_senha_gt,observacoes_opme_gt,observacoes_gerais_gt,usuario_finalizador_gt
0,857416,SALETE EMILIA DOS SANTOS LIMA,"01009001 x 1\n,30101557 x 1",000120250700053801,10/08/2025,Pedido sem OPME,None,Deisiane
1,857469,BARBARA ARAUJO SCHNNEPPEL CORREA,"01009001 x 1\n,30907136 x 1",J5VEYT7,07/01/2026,Pedido sem OPME,Diária: 01,TELMA
2,857883,MILENA RAFAELA TRINDADE,"01009001 x 1\n,30205050 x 1\n,30205271 x 1\n,3...",J5VEW29,07/01/2026,Pedido sem OPME,None,ANA
3,858036,DIONE RAIMUNDO CARVALHO PINTO,"30502349 x 0\n,30205247 x 1\n,30501369 x 1\n,3...",J5VEWF9,06/01/2026,Pedido sem OPME,None,BRUNA FERNANDA
4,859112,LEANDRO SALOMAO ROSA,"01009001 x 1\n,30501350 x 1\n,30501458 x 2",5045663575,19/08/2025,Pedido sem OPME,Diária: 01,TELMA

In [19]:
eval_df.head()

,CD_AVISO_CIRURGIA,DS_PROCEDIMENTO,CD_GUIA,CD_SENHA,DS_GUIA_PATH,DS_CONTATO,DS_PDF_BYTES,DS_GUIA_PATH_CLICKABLE,procedimento_autorizado_llm,paciente_llm,codigo_autorizado_llm,senha_llm,validade_senha_llm,observacoes_opme_llm,observacoes_gerais_llm,usuario_finalizador_llm,paciente_gt,codigo_autorizado_gt,senha_gt,validade_senha_gt,observacoes_opme_gt,observacoes_gerais_gt,usuario_finalizador_gt
0,857416,"[{""code"":30101557,""description"":""EXCISAO E ROT...",19494856.0,None,https://cdns.overmind.ai/autorizacao-cemig-000...,\n Procedimento Autorizado\n Pacient...,b'%PDF-1.3\n%\xb7\xbe\xad\xaa\n1 0 obj\n<<\n/T...,"<a href=""https://cdns.overmind.ai/autorizacao-...","EXTENSOS FERIMENTOS, CICATRIZES OU TUMORES - E...",SALETE EMILIA DOS SANTOS LIMA,301015571,000120250700053801,10/08/25,Pedido sem OPME,Solicitacao de autorizacao,None,SALETE EMILIA DOS SANTOS LIMA,"01009001 x 1\n,30101557 x 1",000120250700053801,10/08/2025,Pedido sem OPME,None,Deisiane
1,857469,"[{""code"":30907136,""description"":""VARIZES - TRA...",19495507.0,J5VEYT7,https://cdns.overmind.ai/autorizacao-bradesco-...,\n Procedimento Autorizado\n Pacient...,b'%PDF-1.4\n%\xe2\xe3\xcf\xd3\n4 0 obj\n<</Len...,"<a href=""https://cdns.overmind.ai/autorizacao-...",VARIZES - TRATAMENTO CIRURGICO DE DOIS MEMBROS,BARBARA ARAUJO SCHNNEPPEL CORREA,309071361,J5VEYT7,None,OPMEs AUTORIZADOS CONFORME SOLICITAÇÃO MÉDICA,DN: ; DC: ; DA: ; I: ; P: ; GR: ; A: ; UTI: N;...,None,BARBARA ARAUJO SCHNNEPPEL CORREA,"01009001 x 1\n,30907136 x 1",J5VEYT7,07/01/2026,Pedido sem OPME,Diária: 01,TELMA
2,857883,"[{""code"":30205050,""description"":""AMIGDALECTOMI...",19506292.0,J5VEW29,https://cdns.overmind.ai/autorizacao-bradesco-...,\n Procedimento Autorizado\n Pacient...,b'%PDF-1.4\n%\xe2\xe3\xcf\xd3\n4 0 obj\n<</Len...,"<a href=""https://cdns.overmind.ai/autorizacao-...",AMIGDALECTOMIA DAS PALATINAS,MILENA RAFAELA TRINDADE,302050501,J5VEW29,25/07/2025,Pedido sem OPME,DN: ; DC: ; DA: ; I: ; P: ; GR: ; A: ; UTI: N;...,None,MILENA RAFAELA TRINDADE,"01009001 x 1\n,30205050 x 1\n,30205271 x 1\n,3...",J5VEW29,07/01/2026,Pedido sem OPME,None,ANA
3,858036,"[{""code"":30205247,""description"":""UVULOPALATO-F...",19508906.0,J5VEWF9,https://cdns.overmind.ai/autorizacao-bradesco-...,\n Procedimento Parcialmente autorizado\n...,b'%PDF-1.4\n%\xe2\xe3\xcf\xd3\n4 0 obj\n<</Len...,"<a href=""https://cdns.overmind.ai/autorizacao-...",AMIGDALECTOMIA DAS PALATINAS,DIONE RAIMUNDO CARVALHO PINTO,30205050Qtde1,J5VEWF9,29/07/2025,Pedido sem OPME,DN: ; DC: ; DA: ; I: ; P: ; GR: ; A: ; UTI: N;...,None,DIONE RAIMUNDO CARVALHO PINTO,"30502349 x 0\n,30205247 x 1\n,30501369 x 1\n,3...",J5VEWF9,06/01/2026,Pedido sem OPME,None,BRUNA FERNANDA
4,859112,"[{""code"":30501350,""description"":""RINOSSEPTOPLA...",19537543.0,5045663575,https://cdns.overmind.ai/autorizacao-sulameric...,\n Procedimento Autorizado\n Pacient...,b'%PDF-1.4\n%\xf6\xe4\xfc\xdf\n1 0 obj\n<<\n/T...,"<a href=""https://cdns.overmind.ai/autorizacao-...",SEPTOPLASTIA TURBINECTOMIA,LEANDRO S ROSA,65300114Qt01,5045663575,19/08/2025,Pedido sem OPME,None,None,LEANDRO SALOMAO ROSA,"01009001 x 1\n,30501350 x 1\n,30501458 x 2",5045663575,19/08/2025,Pedido sem OPME,Diária: 01,TELMA

In [20]:
"000120250700053801" ==  "000120250700053801"

True

# Part 3 - processing with textract

final df should be textract_eval_df

In [21]:
# trying to use the mudular code to get the workflow feeling
import sys

# add app to path so we dont get the error ModuleNotFoundError: No module named 'app'
from pathlib import Path
sys.path.append(str(Path.cwd().parent))
from app.utils.process_images import process_blobs
from app.utils.textract_service import TextractKVExtractor, extract_text_single_id
from app.utils.llm_service import AnthropicLLMService
from app.utils.aws_services_handler import create_boto3_client
from app.utils.config import load_config, AppConstants
from app.utils.logger import get_logger
from app.utils.system_prompts.autorizacao_prompt import Prompts


logger = get_logger(name=__name__)
config_vars = load_config()

In [36]:
# load merged df
import sqlalchemy

# Create a database connection
engine = sqlalchemy.create_engine("sqlite:///merged_autorizacao.sqlite")


# Save the DataFrame to a SQLite table
merged_df_autorizacao_final = pd.read_sql("SELECT * FROM merged_aut", engine)

In [23]:
app_constants = AppConstants()
texttract_client = create_boto3_client("textract", config_vars)
bedrock_client = create_boto3_client("bedrock-runtime", config_vars)
autorizacao_prompt = Prompts.autorizacao_extraction_prompt

texttract_instance = TextractKVExtractor(texttract_client)
llm_instance = AnthropicLLMService(
    model_id=app_constants.BEDROCK_DEFAULT_MODEL_ID,
    model_version=app_constants.BEDROCK_DEFAULT_MODEL_VERSION,
    client=bedrock_client,
    system_prompt=autorizacao_prompt,
    max_tokens=app_constants.MAX_TOKENS,
    temperature=app_constants.TEMPERATURE,
    budget_tokens=app_constants.BUDGET_TOKENS
)

{"timestamp": "2025-08-20T12:30:13", "level": "INFO", "name": "app.utils.aws_services_handler", "message": "Criando cliente TEXTRACT para a região: us-east-1...", "filename": "aws_services_handler.py", "lineno": 17}
{"timestamp": "2025-08-20T12:30:13", "level": "INFO", "name": "app.utils.aws_services_handler", "message": "Cliente TEXTRACT criado com sucesso.", "filename": "aws_services_handler.py", "lineno": 26}
{"timestamp": "2025-08-20T12:30:13", "level": "INFO", "name": "app.utils.aws_services_handler", "message": "Criando cliente BEDROCK-RUNTIME para a região: us-east-1...", "filename": "aws_services_handler.py", "lineno": 17}
{"timestamp": "2025-08-20T12:30:13", "level": "INFO", "name": "app.utils.aws_services_handler", "message": "Cliente BEDROCK-RUNTIME criado com sucesso.", "filename": "aws_services_handler.py", "lineno": 26}

In [25]:
# GETTING ids and blobs dict  like ids_and_blobs = {id: blob,id2: blob} from cd aviso and lo docuemnto anexo from df
def get_ids_and_blobs(df: pd.DataFrame) -> dict:
    ids_and_blobs = {}
    for index, row in df.iterrows():
        ids_and_blobs[row['CD_AVISO_CIRURGIA']] = row['DS_PDF_BYTES']
    return ids_and_blobs

ids_and_blobs = get_ids_and_blobs(merged_df_autorizacao_final)

In [26]:
# PROCESSING CUSTOM D=DICT WITH IDS AND BLOBS
byte_png_images_and_ids = process_blobs(ids_and_blobs, img_enhancement=False, MAX_IMAGES_PER_BLOB=20)
logger.info(f"Processed {len(byte_png_images_and_ids)} byte PNG images.")

{"timestamp": "2025-08-20T12:30:17", "level": "INFO", "name": "app.utils.process_images", "message": "Converting BLOB 857416 to images...", "filename": "process_images.py", "lineno": 70}
{"timestamp": "2025-08-20T12:30:17", "level": "INFO", "name": "app.utils.process_images", "message": "Processando PDF com 1 página(s)...", "filename": "process_images.py", "lineno": 23}

{"timestamp": "2025-08-20T12:30:18", "level": "INFO", "name": "app.utils.process_images", "message": "✅ Converted image from BLOB 857416 to png bytes.", "filename": "process_images.py", "lineno": 80}
{"timestamp": "2025-08-20T12:30:18", "level": "INFO", "name": "app.utils.process_images", "message": "Converting BLOB 857469 to images...", "filename": "process_images.py", "lineno": 70}
{"timestamp": "2025-08-20T12:30:18", "level": "INFO", "name": "app.utils.process_images", "message": "Processando PDF com 1 página(s)...", "filename": "process_images.py", "lineno": 23}
{"timestamp": "2025-08-20T12:30:18", "level": "INFO", "name": "app.utils.process_images", "message": "✅ Converted image from BLOB 857469 to png bytes.", "filename": "process_images.py", "lineno": 80}
{"timestamp": "2025-08-20T12:30:18", "level": "INFO", "name": "app.utils.process_images", "message": "Converting BLOB 857883 to images...", "filename": "process_images.py", "lineno": 70}
{"timestamp": "2025-08-20T12:30:18", "level": "INFO", "name": "app.utils.process_images", "message": "Processando PDF com 2 página(s)...", "filename": "process_images.py", "lineno": 23}
{"timestamp": "2025-08-20T12:30:18", "level": "INFO", "name": "app.utils.process_images", "message": "✅ Converted image from BLOB 857883 to png bytes.", "filename": "process_images.py", "lineno": 80}
{"timestamp": "2025-08-20T12:30:18", "level": "INFO", "name": "app.utils.process_images", "message": "Converting BLOB 858036 to images...", "filename": "process_images.py", "lineno": 70}
{"timestamp": "2025-08-20T12:30:18", "level": "INFO", "name": "app.utils.process_images", "message": "Processando PDF com 2 página(s)...", "filename": "process_images.py", "lineno": 23}
{"timestamp": "2025-08-20T12:30:19", "level": "INFO", "name": "app.utils.process_images", "message": "✅ Converted image from BLOB 858036 to png bytes.", "filename": "process_images.py", "lineno": 80}
{"timestamp": "2025-08-20T12:30:19", "level": "INFO", "name": "app.utils.process_images", "message": "Converting BLOB 859112 to images...", "filename": "process_images.py", "lineno": 70}
{"timestamp": "2025-08-20T12:30:19", "level": "INFO", "name": "app.utils.process_images", "message": "Processando PDF com 2 página(s)...", "filename": "process_images.py", "lineno": 23}
{"timestamp": "2025-08-20T12:30:19", "level": "INFO", "name": "app.utils.process_images", "message": "✅ Converted image from BLOB 859112 to png bytes.", "filename": "process_images.py", "lineno": 80}
{"timestamp": "2025-08-20T12:30:19", "level": "INFO", "name": "app.utils.process_images", "message": "Converting BLOB 859185 to images...", "filename": "process_images.py", "lineno": 70}
{"timestamp": "2025-08-20T12:30:19", "level": "INFO", "name": "app.utils.process_images", "message": "Processando PDF com 4 página(s)...", "filename": "process_images.py", "lineno": 23}
{"timestamp": "2025-08-20T12:30:20", "level": "INFO", "name": "app.utils.process_images", "message": "✅ Converted image from BLOB 859185 to png bytes.", "filename": "process_images.py", "lineno": 80}
{"timestamp": "2025-08-20T12:30:20", "level": "INFO", "name": "app.utils.process_images", "message": "Converting BLOB 859989 to images...", "filename": "process_images.py", "lineno": 70}
{"timestamp": "2025-08-20T12:30:20", "level": "INFO", "name": "app.utils.process_images", "message": "Processando PDF com 2 página(s)...", "filename": "process_images.py", "lineno": 23}
{"timestamp": "2025-08-20T12:30:20", "level": "INFO", "name": "app.utils.process_images", "message": "✅ Converted image from BLOB 859989 to png bytes.", "filename": "process_images.py", "lineno": 80}
{"timestamp": "2025-08-20T12:30:20", "level": "INFO", "name": "app.utils.process_images", "message": "Converting BLOB 861063 to images...", "filename": "process_images.py", "lineno": 70}
{"timestamp": "2025-08-20T12:30:20", "level": "INFO", "name": "app.utils.process_images", "message": "Processando PDF com 1 página(s)...", "filename": "process_images.py", "lineno": 23}
{"timestamp": "2025-08-20T12:30:21", "level": "INFO", "name": "app.utils.process_images", "message": "✅ Converted image from BLOB 861063 to png bytes.", "filename": "process_images.py", "lineno": 80}
{"timestamp": "2025-08-20T12:30:21", "level": "INFO", "name": "app.utils.process_images", "message": "Converting BLOB 861179 to images...", "filename": "process_images.py", "lineno": 70}
{"timestamp": "2025-08-20T12:30:21", "level": "INFO", "name": "app.utils.process_images", "message": "Processando PDF com 1 página(s)...", "filename": "process_images.py", "lineno": 23}
{"timestamp": "2025-08-20T12:30:21", "level": "INFO", "name": "app.utils.process_images", "message": "✅ Converted image from BLOB 861179 to png bytes.", "filename": "process_images.py", "lineno": 80}
{"timestamp": "2025-08-20T12:30:21", "level": "INFO", "name": "app.utils.process_images", "message": "Converting BLOB 861465 to images...", "filename": "process_images.py", "lineno": 70}
{"timestamp": "2025-08-20T12:30:21", "level": "INFO", "name": "app.utils.process_images", "message": "Processando PDF com 2 página(s)...", "filename": "process_images.py", "lineno": 23}
{"timestamp": "2025-08-20T12:30:21", "level": "INFO", "name": "app.utils.process_images", "message": "✅ Converted image from BLOB 861465 to png bytes.", "filename": "process_images.py", "lineno": 80}
{"timestamp": "2025-08-20T12:30:21", "level": "INFO", "name": "app.utils.process_images", "message": "Converting BLOB 861565 to images...", "filename": "process_images.py", "lineno": 70}
{"timestamp": "2025-08-20T12:30:21", "level": "INFO", "name": "app.utils.process_images", "message": "Processando PDF com 1 página(s)...", "filename": "process_images.py", "lineno": 23}
{"timestamp": "2025-08-20T12:30:21", "level": "INFO", "name": "app.utils.process_images", "message": "✅ Converted image from BLOB 861565 to png bytes.", "filename": "process_images.py", "lineno": 80}
{"timestamp": "2025-08-20T12:30:21", "level": "INFO", "name": "app.utils.process_images", "message": "Converting BLOB 862378 to images...", "filename": "process_images.py", "lineno": 70}
{"timestamp": "2025-08-20T12:30:21", "level": "INFO", "name": "app.utils.process_images", "message": "Processando PDF com 2 página(s)...", "filename": "process_images.py", "lineno": 23}
{"timestamp": "2025-08-20T12:30:22", "level": "INFO", "name": "app.utils.process_images", "message": "✅ Converted image from BLOB 862378 to png bytes.", "filename": "process_images.py", "lineno": 80}
{"timestamp": "2025-08-20T12:30:22", "level": "INFO", "name": "app.utils.process_images", "message": "Converting BLOB 862459 to images...", "filename": "process_images.py", "lineno": 70}
{"timestamp": "2025-08-20T12:30:22", "level": "INFO", "name": "app.utils.process_images", "message": "Processando PDF com 1 página(s)...", "filename": "process_images.py", "lineno": 23}
{"timestamp": "2025-08-20T12:30:22", "level": "INFO", "name": "app.utils.process_images", "message": "✅ Converted image from BLOB 862459 to png bytes.", "filename": "process_images.py", "lineno": 80}
{"timestamp": "2025-08-20T12:30:22", "level": "INFO", "name": "app.utils.process_images", "message": "Converting BLOB 863441 to images...", "filename": "process_images.py", "lineno": 70}
{"timestamp": "2025-08-20T12:30:22", "level": "INFO", "name": "app.utils.process_images", "message": "Processando PDF com 1 página(s)...", "filename": "process_images.py", "lineno": 23}
{"timestamp": "2025-08-20T12:30:22", "level": "INFO", "name": "app.utils.process_images", "message": "✅ Converted image from BLOB 863441 to png bytes.", "filename": "process_images.py", "lineno": 80}
{"timestamp": "2025-08-20T12:30:22", "level": "INFO", "name": "app.utils.process_images", "message": "Converting BLOB 863507 to images...", "filename": "process_images.py", "lineno": 70}
{"timestamp": "2025-08-20T12:30:22", "level": "INFO", "name": "app.utils.process_images", "message": "Processando PDF com 1 página(s)...", "filename": "process_images.py", "lineno": 23}
{"timestamp": "2025-08-20T12:30:22", "level": "INFO", "name": "app.utils.process_images", "message": "✅ Converted image from BLOB 863507 to png bytes.", "filename": "process_images.py", "lineno": 80}
{"timestamp": "2025-08-20T12:30:22", "level": "INFO", "name": "app.utils.process_images", "message": "Converting BLOB 863609 to images...", "filename": "process_images.py", "lineno": 70}
{"timestamp": "2025-08-20T12:30:22", "level": "INFO", "name": "app.utils.process_images", "message": "Processando PDF com 1 página(s)...", "filename": "process_images.py", "lineno": 23}
{"timestamp": "2025-08-20T12:30:23", "level": "INFO", "name": "app.utils.process_images", "message": "✅ Converted image from BLOB 863609 to png bytes.", "filename": "process_images.py", "lineno": 80}
{"timestamp": "2025-08-20T12:30:23", "level": "INFO", "name": "app.utils.process_images", "message": "Converting BLOB 863611 to images...", "filename": "process_images.py", "lineno": 70}
{"timestamp": "2025-08-20T12:30:23", "level": "INFO", "name": "app.utils.process_images", "message": "Processando PDF com 1 página(s)...", "filename": "process_images.py", "lineno": 23}
{"timestamp": "2025-08-20T12:30:23", "level": "INFO", "name": "app.utils.process_images", "message": "✅ Converted image from BLOB 863611 to png bytes.", "filename": "process_images.py", "lineno": 80}
{"timestamp": "2025-08-20T12:30:23", "level": "INFO", "name": "app.utils.process_images", "message": "Converting BLOB 863647 to images...", "filename": "process_images.py", "lineno": 70}
{"timestamp": "2025-08-20T12:30:23", "level": "INFO", "name": "app.utils.process_images", "message": "Processando PDF com 4 página(s)...", "filename": "process_images.py", "lineno": 23}
{"timestamp": "2025-08-20T12:30:24", "level": "INFO", "name": "app.utils.process_images", "message": "✅ Converted image from BLOB 863647 to png bytes.", "filename": "process_images.py", "lineno": 80}
{"timestamp": "2025-08-20T12:30:24", "level": "INFO", "name": "app.utils.process_images", "message": "Converting BLOB 863657 to images...", "filename": "process_images.py", "lineno": 70}
{"timestamp": "2025-08-20T12:30:24", "level": "INFO", "name": "app.utils.process_images", "message": "Processando PDF com 1 página(s)...", "filename": "process_images.py", "lineno": 23}
{"timestamp": "2025-08-20T12:30:24", "level": "INFO", "name": "app.utils.process_images", "message": "✅ Converted image from BLOB 863657 to png bytes.", "filename": "process_images.py", "lineno": 80}
{"timestamp": "2025-08-20T12:30:24", "level": "INFO", "name": "app.utils.process_images", "message": "Converting BLOB 863659 to images...", "filename": "process_images.py", "lineno": 70}
{"timestamp": "2025-08-20T12:30:24", "level": "INFO", "name": "app.utils.process_images", "message": "Processando PDF com 1 página(s)...", "filename": "process_images.py", "lineno": 23}
{"timestamp": "2025-08-20T12:30:24", "level": "INFO", "name": "app.utils.process_images", "message": "✅ Converted image from BLOB 863659 to png bytes.", "filename": "process_images.py", "lineno": 80}
{"timestamp": "2025-08-20T12:30:24", "level": "INFO", "name": "app.utils.process_images", "message": "Converting BLOB 863782 to images...", "filename": "process_images.py", "lineno": 70}
{"timestamp": "2025-08-20T12:30:24", "level": "INFO", "name": "app.utils.process_images", "message": "Processando PDF com 1 página(s)...", "filename": "process_images.py", "lineno": 23}
{"timestamp": "2025-08-20T12:30:24", "level": "INFO", "name": "app.utils.process_images", "message": "✅ Converted image from BLOB 863782 to png bytes.", "filename": "process_images.py", "lineno": 80}
{"timestamp": "2025-08-20T12:30:24", "level": "INFO", "name": "app.utils.process_images", "message": "Converting BLOB 863808 to images...", "filename": "process_images.py", "lineno": 70}
{"timestamp": "2025-08-20T12:30:24", "level": "INFO", "name": "app.utils.process_images", "message": "Processando PDF com 1 página(s)...", "filename": "process_images.py", "lineno": 23}
{"timestamp": "2025-08-20T12:30:25", "level": "INFO", "name": "app.utils.process_images", "message": "✅ Converted image from BLOB 863808 to png bytes.", "filename": "process_images.py", "lineno": 80}
{"timestamp": "2025-08-20T12:30:25", "level": "INFO", "name": "app.utils.process_images", "message": "Converting BLOB 863815 to images...", "filename": "process_images.py", "lineno": 70}
{"timestamp": "2025-08-20T12:30:25", "level": "INFO", "name": "app.utils.process_images", "message": "Processando PDF com 1 página(s)...", "filename": "process_images.py", "lineno": 23}
{"timestamp": "2025-08-20T12:30:25", "level": "INFO", "name": "app.utils.process_images", "message": "✅ Converted image from BLOB 863815 to png bytes.", "filename": "process_images.py", "lineno": 80}
{"timestamp": "2025-08-20T12:30:25", "level": "INFO", "name": "app.utils.process_images", "message": "Converting BLOB 863875 to images...", "filename": "process_images.py", "lineno": 70}
{"timestamp": "2025-08-20T12:30:25", "level": "INFO", "name": "app.utils.process_images", "message": "Processando PDF com 1 página(s)...", "filename": "process_images.py", "lineno": 23}
{"timestamp": "2025-08-20T12:30:25", "level": "INFO", "name": "app.utils.process_images", "message": "✅ Converted image from BLOB 863875 to png bytes.", "filename": "process_images.py", "lineno": 80}
{"timestamp": "2025-08-20T12:30:25", "level": "INFO", "name": "app.utils.process_images", "message": "Converting BLOB 864026 to images...", "filename": "process_images.py", "lineno": 70}
{"timestamp": "2025-08-20T12:30:25", "level": "INFO", "name": "app.utils.process_images", "message": "Processando PDF com 1 página(s)...", "filename": "process_images.py", "lineno": 23}
{"timestamp": "2025-08-20T12:30:25", "level": "INFO", "name": "app.utils.process_images", "message": "✅ Converted image from BLOB 864026 to png bytes.", "filename": "process_images.py", "lineno": 80}
{"timestamp": "2025-08-20T12:30:25", "level": "INFO", "name": "app.utils.process_images", "message": "Converting BLOB 864288 to images...", "filename": "process_images.py", "lineno": 70}
{"timestamp": "2025-08-20T12:30:25", "level": "INFO", "name": "app.utils.process_images", "message": "Processando PDF com 1 página(s)...", "filename": "process_images.py", "lineno": 23}
{"timestamp": "2025-08-20T12:30:25", "level": "INFO", "name": "app.utils.process_images", "message": "✅ Converted image from BLOB 864288 to png bytes.", "filename": "process_images.py", "lineno": 80}
{"timestamp": "2025-08-20T12:30:25", "level": "INFO", "name": "app.utils.process_images", "message": "Converting BLOB 864556 to images...", "filename": "process_images.py", "lineno": 70}
{"timestamp": "2025-08-20T12:30:25", "level": "INFO", "name": "app.utils.process_images", "message": "Processando PDF com 1 página(s)...", "filename": "process_images.py", "lineno": 23}
{"timestamp": "2025-08-20T12:30:26", "level": "INFO", "name": "app.utils.process_images", "message": "✅ Converted image from BLOB 864556 to png bytes.", "filename": "process_images.py", "lineno": 80}
{"timestamp": "2025-08-20T12:30:26", "level": "INFO", "name": "app.utils.process_images", "message": "Converting BLOB 864557 to images...", "filename": "process_images.py", "lineno": 70}
{"timestamp": "2025-08-20T12:30:26", "level": "INFO", "name": "app.utils.process_images", "message": "Processando PDF com 1 página(s)...", "filename": "process_images.py", "lineno": 23}
{"timestamp": "2025-08-20T12:30:26", "level": "INFO", "name": "app.utils.process_images", "message": "✅ Converted image from BLOB 864557 to png bytes.", "filename": "process_images.py", "lineno": 80}
{"timestamp": "2025-08-20T12:30:26", "level": "INFO", "name": "app.utils.process_images", "message": "Converting BLOB 864648 to images...", "filename": "process_images.py", "lineno": 70}
{"timestamp": "2025-08-20T12:30:26", "level": "INFO", "name": "app.utils.process_images", "message": "Processando PDF com 1 página(s)...", "filename": "process_images.py", "lineno": 23}
{"timestamp": "2025-08-20T12:30:26", "level": "INFO", "name": "app.utils.process_images", "message": "✅ Converted image from BLOB 864648 to png bytes.", "filename": "process_images.py", "lineno": 80}
{"timestamp": "2025-08-20T12:30:26", "level": "INFO", "name": "app.utils.process_images", "message": "Converting BLOB 864662 to images...", "filename": "process_images.py", "lineno": 70}
{"timestamp": "2025-08-20T12:30:26", "level": "INFO", "name": "app.utils.process_images", "message": "Processando PDF com 1 página(s)...", "filename": "process_images.py", "lineno": 23}
{"timestamp": "2025-08-20T12:30:26", "level": "INFO", "name": "app.utils.process_images", "message": "✅ Converted image from BLOB 864662 to png bytes.", "filename": "process_images.py", "lineno": 80}
{"timestamp": "2025-08-20T12:30:26", "level": "INFO", "name": "app.utils.process_images", "message": "Converting BLOB 864785 to images...", "filename": "process_images.py", "lineno": 70}
{"timestamp": "2025-08-20T12:30:26", "level": "INFO", "name": "app.utils.process_images", "message": "Processando PDF com 1 página(s)...", "filename": "process_images.py", "lineno": 23}
{"timestamp": "2025-08-20T12:30:26", "level": "INFO", "name": "app.utils.process_images", "message": "✅ Converted image from BLOB 864785 to png bytes.", "filename": "process_images.py", "lineno": 80}
{"timestamp": "2025-08-20T12:30:26", "level": "INFO", "name": "app.utils.process_images", "message": "Converting BLOB 864810 to images...", "filename": "process_images.py", "lineno": 70}
{"timestamp": "2025-08-20T12:30:26", "level": "INFO", "name": "app.utils.process_images", "message": "Processando PDF com 1 página(s)...", "filename": "process_images.py", "lineno": 23}
{"timestamp": "2025-08-20T12:30:27", "level": "INFO", "name": "app.utils.process_images", "message": "✅ Converted image from BLOB 864810 to png bytes.", "filename": "process_images.py", "lineno": 80}
{"timestamp": "2025-08-20T12:30:27", "level": "INFO", "name": "app.utils.process_images", "message": "Converting BLOB 864931 to images...", "filename": "process_images.py", "lineno": 70}
{"timestamp": "2025-08-20T12:30:27", "level": "INFO", "name": "app.utils.process_images", "message": "Processando PDF com 1 página(s)...", "filename": "process_images.py", "lineno": 23}
{"timestamp": "2025-08-20T12:30:27", "level": "INFO", "name": "app.utils.process_images", "message": "✅ Converted image from BLOB 864931 to png bytes.", "filename": "process_images.py", "lineno": 80}
{"timestamp": "2025-08-20T12:30:27", "level": "INFO", "name": "app.utils.process_images", "message": "Converting BLOB 865070 to images...", "filename": "process_images.py", "lineno": 70}
{"timestamp": "2025-08-20T12:30:27", "level": "INFO", "name": "app.utils.process_images", "message": "Processando PDF com 1 página(s)...", "filename": "process_images.py", "lineno": 23}
{"timestamp": "2025-08-20T12:30:27", "level": "INFO", "name": "app.utils.process_images", "message": "✅ Converted image from BLOB 865070 to png bytes.", "filename": "process_images.py", "lineno": 80}
{"timestamp": "2025-08-20T12:30:27", "level": "INFO", "name": "app.utils.process_images", "message": "Converting BLOB 865191 to images...", "filename": "process_images.py", "lineno": 70}
{"timestamp": "2025-08-20T12:30:27", "level": "INFO", "name": "app.utils.process_images", "message": "Processando PDF com 1 página(s)...", "filename": "process_images.py", "lineno": 23}
{"timestamp": "2025-08-20T12:30:27", "level": "INFO", "name": "app.utils.process_images", "message": "✅ Converted image from BLOB 865191 to png bytes.", "filename": "process_images.py", "lineno": 80}
{"timestamp": "2025-08-20T12:30:27", "level": "INFO", "name": "app.utils.process_images", "message": "Converting BLOB 865357 to images...", "filename": "process_images.py", "lineno": 70}

In [27]:
textract_results = {}
llm_results = {}
for id in list(byte_png_images_and_ids.keys())[:3]:
    single_id_full_text = extract_text_single_id(images_bytes_list=byte_png_images_and_ids[id],
                                                 textract_instance=texttract_instance, extract_full_text=False)

    textract_results[id] = single_id_full_text
    llm_response = llm_instance.invoke_model(input_str=single_id_full_text)
    llm_results[id] = llm_response

# save to df
textract_results_df = pd.DataFrame.from_dict(textract_results, orient="index")
textract_results_df.index.name = "CD_AVISO_CIRURGIA"
textract_results_df = textract_results_df.reset_index()

llm_results_df = pd.DataFrame.from_dict(llm_results, orient="index")
llm_results_df.index.name = "CD_AVISO_CIRURGIA"
llm_results_df = llm_results_df.reset_index()

In [28]:

textract_results_df.rename(columns={0: 'full_text'}, inplace=True)

In [29]:

textract_results_df.head()

   CD_AVISO_CIRURGIA                                          full_text
0             857416  defaultdict(<class 'list'>, {'13 Nome do Contr...
1             857469  defaultdict(<class 'list'>, {'8 Validade da Ca...
2             857883  defaultdict(<class 'list'>, {'8 Validade da Ca...

In [30]:
# getting the third value of column full_text 857883
textract_results_df['full_text'].iloc[2]

"defaultdict(<class 'list'>, {'8 Validade da Carteira': [''], '16 Número do Conselho': ['41848'], '14 Nome do Profissional Solicitante': ['AURELIA ALBUQUERQUE MARTINS'], '27 Previsão de uso de Quimioterápico': [''], '20 Nome do Hospital/ Local Solicitado': ['HOSPITAL MATER DEI'], '17 UF': ['MG'], '15 Conselho Profissional': ['CRM'], 'Registro ANS': ['421715'], '25 Qtde. Diárias': ['1'], '9 Atendimento a RN': ['Não'], '3 Número da Guia Atribuído pela Operadora': ['121223228'], '23 Tipo de': ['2'], '7 Número da Carteira': ['954220139734026'], '24 Regime de Internação': ['HOSPITALAR'], '50 Nome Social': [''], '22 Caráter do': ['ELETIVO'], '5 Senha': ['J5VEW29'], '21 Data Sugerida para Internação (Real)': ['12/07/2025'], '19 Código na Operadora / CNPJ': ['426512'], '10 Nome': ['MILENA RAFAELA TRINDADE'], '13 Nome do Contratado': ['HOSPITAL MATER DEI'], '4 Data da Autorização': ['25/07/2025'], '12 Código na Operadora': ['426512'], '26 Previsão de uso de OPME': [''], '6 Data de Validade da Senha': [''], '18 Código CBC': ['292 MEDICO CLINICO'], '33': [''], 'Gerado em:': ['25/07/2025 11:34'], '29 CID 10 Principal': ['30 CID 10 (2) 31 CID 10 (3) 32 CID 10 (4) Indicação de Acidente (acidente ou doença'], 'A: :': ['UTI:'], 'OBS:': ['Solicitacao de autorizacao'], '34': ['Tabela']})defaultdict(<class 'list'>, {'47 Assinatura do Profissional Solicitante': [''], '46 - Data da Solicitação': ['11/07/2025'], '48 Assinatura do Beneficiário ou Responsável': [''], '49 - Assinatura do Responsável pela Autorização': [''], '39 Data Provável da Admissão': ['12/07/2025'], '42 Código na Operadora / CNPJ autorizado': [''], '44 Código CNES': [''], '43 Nome do Hospital / Local Autorizado': [''], '40 Qtde. Diárias Autorizadas': ['1'], '41 Tipo da Acomodação Autorizada': ['ENFERMARIA'], '45 Observação / Justificativa': ['ADM(REDE NACIONAL (0) PL. ADM(REDE NACIONAL (0) - - PL. EMPRESARIAL) MED(CONFORME PROCEDIMENTO PADRONIZADO. SOLICITAÇÃO AUTORI']})"

In [31]:
llm_results_df.head()

,CD_AVISO_CIRURGIA,procedimento_autorizado,paciente,codigo_autorizado,senha,validade_senha,observacoes_opme,observacoes_gerais,profissional_solicitante
0,857416,None,SALETE EMILIA DOS SANTOS LIMA,None,0001.2025.07-00053801,10/08/25,Pedido sem OPME,Solicitacao de autorizacao,KAYO VIEIRA TEODORAK PÊGO
1,857469,VARIZES TRATAMENTO CIRURGICO DE DOIS MEMBROS,BARBARA ARAUJO SCHNNEPPEL CORREA,30907136 - 1,J5VEYT7,None,Pedido sem OPME,None,MATEUS ALVES BORGES CRISTINO
2,857883,None,MILENA RAFAELA TRINDADE,None,J5VEW29,25/07/2025,Pedido sem OPME,ADM(REDE NACIONAL (0) PL. ADM(REDE NACIONAL (0...,AURELIA ALBUQUERQUE MARTINS