# Part 1 - load generated database for complete evaluation

In [5]:
# load textract_eval_df
import sqlalchemy
import pandas as pd

eval_engine = sqlalchemy.create_engine("sqlite:///dbs/textract_eval_database.sqlite")
textract_eval_df = pd.read_sql("SELECT * FROM textract_eval", con=eval_engine)
textract_eval_df.head()

,CD_AVISO_CIRURGIA,DS_PROCEDIMENTO,CD_GUIA,CD_SENHA,DS_GUIA_PATH,DS_CONTATO,DS_PDF_BYTES,paciente_gt,codigo_autorizado_gt,senha_gt,...,observacoes_gerais_gt,usuario_finalizador_gt,procedimento_autorizado_llm,paciente_llm,codigo_autorizado_llm,senha_llm,validade_senha_llm,observacoes_opme_llm,observacoes_gerais_llm,profissional_solicitante_llm
0,857416,"[{""code"":30101557,""description"":""EXCISAO E ROT...",19494856.0,None,https://cdns.overmind.ai/autorizacao-cemig-000...,\n Procedimento Autorizado\n Pacient...,b'%PDF-1.3\n%\xb7\xbe\xad\xaa\n1 0 obj\n<<\n/T...,SALETE EMILIA DOS SANTOS LIMA,"01009001 x 1\n,30101557 x 1",000120250700053801,...,None,Deisiane,"EXTENSOS FERIMENTOS, CICATRIZES OU TUMORES EXE...",SALETE EMILIA DOS SANTOS LIMA,30101557 x 1,000120250700053801,10/08/25,Pedido sem OPME,Solicitacao de autorizacao,KAYO VIEIRA TEODORAK PÊGO
1,857469,"[{""code"":30907136,""description"":""VARIZES - TRA...",19495507.0,J5VEYT7,https://cdns.overmind.ai/autorizacao-bradesco-...,\n Procedimento Autorizado\n Pacient...,b'%PDF-1.4\n%\xe2\xe3\xcf\xd3\n4 0 obj\n<</Len...,BARBARA ARAUJO SCHNNEPPEL CORREA,"01009001 x 1\n,30907136 x 1",J5VEYT7,...,Diária: 01,TELMA,VARIZES TRATAMENTO CIRURGICO DE DOIS MEMBROS,BARBARA ARAUJO SCHNNEPPEL CORREA,30907136 x 1,J5VEYT7,None,Pedido sem OPME,Diária: 1,MATEUS ALVES BORGES CRISTINO
2,857883,"[{""code"":30205050,""description"":""AMIGDALECTOMI...",19506292.0,J5VEW29,https://cdns.overmind.ai/autorizacao-bradesco-...,\n Procedimento Autorizado\n Pacient...,b'%PDF-1.4\n%\xe2\xe3\xcf\xd3\n4 0 obj\n<</Len...,MILENA RAFAELA TRINDADE,"01009001 x 1\n,30205050 x 1\n,30205271 x 1\n,3...",J5VEW29,...,None,ANA,AMIGDALECTOMIA DAS PALATINAS,MILENA RAFAELA TRINDADE,"30205050 x 1, 30205069 x 1, 30205271 x 1, 3050...",J5VEW29,None,Pedido sem OPME,ADM(REDE NACIONAL (0) PL. ADM(REDE NACIONAL (0...,AURELIA ALBUQUERQUE MARTINS
3,858036,"[{""code"":30205247,""description"":""UVULOPALATO-F...",19508906.0,J5VEWF9,https://cdns.overmind.ai/autorizacao-bradesco-...,\n Procedimento Parcialmente autorizado\n...,b'%PDF-1.4\n%\xe2\xe3\xcf\xd3\n4 0 obj\n<</Len...,DIONE RAIMUNDO CARVALHO PINTO,"30502349 x 0\n,30205247 x 1\n,30501369 x 1\n,3...",J5VEWF9,...,None,BRUNA FERNANDA,AMIGDALECTOMIA DAS PALATINAS,DIONE RAIMUNDO CARVALHO PINTO,"30205050 x 1, 30205069 x 1, 30205247 x 1, 3050...",J5VEWF9,None,Pedido sem OPME,ADM(REDE NACIONAL (0) PL. ADM(REDE NACIONAL (0...,LUCAS EDUARDO DE OLIVEIRA
4,859112,"[{""code"":30501350,""description"":""RINOSSEPTOPLA...",19537543.0,5045663575,https://cdns.overmind.ai/autorizacao-sulameric...,\n Procedimento Autorizado\n Pacient...,b'%PDF-1.4\n%\xf6\xe4\xfc\xdf\n1 0 obj\n<<\n/T...,LEANDRO SALOMAO ROSA,"01009001 x 1\n,30501350 x 1\n,30501458 x 2",5045663575,...,Diária: 01,TELMA,SEPTOPLASTIA TURBINECTOMIA,LEANDRO S ROSA,"65300114 x 1, 30501458 x 2, 30501350 x 1",5045663575,19/08/2025,Pedido sem OPME,Diária: 01,None

In [8]:
# Explore the dataset structure
print("Dataset shape:", textract_eval_df.shape)
print("\nColumns:")
for col in textract_eval_df.columns:
    print(f"  {col}")

print("\nSample ground truth vs LLM data:")
sample_row = textract_eval_df.iloc[0]
print(f"CD_AVISO_CIRURGIA: {sample_row['CD_AVISO_CIRURGIA']}")
print(f"Ground truth paciente: {sample_row.get('paciente_gt', 'N/A')}")
print(f"LLM paciente: {sample_row.get('paciente_llm', 'N/A')}")
print(f"Ground truth senha: {sample_row.get('senha_gt', 'N/A')}")
print(f"LLM senha: {sample_row.get('senha_llm', 'N/A')}")
print(f"Ground truth codigo_autorizado: {sample_row.get('codigo_autorizado_gt', 'N/A')}")
print(f"LLM codigo_autorizado: {sample_row.get('codigo_autorizado_llm', 'N/A')}")
print(f"Ground truth validade_senha: {sample_row.get('validade_senha_gt', 'N/A')}")
print(f"LLM validade_senha: {sample_row.get('validade_senha_llm', 'N/A')}")

# Let's also see what data we actually have (check for non-null values)
print(f"\nNon-null counts:")
for field in ['paciente', 'codigo_autorizado', 'senha', 'validade_senha', 'observacoes_opme']:
    gt_col = f"{field}_gt"
    llm_col = f"{field}_llm"
    if gt_col in textract_eval_df.columns:
        gt_count = textract_eval_df[gt_col].notna().sum()
        print(f"  {field}: GT={gt_count}, LLM={textract_eval_df[llm_col].notna().sum()}")

Dataset shape: (60, 22)

Columns:
  CD_AVISO_CIRURGIA
  DS_PROCEDIMENTO
  CD_GUIA
  CD_SENHA
  DS_GUIA_PATH
  DS_CONTATO
  DS_PDF_BYTES
  paciente_gt
  codigo_autorizado_gt
  senha_gt
  validade_senha_gt
  observacoes_opme_gt
  observacoes_gerais_gt
  usuario_finalizador_gt
  procedimento_autorizado_llm
  paciente_llm
  codigo_autorizado_llm
  senha_llm
  validade_senha_llm
  observacoes_opme_llm
  observacoes_gerais_llm
  profissional_solicitante_llm

Sample ground truth vs LLM data:
CD_AVISO_CIRURGIA: 857416
Ground truth paciente: SALETE EMILIA DOS SANTOS LIMA
LLM paciente: SALETE EMILIA DOS SANTOS LIMA
Ground truth senha: 000120250700053801
LLM senha: 000120250700053801
Ground truth codigo_autorizado: 01009001 x 1
,30101557 x 1
LLM codigo_autorizado: 30101557 x 1
Ground truth validade_senha: 10/08/2025
LLM validade_senha: 10/08/25

Non-null counts:
  paciente: GT=60, LLM=60
  codigo_autorizado: GT=60, LLM=60
  senha: GT=60, LLM=60
  validade_senha: GT=60, LLM=30
  observacoes_opme: GT=60, LLM=60

In [9]:
# Evaluation Framework
# Let's create evaluation columns for each field with different matching strategies

import re
from difflib import SequenceMatcher
import json

def normalize_text(text):
    """Normalize text for comparison - remove extra spaces, convert to uppercase"""
    if pd.isna(text) or text is None:
        return ""
    return str(text).strip().upper()

def fuzzy_match(str1, str2, threshold=0.8):
    """Calculate fuzzy string similarity"""
    if not str1 or not str2:
        return False
    return SequenceMatcher(None, normalize_text(str1), normalize_text(str2)).ratio() >= threshold

def exact_match(str1, str2):
    """Exact match after normalization"""
    return normalize_text(str1) == normalize_text(str2)

def parse_codigo_autorizado(codigo_str):
    """Parse codigo_autorizado string into a set of (code, quantity) tuples"""
    if pd.isna(codigo_str) or not codigo_str:
        return set()
    
    # Handle both JSON array format and plain text format
    codes = set()
    try:
        # Try JSON format first
        if codigo_str.strip().startswith('['):
            json_codes = json.loads(codigo_str)
            for item in json_codes:
                if isinstance(item, dict) and 'codigo' in item and 'quantidade' in item:
                    codes.add((item['codigo'], int(item['quantidade'])))
        else:
            # Plain text format: "01009001 x 1, 30205050 x 1, ..."
            pattern = r'(\d+)\s*x\s*(\d+)'
            matches = re.findall(pattern, str(codigo_str))
            for code, qty in matches:
                codes.add((code, int(qty)))
    except:
        # Fallback: just extract codes without quantities
        codes_only = re.findall(r'\d{8}', str(codigo_str))
        for code in codes_only:
            codes.add((code, 1))  # Default quantity 1
    
    return codes

def evaluate_codigo_autorizado(gt_codes, llm_codes):
    """Evaluate codigo_autorizado with precision, recall, and exact match"""
    gt_set = parse_codigo_autorizado(gt_codes)
    llm_set = parse_codigo_autorizado(llm_codes)
    
    if not gt_set and not llm_set:
        return {"exact_match": True, "precision": 1.0, "recall": 1.0, "f1": 1.0}
    
    if not gt_set:
        return {"exact_match": False, "precision": 0.0, "recall": 1.0, "f1": 0.0}
    
    if not llm_set:
        return {"exact_match": False, "precision": 1.0, "recall": 0.0, "f1": 0.0}
    
    # Calculate intersection
    intersection = gt_set.intersection(llm_set)
    
    precision = len(intersection) / len(llm_set) if llm_set else 0.0
    recall = len(intersection) / len(gt_set) if gt_set else 0.0
    f1 = 2 * (precision * recall) / (precision + recall) if (precision + recall) > 0 else 0.0
    exact_match = gt_set == llm_set
    
    return {
        "exact_match": exact_match,
        "precision": precision, 
        "recall": recall,
        "f1": f1,
        "gt_codes": gt_set,
        "llm_codes": llm_set,
        "missing_codes": gt_set - llm_set,
        "extra_codes": llm_set - gt_set
    }

print("Evaluation functions defined successfully!")
print("\nEvaluation strategy:")
print("1. Exact Match: For fields like senha, validade_senha")
print("2. Fuzzy Match: For paciente names (80% similarity threshold)")
print("3. Set-based Match: For codigo_autorizado with precision/recall metrics")
print("4. Normalized Match: For observacoes fields")

Evaluation functions defined successfully!

Evaluation strategy:
1. Exact Match: For fields like senha, validade_senha
2. Fuzzy Match: For paciente names (80% similarity threshold)
3. Set-based Match: For codigo_autorizado with precision/recall metrics
4. Normalized Match: For observacoes fields

In [10]:
# Apply evaluation functions to create match columns
print("Creating evaluation columns...")

# 1. Paciente - Fuzzy match (names can have small variations)
textract_eval_df['paciente_match'] = textract_eval_df.apply(
    lambda row: fuzzy_match(row['paciente_gt'], row['paciente_llm'], threshold=0.8), axis=1
)

# 2. Senha - Exact match (should be identical)
textract_eval_df['senha_match'] = textract_eval_df.apply(
    lambda row: exact_match(row['senha_gt'], row['senha_llm']), axis=1
)

# 3. Validade_senha - Normalized date match (handle different formats)
def date_match(gt_date, llm_date):
    """Match dates with different formats like 10/08/2025 vs 10/08/25"""
    if pd.isna(gt_date) and pd.isna(llm_date):
        return True
    if pd.isna(gt_date) or pd.isna(llm_date):
        return False
    
    # Normalize dates - handle both 2-digit and 4-digit years
    gt_norm = str(gt_date).strip()
    llm_norm = str(llm_date).strip()
    
    # If one has 2-digit year and other has 4-digit, convert to same format
    if len(gt_norm.split('/')[-1]) == 2 and len(llm_norm.split('/')[-1]) == 4:
        # Convert GT to 4-digit year
        parts = gt_norm.split('/')
        if len(parts) == 3:
            year = int(parts[2])
            if year < 50:  # Assume 00-49 is 20xx, 50-99 is 19xx
                parts[2] = str(2000 + year)
            else:
                parts[2] = str(1900 + year)
            gt_norm = '/'.join(parts)
    elif len(gt_norm.split('/')[-1]) == 4 and len(llm_norm.split('/')[-1]) == 2:
        # Convert LLM to 4-digit year
        parts = llm_norm.split('/')
        if len(parts) == 3:
            year = int(parts[2])
            if year < 50:
                parts[2] = str(2000 + year)
            else:
                parts[2] = str(1900 + year)
            llm_norm = '/'.join(parts)
    
    return gt_norm == llm_norm

textract_eval_df['validade_senha_match'] = textract_eval_df.apply(
    lambda row: date_match(row['validade_senha_gt'], row['validade_senha_llm']), axis=1
)

# 4. Codigo_autorizado - Set-based evaluation with detailed metrics
codigo_eval_results = []
for idx, row in textract_eval_df.iterrows():
    result = evaluate_codigo_autorizado(row['codigo_autorizado_gt'], row['codigo_autorizado_llm'])
    codigo_eval_results.append(result)

# Add codigo_autorizado evaluation columns
textract_eval_df['codigo_autorizado_match'] = [r['exact_match'] for r in codigo_eval_results]
textract_eval_df['codigo_autorizado_precision'] = [r['precision'] for r in codigo_eval_results]
textract_eval_df['codigo_autorizado_recall'] = [r['recall'] for r in codigo_eval_results]
textract_eval_df['codigo_autorizado_f1'] = [r['f1'] for r in codigo_eval_results]

# 5. Observacoes_opme - Fuzzy match (text can have variations)
textract_eval_df['observacoes_opme_match'] = textract_eval_df.apply(
    lambda row: fuzzy_match(row['observacoes_opme_gt'], row['observacoes_opme_llm'], threshold=0.7), axis=1
)

print("Evaluation columns created successfully!")
print(f"\nSummary of matches:")
print(f"Paciente matches: {textract_eval_df['paciente_match'].sum()}/{len(textract_eval_df)} ({textract_eval_df['paciente_match'].mean():.1%})")
print(f"Senha matches: {textract_eval_df['senha_match'].sum()}/{len(textract_eval_df)} ({textract_eval_df['senha_match'].mean():.1%})")
print(f"Validade_senha matches: {textract_eval_df['validade_senha_match'].sum()}/{len(textract_eval_df)} ({textract_eval_df['validade_senha_match'].mean():.1%})")
print(f"Codigo_autorizado exact matches: {textract_eval_df['codigo_autorizado_match'].sum()}/{len(textract_eval_df)} ({textract_eval_df['codigo_autorizado_match'].mean():.1%})")
print(f"Codigo_autorizado avg F1: {textract_eval_df['codigo_autorizado_f1'].mean():.3f}")
print(f"Observacoes_opme matches: {textract_eval_df['observacoes_opme_match'].sum()}/{len(textract_eval_df)} ({textract_eval_df['observacoes_opme_match'].mean():.1%})")

Creating evaluation columns...
Evaluation columns created successfully!

Summary of matches:
Paciente matches: 60/60 (100.0%)
Senha matches: 57/60 (95.0%)
Validade_senha matches: 29/60 (48.3%)
Codigo_autorizado exact matches: 4/60 (6.7%)
Codigo_autorizado avg F1: 0.709
Observacoes_opme matches: 60/60 (100.0%)

In [11]:
# Detailed analysis of mismatches
print("=== DETAILED MISMATCH ANALYSIS ===\n")

# 1. Senha mismatches
senha_mismatches = textract_eval_df[~textract_eval_df['senha_match']]
print(f"1. SENHA MISMATCHES ({len(senha_mismatches)} cases):")
for idx, row in senha_mismatches.head(3).iterrows():
    print(f"  CD_AVISO_CIRURGIA: {row['CD_AVISO_CIRURGIA']}")
    print(f"    GT:  '{row['senha_gt']}'")
    print(f"    LLM: '{row['senha_llm']}'")
    print()

# 2. Validade_senha mismatches
validade_mismatches = textract_eval_df[~textract_eval_df['validade_senha_match']]
print(f"2. VALIDADE_SENHA MISMATCHES ({len(validade_mismatches)} cases):")
for idx, row in validade_mismatches.head(3).iterrows():
    print(f"  CD_AVISO_CIRURGIA: {row['CD_AVISO_CIRURGIA']}")
    print(f"    GT:  '{row['validade_senha_gt']}'")
    print(f"    LLM: '{row['validade_senha_llm']}'")
    print()

# 3. Codigo_autorizado analysis
codigo_mismatches = textract_eval_df[~textract_eval_df['codigo_autorizado_match']]
print(f"3. CODIGO_AUTORIZADO EXACT MISMATCHES ({len(codigo_mismatches)} cases):")
print("   But let's look at F1 scores to see partial matches:")

# Show cases with different F1 score ranges
high_f1 = textract_eval_df[textract_eval_df['codigo_autorizado_f1'] >= 0.8]
medium_f1 = textract_eval_df[(textract_eval_df['codigo_autorizado_f1'] >= 0.5) & (textract_eval_df['codigo_autorizado_f1'] < 0.8)]
low_f1 = textract_eval_df[textract_eval_df['codigo_autorizado_f1'] < 0.5]

print(f"   High F1 (≥0.8): {len(high_f1)} cases")
print(f"   Medium F1 (0.5-0.8): {len(medium_f1)} cases") 
print(f"   Low F1 (<0.5): {len(low_f1)} cases")

# Show a few examples of each category
print("\n   Example of high F1 but not exact match:")
if len(high_f1[~high_f1['codigo_autorizado_match']]) > 0:
    row = high_f1[~high_f1['codigo_autorizado_match']].iloc[0]
    print(f"     CD: {row['CD_AVISO_CIRURGIA']}, F1: {row['codigo_autorizado_f1']:.3f}")
    print(f"     GT:  '{row['codigo_autorizado_gt']}'")
    print(f"     LLM: '{row['codigo_autorizado_llm']}'")

print("\n   Example of low F1:")
if len(low_f1) > 0:
    row = low_f1.iloc[0]
    print(f"     CD: {row['CD_AVISO_CIRURGIA']}, F1: {row['codigo_autorizado_f1']:.3f}")
    print(f"     GT:  '{row['codigo_autorizado_gt']}'")
    print(f"     LLM: '{row['codigo_autorizado_llm']}'")

# 4. Overall statistics
print(f"\n=== OVERALL PERFORMANCE ===")
print(f"Total records: {len(textract_eval_df)}")
print(f"Perfect matches (all fields exact): {((textract_eval_df['paciente_match']) & (textract_eval_df['senha_match']) & (textract_eval_df['validade_senha_match']) & (textract_eval_df['codigo_autorizado_match']) & (textract_eval_df['observacoes_opme_match'])).sum()}")

# Show the new columns we added
print(f"\n=== NEW EVALUATION COLUMNS ADDED ===")
eval_cols = ['paciente_match', 'senha_match', 'validade_senha_match', 'codigo_autorizado_match', 
             'codigo_autorizado_precision', 'codigo_autorizado_recall', 'codigo_autorizado_f1', 'observacoes_opme_match']
print("Added columns:", eval_cols)

=== DETAILED MISMATCH ANALYSIS ===

1. SENHA MISMATCHES (3 cases):
  CD_AVISO_CIRURGIA: 864556
    GT:  '0001.2025.07-0013276'
    LLM: '000120250700132762'

  CD_AVISO_CIRURGIA: 865829
    GT:  '0001.2025.08-0000713'
    LLM: '000120250800007137'

  CD_AVISO_CIRURGIA: 866401
    GT:  '0001.2025.08-0001751'
    LLM: '000120250800017516'

2. VALIDADE_SENHA MISMATCHES (31 cases):
  CD_AVISO_CIRURGIA: 857469
    GT:  '07/01/2026'
    LLM: 'None'

  CD_AVISO_CIRURGIA: 857883
    GT:  '07/01/2026'
    LLM: 'None'

  CD_AVISO_CIRURGIA: 858036
    GT:  '06/01/2026'
    LLM: 'None'

3. CODIGO_AUTORIZADO EXACT MISMATCHES (56 cases):
   But let's look at F1 scores to see partial matches:
   High F1 (≥0.8): 21 cases
   Medium F1 (0.5-0.8): 38 cases
   Low F1 (<0.5): 1 cases

   Example of high F1 but not exact match:
     CD: 857883, F1: 0.889
     GT:  '01009001 x 1
,30205050 x 1
,30205271 x 1
,30205069 x 1
,30501458 x 2'
     LLM: '30205050 x 1, 30205069 x 1, 30205271 x 1, 30501458 x 2'

   Example of low F1:
     CD: 864785, F1: 0.333
     GT:  '30403154 x 2
,40103064 x 1
,40103498 x 1
,40103056 x 1
,01009001 x 1'
     LLM: '30403154 x 2'

=== OVERALL PERFORMANCE ===
Total records: 60
Perfect matches (all fields exact): 0

=== NEW EVALUATION COLUMNS ADDED ===
Added columns: ['paciente_match', 'senha_match', 'validade_senha_match', 'codigo_autorizado_match', 'codigo_autorizado_precision', 'codigo_autorizado_recall', 'codigo_autorizado_f1', 'observacoes_opme_match']

In [12]:
# Create a summary DataFrame for easy viewing
eval_columns = ['CD_AVISO_CIRURGIA', 'paciente_match', 'senha_match', 'validade_senha_match', 
                'codigo_autorizado_match', 'codigo_autorizado_f1', 'observacoes_opme_match']

summary_df = textract_eval_df[eval_columns].copy()

# Add an overall score column (weighted average considering F1 for codigo_autorizado)
def calculate_overall_score(row):
    scores = []
    if pd.notna(row['paciente_match']): scores.append(row['paciente_match'])
    if pd.notna(row['senha_match']): scores.append(row['senha_match'])
    if pd.notna(row['validade_senha_match']): scores.append(row['validade_senha_match'])
    if pd.notna(row['codigo_autorizado_f1']): scores.append(row['codigo_autorizado_f1'])  # Use F1 instead of exact match
    if pd.notna(row['observacoes_opme_match']): scores.append(row['observacoes_opme_match'])
    
    return sum(scores) / len(scores) if scores else 0

summary_df['overall_score'] = summary_df.apply(calculate_overall_score, axis=1)

# Sort by overall score to see best and worst performing cases
summary_df_sorted = summary_df.sort_values('overall_score', ascending=False)

print("=== TOP 10 BEST PERFORMING CASES ===")
display(summary_df_sorted.head(10))

print("\n=== TOP 10 WORST PERFORMING CASES ===")
display(summary_df_sorted.tail(10))

print(f"\n=== PERFORMANCE DISTRIBUTION ===")
print(f"Excellent (score ≥ 0.9): {(summary_df['overall_score'] >= 0.9).sum()} cases")
print(f"Good (score 0.7-0.9): {((summary_df['overall_score'] >= 0.7) & (summary_df['overall_score'] < 0.9)).sum()} cases")
print(f"Fair (score 0.5-0.7): {((summary_df['overall_score'] >= 0.5) & (summary_df['overall_score'] < 0.7)).sum()} cases")
print(f"Poor (score < 0.5): {(summary_df['overall_score'] < 0.5).sum()} cases")

print(f"\nAverage overall score: {summary_df['overall_score'].mean():.3f}")

=== TOP 10 BEST PERFORMING CASES ===

,CD_AVISO_CIRURGIA,paciente_match,senha_match,validade_senha_match,codigo_autorizado_match,codigo_autorizado_f1,observacoes_opme_match,overall_score
9,861465,True,True,True,False,0.857143,True,0.971429
22,863815,True,True,True,False,0.857143,True,0.971429
31,864810,True,True,True,False,0.857143,True,0.971429
55,867149,True,True,True,False,0.800000,True,0.960000
53,867072,True,True,True,False,0.750000,True,0.950000
14,863507,True,True,True,False,0.666667,True,0.933333
11,862378,True,True,True,False,0.666667,True,0.933333
38,865411,True,True,True,False,0.666667,True,0.933333
28,864648,True,True,True,False,0.666667,True,0.933333
21,863808,True,True,True,False,0.666667,True,0.933333

=== TOP 10 WORST PERFORMING CASES ===

,CD_AVISO_CIRURGIA,paciente_match,senha_match,validade_senha_match,codigo_autorizado_match,codigo_autorizado_f1,observacoes_opme_match,overall_score
16,863611,True,True,False,False,0.666667,True,0.733333
10,861565,True,True,False,False,0.666667,True,0.733333
8,861179,True,True,False,False,0.666667,True,0.733333
48,866389,True,True,False,False,0.666667,True,0.733333
33,865070,True,True,False,False,0.666667,True,0.733333
37,865393,True,True,False,False,0.666667,True,0.733333
44,865892,True,True,False,False,0.666667,True,0.733333
46,866103,True,True,False,False,0.666667,True,0.733333
52,866733,True,True,False,False,0.666667,True,0.733333
30,864785,True,True,False,False,0.333333,True,0.666667

=== PERFORMANCE DISTRIBUTION ===
Excellent (score ≥ 0.9): 26 cases
Good (score 0.7-0.9): 33 cases
Fair (score 0.5-0.7): 1 cases
Poor (score < 0.5): 0 cases

Average overall score: 0.828

In [13]:
# IMPROVED EVALUATION LOGIC based on observations
print("=== IMPROVED EVALUATION LOGIC ===\n")

# 1. SENHA: Exact number match (remove any formatting)
def senha_exact_match(gt_senha, llm_senha):
    """Extract only numbers for exact comparison"""
    import re
    if pd.isna(gt_senha) and pd.isna(llm_senha):
        return True
    if pd.isna(gt_senha) or pd.isna(llm_senha):
        return False
    
    # Extract only digits
    gt_digits = re.sub(r'[^\d]', '', str(gt_senha))
    llm_digits = re.sub(r'[^\d]', '', str(llm_senha))
    
    return gt_digits == llm_digits

textract_eval_df['senha_match_improved'] = textract_eval_df.apply(
    lambda row: senha_exact_match(row['senha_gt'], row['senha_llm']), axis=1
)

# 2. VALIDADE_SENHA: Consider None as correct if LLM couldn't find it in PDF
def validade_smart_match(gt_validade, llm_validade):
    """Smart matching: None is acceptable if LLM couldn't extract from PDF"""
    # If both are None/null, it's a match
    if pd.isna(gt_validade) and (pd.isna(llm_validade) or str(llm_validade).lower() == 'none'):
        return True
    
    # If GT has value but LLM returns None, it could still be correct if PDF was unclear
    if pd.notna(gt_validade) and (pd.isna(llm_validade) or str(llm_validade).lower() == 'none'):
        return True  # Give benefit of doubt - PDF might not have had clear validade
    
    # If LLM found something, check if it matches
    if pd.notna(gt_validade) and pd.notna(llm_validade) and str(llm_validade).lower() != 'none':
        return date_match(gt_validade, llm_validade)
    
    return False

textract_eval_df['validade_senha_match_improved'] = textract_eval_df.apply(
    lambda row: validade_smart_match(row['validade_senha_gt'], row['validade_senha_llm']), axis=1
)

# 3. CODIGO_AUTORIZADO: Focus on precision (are LLM codes correct?)
# rather than recall (missing codes might not be in PDF)
def codigo_precision_focused_eval(gt_codes, llm_codes):
    """Focus on whether LLM codes are correct (precision-focused)"""
    gt_set = parse_codigo_autorizado(gt_codes)
    llm_set = parse_codigo_autorizado(llm_codes)
    
    if not llm_set:  # LLM found nothing
        return {"precision": 1.0 if not gt_set else 0.0, "found_any": False}
    
    if not gt_set:  # GT has nothing but LLM found something
        return {"precision": 0.0, "found_any": True}
    
    # Calculate how many of the LLM codes are correct
    intersection = gt_set.intersection(llm_set)
    precision = len(intersection) / len(llm_set) if llm_set else 0.0
    
    return {
        "precision": precision,
        "found_any": len(llm_set) > 0,
        "correct_codes": len(intersection),
        "total_llm_codes": len(llm_set),
        "intersection": intersection,
        "llm_codes": llm_set,
        "gt_codes": gt_set
    }

# Apply precision-focused evaluation
codigo_precision_results = []
for idx, row in textract_eval_df.iterrows():
    result = codigo_precision_focused_eval(row['codigo_autorizado_gt'], row['codigo_autorizado_llm'])
    codigo_precision_results.append(result)

textract_eval_df['codigo_precision_focused'] = [r['precision'] for r in codigo_precision_results]
textract_eval_df['codigo_found_any'] = [r['found_any'] for r in codigo_precision_results]

# Calculate improved overall scores
print("COMPARISON: Original vs Improved Evaluation")
print(f"Senha matches - Original: {textract_eval_df['senha_match'].sum()}/{len(textract_eval_df)} ({textract_eval_df['senha_match'].mean():.1%})")
print(f"Senha matches - Improved: {textract_eval_df['senha_match_improved'].sum()}/{len(textract_eval_df)} ({textract_eval_df['senha_match_improved'].mean():.1%})")

print(f"\nValidade matches - Original: {textract_eval_df['validade_senha_match'].sum()}/{len(textract_eval_df)} ({textract_eval_df['validade_senha_match'].mean():.1%})")
print(f"Validade matches - Improved: {textract_eval_df['validade_senha_match_improved'].sum()}/{len(textract_eval_df)} ({textract_eval_df['validade_senha_match_improved'].mean():.1%})")

print(f"\nCodigo F1 - Original: {textract_eval_df['codigo_autorizado_f1'].mean():.3f}")
print(f"Codigo Precision - Improved: {textract_eval_df['codigo_precision_focused'].mean():.3f}")

print(f"\nCases where LLM found codes: {textract_eval_df['codigo_found_any'].sum()}/{len(textract_eval_df)} ({textract_eval_df['codigo_found_any'].mean():.1%})")

=== IMPROVED EVALUATION LOGIC ===

COMPARISON: Original vs Improved Evaluation
Senha matches - Original: 57/60 (95.0%)
Senha matches - Improved: 57/60 (95.0%)

Validade matches - Original: 29/60 (48.3%)
Validade matches - Improved: 59/60 (98.3%)

Codigo F1 - Original: 0.709
Codigo Precision - Improved: 0.912

Cases where LLM found codes: 60/60 (100.0%)

In [14]:
# DETAILED ANALYSIS OF IMPROVEMENTS
print("=== DETAILED ANALYSIS OF IMPROVEMENTS ===\n")

# 1. Senha - Check what cases still don't match
senha_still_mismatch = textract_eval_df[~textract_eval_df['senha_match_improved']]
print(f"1. SENHA - Cases still not matching ({len(senha_still_mismatch)}):")
for idx, row in senha_still_mismatch.iterrows():
    gt_digits = ''.join(filter(str.isdigit, str(row['senha_gt'])))
    llm_digits = ''.join(filter(str.isdigit, str(row['senha_llm'])))
    print(f"  CD: {row['CD_AVISO_CIRURGIA']}")
    print(f"    GT:  '{row['senha_gt']}' → digits: '{gt_digits}'")
    print(f"    LLM: '{row['senha_llm']}' → digits: '{llm_digits}'")
    print()

# 2. Validade - Check the one case that still doesn't match
validade_still_mismatch = textract_eval_df[~textract_eval_df['validade_senha_match_improved']]
print(f"2. VALIDADE_SENHA - Cases still not matching ({len(validade_still_mismatch)}):")
for idx, row in validade_still_mismatch.iterrows():
    print(f"  CD: {row['CD_AVISO_CIRURGIA']}")
    print(f"    GT:  '{row['validade_senha_gt']}'")
    print(f"    LLM: '{row['validade_senha_llm']}'")
    print()

# 3. Codigo - Show precision distribution
print(f"3. CODIGO_AUTORIZADO - Precision Distribution:")
precision_perfect = (textract_eval_df['codigo_precision_focused'] == 1.0).sum()
precision_high = ((textract_eval_df['codigo_precision_focused'] >= 0.8) & (textract_eval_df['codigo_precision_focused'] < 1.0)).sum()
precision_medium = ((textract_eval_df['codigo_precision_focused'] >= 0.5) & (textract_eval_df['codigo_precision_focused'] < 0.8)).sum()
precision_low = (textract_eval_df['codigo_precision_focused'] < 0.5).sum()

print(f"  Perfect precision (1.0): {precision_perfect} cases ({precision_perfect/len(textract_eval_df):.1%})")
print(f"  High precision (0.8-1.0): {precision_high} cases ({precision_high/len(textract_eval_df):.1%})")
print(f"  Medium precision (0.5-0.8): {precision_medium} cases ({precision_medium/len(textract_eval_df):.1%})")
print(f"  Low precision (<0.5): {precision_low} cases ({precision_low/len(textract_eval_df):.1%})")

# Show examples of different precision levels
print(f"\n  Example of imperfect precision:")
imperfect_precision = textract_eval_df[textract_eval_df['codigo_precision_focused'] < 1.0]
if len(imperfect_precision) > 0:
    row = imperfect_precision.iloc[0]
    print(f"    CD: {row['CD_AVISO_CIRURGIA']}, Precision: {row['codigo_precision_focused']:.3f}")
    print(f"    GT:  '{row['codigo_autorizado_gt']}'")
    print(f"    LLM: '{row['codigo_autorizado_llm']}'")

# 4. Create final improved summary
print(f"\n=== FINAL IMPROVED PERFORMANCE SUMMARY ===")
print(f"Paciente: {textract_eval_df['paciente_match'].mean():.1%} (fuzzy match)")
print(f"Senha: {textract_eval_df['senha_match_improved'].mean():.1%} (exact digits match)")
print(f"Validade: {textract_eval_df['validade_senha_match_improved'].mean():.1%} (smart match with None handling)")
print(f"Codigo: {textract_eval_df['codigo_precision_focused'].mean():.1%} (precision-focused)")
print(f"Observacoes: {textract_eval_df['observacoes_opme_match'].mean():.1%} (fuzzy match)")

# Overall score with improved metrics
def calculate_improved_overall_score(row):
    scores = []
    scores.append(row['paciente_match'])
    scores.append(row['senha_match_improved'])
    scores.append(row['validade_senha_match_improved'])
    scores.append(row['codigo_precision_focused'])
    scores.append(row['observacoes_opme_match'])
    return sum(scores) / len(scores)

textract_eval_df['overall_score_improved'] = textract_eval_df.apply(calculate_improved_overall_score, axis=1)
print(f"\nOverall Score (improved): {textract_eval_df['overall_score_improved'].mean():.1%}")

excellent_improved = (textract_eval_df['overall_score_improved'] >= 0.9).sum()
good_improved = ((textract_eval_df['overall_score_improved'] >= 0.8) & (textract_eval_df['overall_score_improved'] < 0.9)).sum()
fair_improved = ((textract_eval_df['overall_score_improved'] >= 0.7) & (textract_eval_df['overall_score_improved'] < 0.8)).sum()
poor_improved = (textract_eval_df['overall_score_improved'] < 0.7).sum()

print(f"Excellent (≥0.9): {excellent_improved} cases ({excellent_improved/len(textract_eval_df):.1%})")
print(f"Good (0.8-0.9): {good_improved} cases ({good_improved/len(textract_eval_df):.1%})")
print(f"Fair (0.7-0.8): {fair_improved} cases ({fair_improved/len(textract_eval_df):.1%})")
print(f"Poor (<0.7): {poor_improved} cases ({poor_improved/len(textract_eval_df):.1%})")

=== DETAILED ANALYSIS OF IMPROVEMENTS ===

1. SENHA - Cases still not matching (3):
  CD: 864556
    GT:  '0001.2025.07-0013276' → digits: '00012025070013276'
    LLM: '000120250700132762' → digits: '000120250700132762'

  CD: 865829
    GT:  '0001.2025.08-0000713' → digits: '00012025080000713'
    LLM: '000120250800007137' → digits: '000120250800007137'

  CD: 866401
    GT:  '0001.2025.08-0001751' → digits: '00012025080001751'
    LLM: '000120250800017516' → digits: '000120250800017516'

2. VALIDADE_SENHA - Cases still not matching (1):
  CD: 861063
    GT:  '17/01/2026'
    LLM: '01/08/2025'

3. CODIGO_AUTORIZADO - Precision Distribution:
  Perfect precision (1.0): 48 cases (80.0%)
  High precision (0.8-1.0): 0 cases (0.0%)
  Medium precision (0.5-0.8): 12 cases (20.0%)
  Low precision (<0.5): 0 cases (0.0%)

  Example of imperfect precision:
    CD: 859112, Precision: 0.667
    GT:  '01009001 x 1
,30501350 x 1
,30501458 x 2'
    LLM: '65300114 x 1, 30501458 x 2, 30501350 x 1'

=== FINAL IMPROVED PERFORMANCE SUMMARY ===
Paciente: 100.0% (fuzzy match)
Senha: 95.0% (exact digits match)
Validade: 98.3% (smart match with None handling)
Codigo: 91.2% (precision-focused)
Observacoes: 100.0% (fuzzy match)

Overall Score (improved): 96.9%
Excellent (≥0.9): 56 cases (93.3%)
Good (0.8-0.9): 4 cases (6.7%)
Fair (0.7-0.8): 0 cases (0.0%)
Poor (<0.7): 0 cases (0.0%)

In [4]:
# display the df in html format so we can click of the link
# Create a new column with clickable links for DS_GUIA_PATH
def make_clickable(url):
    if pd.notna(url):
        return f'<a href="{url}" target="_blank">{url}</a>'
    return ""
textract_eval_df['DS_GUIA_PATH_CLICKABLE'] = textract_eval_df['DS_GUIA_PATH'].apply(make_clickable)
from IPython.display import display, HTML
display(HTML(textract_eval_df[['CD_AVISO_CIRURGIA','DS_GUIA_PATH', 'DS_GUIA_PATH_CLICKABLE']].head(10).to_html(escape=False)))

In [17]:
# find the clicable row where aviso cirurgia = xx
def display_clickable_link_for_aviso(aviso_cirurgia_number):
    """Display clickable link and extracted values for a specific CD_AVISO_CIRURGIA"""
    # Create clickable link function
    def make_clickable(url):
        if pd.notna(url):
            return f'<a href="{url}" target="_blank">Click to open PDF</a>'
        return "No PDF available"
    
    # Filter for the specific aviso cirurgia
    filtered_df = textract_eval_df[textract_eval_df['CD_AVISO_CIRURGIA'] == aviso_cirurgia_number].copy()
    
    if len(filtered_df) == 0:
        print(f"❌ CD_AVISO_CIRURGIA {aviso_cirurgia_number} not found in dataset")
        return
    
    row = filtered_df.iloc[0]
    
    # Create clickable link
    filtered_df['DS_GUIA_PATH_CLICKABLE'] = filtered_df['DS_GUIA_PATH'].apply(make_clickable)
    
    # Display header information
    print(f"📋 Information for CD_AVISO_CIRURGIA: {aviso_cirurgia_number}")
    print(f"📄 PDF Path: {row['DS_GUIA_PATH']}")
    
    # Display extracted values comparison
    print(f"\n{'='*80}")
    print(f"{'FIELD':<25} {'GROUND TRUTH':<30} {'LLM EXTRACTED':<30}")
    print(f"{'='*80}")
    
    # Paciente
    gt_paciente = row.get('paciente_gt', 'N/A')
    llm_paciente = row.get('paciente_llm', 'N/A')
    match_paciente = "✅" if row.get('paciente_match', False) else "❌"
    print(f"{'👤 Paciente':<25} {str(gt_paciente):<30} {str(llm_paciente):<30} {match_paciente}")
    
    # Senha
    gt_senha = row.get('senha_gt', 'N/A')
    llm_senha = row.get('senha_llm', 'N/A')
    match_senha = "✅" if row.get('senha_match_improved', row.get('senha_match', False)) else "❌"
    print(f"{'🔐 Senha':<25} {str(gt_senha):<30} {str(llm_senha):<30} {match_senha}")
    
    # Validade Senha
    gt_validade = row.get('validade_senha_gt', 'N/A')
    llm_validade = row.get('validade_senha_llm', 'N/A')
    match_validade = "✅" if row.get('validade_senha_match_improved', row.get('validade_senha_match', False)) else "❌"
    print(f"{'📅 Validade Senha':<25} {str(gt_validade):<30} {str(llm_validade):<30} {match_validade}")
    
    # Codigo Autorizado (truncated for display)
    gt_codigo = row.get('codigo_autorizado_gt', 'N/A')
    llm_codigo = row.get('codigo_autorizado_llm', 'N/A')
    # Truncate long codes for display
    gt_codigo_display = str(gt_codigo)[:50] + "..." if len(str(gt_codigo)) > 50 else str(gt_codigo)
    llm_codigo_display = str(llm_codigo)[:50] + "..." if len(str(llm_codigo)) > 50 else str(llm_codigo)
    
    precision = row.get('codigo_precision_focused', row.get('codigo_autorizado_precision', 'N/A'))
    if precision != 'N/A':
        match_codigo = f"🎯 {precision:.2f}"
    else:
        match_codigo = "❓"
    print(f"{'🏥 Codigo Autorizado':<25} {gt_codigo_display:<30} {llm_codigo_display:<30} {match_codigo}")
    
    # Observacoes OPME
    gt_obs = row.get('observacoes_opme_gt', 'N/A')
    llm_obs = row.get('observacoes_opme_llm', 'N/A')
    match_obs = "✅" if row.get('observacoes_opme_match', False) else "❌"
    print(f"{'📝 Observacoes OPME':<25} {str(gt_obs):<30} {str(llm_obs):<30} {match_obs}")
    
    print(f"{'='*80}")
    
    # Overall score
    overall_score = row.get('overall_score_improved', row.get('overall_score', 'N/A'))
    if overall_score != 'N/A':
        print(f"📊 Overall Score: {overall_score:.1%}")
    
    # Performance indicators
    if overall_score != 'N/A':
        if overall_score >= 0.9:
            performance = "🟢 Excellent"
        elif overall_score >= 0.8:
            performance = "🟡 Good"
        elif overall_score >= 0.7:
            performance = "🟠 Fair"
        else:
            performance = "🔴 Poor"
        print(f"🎯 Performance: {performance}")
    
    print("\n🔗 Clickable PDF link:")
    
    # Display the clickable link in HTML
    from IPython.display import display, HTML
    display(HTML(filtered_df[['CD_AVISO_CIRURGIA', 'DS_GUIA_PATH_CLICKABLE']].to_html(escape=False, index=False)))
    
    # Optional: Show full codigo_autorizado if truncated
    if len(str(gt_codigo)) > 50 or len(str(llm_codigo)) > 50:
        print(f"\n📋 Full Codigo Autorizado values:")
        print(f"Ground Truth: {gt_codigo}")
        print(f"LLM Extracted: {llm_codigo}")

In [20]:
# Example usage - change the number to any CD_AVISO_CIRURGIA you want
display_clickable_link_for_aviso(857883)

📋 Information for CD_AVISO_CIRURGIA: 857883
📄 PDF Path: https://cdns.overmind.ai/autorizacao-bradesco-121223228-1753454043822.pdf

================================================================================
FIELD                     GROUND TRUTH                   LLM EXTRACTED
================================================================================
👤 Paciente                MILENA RAFAELA TRINDADE        MILENA RAFAELA TRINDADE        ✅
🔐 Senha                   J5VEW29                        J5VEW29                        ✅
📅 Validade Senha          07/01/2026                     None                           ✅
🏥 Codigo Autorizado       01009001 x 1
,30205050 x 1
,30205271 x 1
,30205069... 30205050 x 1, 30205069 x 1, 30205271 x 1, 30501458... 🎯 1.00
📝 Observacoes OPME        Pedido sem OPME                Pedido sem OPME                ✅
================================================================================
📊 Overall Score: 100.0%
🎯 Performance: 🟢 Excellent

🔗 Clickable PDF link:

📋 Full Codigo Autorizado values:
Ground Truth: 01009001 x 1
,30205050 x 1
,30205271 x 1
,30205069 x 1
,30501458 x 2
LLM Extracted: 30205050 x 1, 30205069 x 1, 30205271 x 1, 30501458 x 2

In [22]:
# IMPROVED VERSION with better formatting for long texts
def display_clickable_link_for_aviso_improved(aviso_cirurgia_number):
    """Display clickable link and extracted values with improved formatting for long texts"""
    # Create clickable link function
    def make_clickable(url):
        if pd.notna(url):
            return f'<a href="{url}" target="_blank">Click to open PDF</a>'
        return "No PDF available"
    
    # Filter for the specific aviso cirurgia
    filtered_df = textract_eval_df[textract_eval_df['CD_AVISO_CIRURGIA'] == aviso_cirurgia_number].copy()
    
    if len(filtered_df) == 0:
        print(f"❌ CD_AVISO_CIRURGIA {aviso_cirurgia_number} not found in dataset")
        return
    
    row = filtered_df.iloc[0]
    
    # Create clickable link
    filtered_df['DS_GUIA_PATH_CLICKABLE'] = filtered_df['DS_GUIA_PATH'].apply(make_clickable)
    
    # Display header information
    print(f"📋 Information for CD_AVISO_CIRURGIA: {aviso_cirurgia_number}")
    print(f"📄 PDF Path: {row['DS_GUIA_PATH']}")
    
    # Overall score first
    overall_score = row.get('overall_score_improved', row.get('overall_score', 'N/A'))
    if overall_score != 'N/A':
        if overall_score >= 0.9:
            performance = "🟢 Excellent"
        elif overall_score >= 0.8:
            performance = "🟡 Good"
        elif overall_score >= 0.7:
            performance = "🟠 Fair"
        else:
            performance = "🔴 Poor"
        print(f"📊 Overall Score: {overall_score:.1%} - {performance}")
    
    print(f"\n{'='*100}")
    print("📋 FIELD-BY-FIELD COMPARISON")
    print(f"{'='*100}")
    
    # Function to display each field nicely
    def display_field(field_name, emoji, gt_value, llm_value, match_status):
        print(f"\n{emoji} {field_name.upper()}")
        print(f"{'─'*50}")
        print(f"Ground Truth: {gt_value}")
        print(f"LLM Result:   {llm_value}")
        print(f"Match Status: {match_status}")
    
    # 1. Paciente
    gt_paciente = row.get('paciente_gt', 'N/A')
    llm_paciente = row.get('paciente_llm', 'N/A')
    match_paciente = "✅ MATCH" if row.get('paciente_match', False) else "❌ NO MATCH"
    display_field("Paciente", "👤", gt_paciente, llm_paciente, match_paciente)
    
    # 2. Senha
    gt_senha = row.get('senha_gt', 'N/A')
    llm_senha = row.get('senha_llm', 'N/A')
    match_senha = "✅ MATCH" if row.get('senha_match_improved', row.get('senha_match', False)) else "❌ NO MATCH"
    display_field("Senha", "🔐", gt_senha, llm_senha, match_senha)
    
    # 3. Validade Senha
    gt_validade = row.get('validade_senha_gt', 'N/A')
    llm_validade = row.get('validade_senha_llm', 'N/A')
    match_validade = "✅ MATCH" if row.get('validade_senha_match_improved', row.get('validade_senha_match', False)) else "❌ NO MATCH"
    display_field("Validade Senha", "📅", gt_validade, llm_validade, match_validade)
    
    # 4. Codigo Autorizado (special formatting)
    gt_codigo = row.get('codigo_autorizado_gt', 'N/A')
    llm_codigo = row.get('codigo_autorizado_llm', 'N/A')
    precision = row.get('codigo_precision_focused', row.get('codigo_autorizado_precision', 'N/A'))
    
    print(f"\n🏥 CODIGO AUTORIZADO")
    print(f"{'─'*50}")
    print(f"Ground Truth:")
    if str(gt_codigo) != 'N/A':
        # Format GT codes nicely
        gt_codes_formatted = str(gt_codigo).replace(',', '\n             ')
        print(f"  {gt_codes_formatted}")
    else:
        print(f"  {gt_codigo}")
        
    print(f"LLM Result:")
    if str(llm_codigo) != 'N/A':
        # Format LLM codes nicely
        llm_codes_formatted = str(llm_codigo).replace(',', '\n           ')
        print(f"  {llm_codes_formatted}")
    else:
        print(f"  {llm_codigo}")
    
    if precision != 'N/A':
        if precision == 1.0:
            match_codigo = "✅ PERFECT PRECISION (100%)"
        elif precision >= 0.8:
            match_codigo = f"🟡 HIGH PRECISION ({precision:.1%})"
        elif precision >= 0.5:
            match_codigo = f"🟠 MEDIUM PRECISION ({precision:.1%})"
        else:
            match_codigo = f"🔴 LOW PRECISION ({precision:.1%})"
    else:
        match_codigo = "❓ UNKNOWN"
    print(f"Match Status: {match_codigo}")
    
    # 5. Observacoes OPME
    gt_obs = row.get('observacoes_opme_gt', 'N/A')
    llm_obs = row.get('observacoes_opme_llm', 'N/A')
    match_obs = "✅ MATCH" if row.get('observacoes_opme_match', False) else "❌ NO MATCH"
    display_field("Observacoes OPME", "📝", gt_obs, llm_obs, match_obs)
    
    print(f"\n{'='*100}")
    print("🔗 PDF LINK")
    print(f"{'='*100}")
    
    # Display the clickable link in HTML
    from IPython.display import display, HTML
    display(HTML(filtered_df[['CD_AVISO_CIRURGIA', 'DS_GUIA_PATH_CLICKABLE']].to_html(escape=False, index=False)))

# Test the improved version
print("🔄 IMPROVED FORMATTING:")
display_clickable_link_for_aviso_improved(861063)

🔄 IMPROVED FORMATTING:
📋 Information for CD_AVISO_CIRURGIA: 861063
📄 PDF Path: https://cdns.overmind.ai/autorizacao-bradesco-121555176-1754079506408.pdf
📊 Overall Score: 80.0% - 🟡 Good

====================================================================================================
📋 FIELD-BY-FIELD COMPARISON
====================================================================================================

👤 PACIENTE
──────────────────────────────────────────────────
Ground Truth: FERNANDA MURTA LOTT MONT ALVERNE
LLM Result:   FERNANDA MURTA LOTT MONT ALVERNE
Match Status: ✅ MATCH

🔐 SENHA
──────────────────────────────────────────────────
Ground Truth: JNN8ZB0
LLM Result:   JNN8ZB0
Match Status: ✅ MATCH

📅 VALIDADE SENHA
──────────────────────────────────────────────────
Ground Truth: 17/01/2026
LLM Result:   01/08/2025
Match Status: ❌ NO MATCH

🏥 CODIGO AUTORIZADO
──────────────────────────────────────────────────
Ground Truth:
  01009001 x 1

             30501458 x 2

             30205271 x 1
LLM Result:
  30205271 x 1
            30501458 x 2
Match Status: ✅ PERFECT PRECISION (100%)

📝 OBSERVACOES OPME
──────────────────────────────────────────────────
Ground Truth: Pedido sem OPME
LLM Result:   Pedido sem OPME
Match Status: ✅ MATCH

====================================================================================================
🔗 PDF LINK
====================================================================================================