In [16]:
import pandas as pd
import openpyxl

In [17]:
nome_do_arquivo = 'docs/autorizacoes_2025.xlsx'


df = pd.read_excel(nome_do_arquivo)
print("Arquivo carregado com sucesso!")

Arquivo carregado com sucesso!

In [18]:
df.head()

,CD_GUIA,TP_GUIA,CD_AVISO_CIRURGIA,TP_SITUACAO,DT_SOLICITACAO,DT_AUTORIZACAO,CD_GUIA_1,CD_AVISO,DT_INSERCAO,DT_OVERMIND,DS_PROTOCOLO,DT_STATUS,TP_STATUS,DS_STATUS,CD_SENHA,DT_SENHA,DS_GUIA_PATH
0,19548918.0,P,NaN,A,2025-07-16,2025-07-15 17:47:19,19548918.0,0.0,2025-07-15 17:47:17,2025-07-15 17:47:19,278704618,2025-07-15 17:47:19,A,NaN,278704618,NaN,http://cdn.overmind.ai/autorizacao-cassi-27870...
1,19548917.0,P,NaN,A,2025-08-01,2025-08-01 02:16:20,19548917.0,0.0,2025-07-31 11:09:07,2025-07-31 11:09:11,279467334,2025-08-01 02:16:20,A,NaN,279467334,NaN,https://cdns.overmind.ai/autorizacao-cassi-279...
2,19627380.0,S,NaN,A,2025-07-24,2025-07-24 07:21:17,19627380.0,0.0,2025-07-24 07:20:43,2025-07-24 07:21:17,1500953,2025-07-24 07:21:17,A,NaN,29013392,NaN,http://cdn.overmind.ai/autorizacao-cnu-1500953...
3,19341607.0,C,NaN,P,NaT,NaT,19341607.0,0.0,2025-06-24 08:21:52,2025-06-24 08:22:15,103872562025,2025-06-24 08:22:15,N,1214 - Credenciado não habilitado a realizar o...,NaN,NaN,NaN
4,19487547.0,P,NaN,A,NaT,2025-07-09 08:29:07,19487547.0,0.0,2025-07-09 08:28:21,2025-07-09 08:29:07,121546854,2025-07-09 08:29:07,A,NaN,87095062,NaN,http://cdn.overmind.ai/autorizacao-segurosunim...

In [26]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 308409 entries, 0 to 308408
Data columns (total 18 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   CD_GUIA            308111 non-null  float64
 1   TP_GUIA            308249 non-null  object
 2   CD_AVISO_CIRURGIA  6532 non-null    object
 3   TP_SITUACAO        308141 non-null  object
 4   DT_SOLICITACAO     281132 non-null  datetime64[ns]
 5   DT_AUTORIZACAO     289191 non-null  datetime64[ns]
 6   CD_GUIA_1          308111 non-null  float64
 7   CD_AVISO           100258 non-null  float64
 8   DT_INSERCAO        308111 non-null  datetime64[ns]
 9   DT_OVERMIND        308111 non-null  datetime64[ns]
 10  DS_PROTOCOLO       255072 non-null  object
 11  DT_STATUS          308111 non-null  datetime64[ns]
 12  TP_STATUS          304454 non-null  object
 13  DS_STATUS          65814 non-null   object
 14  CD_SENHA           155782 non-null  object
 15  DT_SENHA           0 non-null       float64
 16  DS_GUIA_PATH       227979 non-null  object
 17  CONVENIO           227979 non-null  object
dtypes: datetime64[ns](5), float64(4), object(9)
memory usage: 42.4+ MB

In [19]:
# Exibe as 5 primeiras linhas do DataFrame para uma inspeção visual
print("--- Primeiras 5 linhas do DataFrame ---")
display(df.head())

# Exibe um resumo técnico, incluindo o nome das colunas, a contagem de valores não nulos e os tipos de dados
print("\n--- Informações do DataFrame ---")
df.info()

--- Primeiras 5 linhas do DataFrame ---

,CD_GUIA,TP_GUIA,CD_AVISO_CIRURGIA,TP_SITUACAO,DT_SOLICITACAO,DT_AUTORIZACAO,CD_GUIA_1,CD_AVISO,DT_INSERCAO,DT_OVERMIND,DS_PROTOCOLO,DT_STATUS,TP_STATUS,DS_STATUS,CD_SENHA,DT_SENHA,DS_GUIA_PATH
0,19548918.0,P,NaN,A,2025-07-16,2025-07-15 17:47:19,19548918.0,0.0,2025-07-15 17:47:17,2025-07-15 17:47:19,278704618,2025-07-15 17:47:19,A,NaN,278704618,NaN,http://cdn.overmind.ai/autorizacao-cassi-27870...
1,19548917.0,P,NaN,A,2025-08-01,2025-08-01 02:16:20,19548917.0,0.0,2025-07-31 11:09:07,2025-07-31 11:09:11,279467334,2025-08-01 02:16:20,A,NaN,279467334,NaN,https://cdns.overmind.ai/autorizacao-cassi-279...
2,19627380.0,S,NaN,A,2025-07-24,2025-07-24 07:21:17,19627380.0,0.0,2025-07-24 07:20:43,2025-07-24 07:21:17,1500953,2025-07-24 07:21:17,A,NaN,29013392,NaN,http://cdn.overmind.ai/autorizacao-cnu-1500953...
3,19341607.0,C,NaN,P,NaT,NaT,19341607.0,0.0,2025-06-24 08:21:52,2025-06-24 08:22:15,103872562025,2025-06-24 08:22:15,N,1214 - Credenciado não habilitado a realizar o...,NaN,NaN,NaN
4,19487547.0,P,NaN,A,NaT,2025-07-09 08:29:07,19487547.0,0.0,2025-07-09 08:28:21,2025-07-09 08:29:07,121546854,2025-07-09 08:29:07,A,NaN,87095062,NaN,http://cdn.overmind.ai/autorizacao-segurosunim...

--- Informações do DataFrame ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 308409 entries, 0 to 308408
Data columns (total 17 columns):
 #   Column             Non-Null Count   Dtype
---  ------             --------------   -----
 0   CD_GUIA            308111 non-null  float64
 1   TP_GUIA            308249 non-null  object
 2   CD_AVISO_CIRURGIA  6532 non-null    object
 3   TP_SITUACAO        308141 non-null  object
 4   DT_SOLICITACAO     281132 non-null  datetime64[ns]
 5   DT_AUTORIZACAO     289191 non-null  datetime64[ns]
 6   CD_GUIA_1          308111 non-null  float64
 7   CD_AVISO           100258 non-null  float64
 8   DT_INSERCAO        308111 non-null  datetime64[ns]
 9   DT_OVERMIND        308111 non-null  datetime64[ns]
 10  DS_PROTOCOLO       255072 non-null  object
 11  DT_STATUS          308111 non-null  datetime64[ns]
 12  TP_STATUS          304454 non-null  object
 13  DS_STATUS          65814 non-null   object
 14  CD_SENHA           155782 non-null  object
 15  DT_SENHA           0 non-null       float64
 16  DS_GUIA_PATH       227979 non-null  object
dtypes: datetime64[ns](5), float64(4), object(8)
memory usage: 40.0+ MB

In [20]:
# A função str.extract() usa a expressão regular (regex) para extrair os nomes dos convênios.
# O padrão r'autorizacao-([a-zA-Z_]+)-' captura o texto entre 'autorizacao-' e o hífen seguinte.
# O 'na=False' garante que a extração não seja aplicada em linhas onde o link é nulo (NaN).
df['CONVENIO'] = df['DS_GUIA_PATH'].str.extract(r'autorizacao-([a-zA-Z_]+)-', expand=False)

# Exibe as 5 primeiras linhas da nova coluna para conferência
print("--- Amostra da nova coluna 'CONVENIO' ---")
display(df[['DS_GUIA_PATH', 'CONVENIO']].head())

# Exibe as 5 últimas linhas também, para vermos a variedade
print("\n--- Últimas 5 linhas para comparação ---")
display(df[['DS_GUIA_PATH', 'CONVENIO']].tail())

--- Amostra da nova coluna 'CONVENIO' ---

                                        DS_GUIA_PATH       CONVENIO
0  http://cdn.overmind.ai/autorizacao-cassi-27870...          cassi
1  https://cdns.overmind.ai/autorizacao-cassi-279...          cassi
2  http://cdn.overmind.ai/autorizacao-cnu-1500953...            cnu
3                                                NaN            NaN
4  http://cdn.overmind.ai/autorizacao-segurosunim...  segurosunimed

--- Últimas 5 linhas para comparação ---

                                             DS_GUIA_PATH          CONVENIO
308404  http://cdn.overmind.ai/autorizacao-unimeduberl...  unimeduberlandia
308405  http://cdn.overmind.ai/autorizacao-unimeduberl...  unimeduberlandia
308406  http://cdn.overmind.ai/autorizacao-unimeduberl...  unimeduberlandia
308407  http://cdn.overmind.ai/autorizacao-unimeduberl...  unimeduberlandia
308408  http://cdn.overmind.ai/autorizacao-benner-2841...            benner

In [21]:
# Conta a ocorrência de cada convênio na nova coluna.
contagem_convenios = df['CONVENIO'].value_counts()

# Conta o número de links ausentes (NaN) na coluna original.
contagem_na = df['DS_GUIA_PATH'].isna().sum()

print("--- Contagem por Convênio (Top 40) ---")
display(contagem_convenios.head(40))

print(f"\nNúmero total de links ausentes (NA): {contagem_na}")

--- Contagem por Convênio (Top 40) ---

CONVENIO
bradesco                          47178
sulamerica                        23698
cemig                             21770
ipsemg                            19835
benner                            15263
unimeduberlandia                  11081
copass                            10468
stellantis                        10139
cnu                                8425
cassi                              7935
amil                               6979
fundaffemg                         6897
porto                              6719
segurosunimed                      6590
ipsm                               5959
petrobraspetroleo                  5716
bradescosaudeoperadoradeplanos     5710
postalsaude                        3385
saudecaixa                         3068
medsenior                           631
mediservice                         262
spasaude                            116
proasa                               56
usisaude                             55
connectmed                           21
gamatopsaude                         15
unimedgoiania                         5
cabesp                                3
Name: count, dtype: int64

Número total de links ausentes (NA): 80430

In [22]:
# Pega a contagem de convênios que já tínhamos e transforma em um DataFrame
df_contagem = contagem_convenios.reset_index()
df_contagem.columns = ['CONVENIO', 'FREQUENCIA']

# Calcula o percentual de cada convênio em relação ao total de links extraídos
total_extraido = df_contagem['FREQUENCIA'].sum()
df_contagem['PERCENTUAL (%)'] = round((df_contagem['FREQUENCIA'] / total_extraido) * 100, 2)

# Pega a nossa tabela de exemplos de links
df_exemplos = df.dropna(subset=['CONVENIO']).groupby('CONVENIO')['DS_GUIA_PATH'].first().reset_index()
df_exemplos.rename(columns={'DS_GUIA_PATH': 'LINK_EXEMPLO'}, inplace=True)

# Agora, une as duas tabelas usando a coluna 'CONVENIO' como chave
df_final_detalhado = pd.merge(df_contagem, df_exemplos, on='CONVENIO')

# Garante que a coluna de links seja exibida completamente
pd.set_option('display.max_colwidth', None)


# Função para converter um texto de URL em uma tag HTML de link clicável
def tornar_clicavel(url):
    # Retorna a tag <a> do HTML. target="_blank" faz com que o link abra em uma nova aba.
    return f'<a href="{url}" target="_blank">{url}</a>'

# Prepara a tabela para exibição com o estilo
# Usamos .format() para aplicar a função 'tornar_clicavel' na coluna 'LINK_EXEMPLO'
# e também podemos formatar a coluna de percentual para exibir o símbolo '%'
tabela_formatada = df_final_detalhado.style.format({
    'LINK_EXEMPLO': tornar_clicavel,
    'PERCENTUAL (%)': '{:.2f}%'.format
})

print("--- Tabela Detalhada com Links Clicáveis ---")

# Exibe a tabela estilizada
display(tabela_formatada)

--- Tabela Detalhada com Links Clicáveis ---

In [23]:
# Filtra o DataFrame original para manter apenas as linhas onde:
# 1. 'CD_AVISO' não é Nulo/NA (df['CD_AVISO'].notna())
# 2. 'CD_AVISO' é maior que zero (df['CD_AVISO'] > 0)
df_com_aviso_valido = df[(df['CD_AVISO'].notna()) & (df['CD_AVISO'] > 0)]

# Agora, fazemos a contagem de convênios nesse DataFrame filtrado
contagem_convenio_com_aviso = df_com_aviso_valido['CONVENIO'].value_counts()

# Exibe o resultado
print("--- Contagem de Convênios (Apenas com CD_AVISO > 0) ---")
print(f"Total de guias com CD_AVISO válido: {len(df_com_aviso_valido)}")
print("-" * 50)

# 1. Pega a contagem da célula anterior e converte para um DataFrame
df_contagem_aviso = contagem_convenio_com_aviso.reset_index()
df_contagem_aviso.columns = ['CONVENIO', 'FREQUENCIA']

# 2. Calcula o percentual em relação ao novo total (apenas guias com aviso válido)
total_com_aviso = df_contagem_aviso['FREQUENCIA'].sum()
df_contagem_aviso['PERCENTUAL (%)'] = round((df_contagem_aviso['FREQUENCIA'] / total_com_aviso) * 100, 2)

# 3. Pega um link de exemplo de dentro do DataFrame já filtrado
df_exemplos_aviso = df_com_aviso_valido.groupby('CONVENIO')['DS_GUIA_PATH'].first().reset_index()
df_exemplos_aviso.rename(columns={'DS_GUIA_PATH': 'LINK_EXEMPLO'}, inplace=True)

# 4. Une a tabela de contagem com a de exemplos
df_final_aviso = pd.merge(df_contagem_aviso, df_exemplos_aviso, on='CONVENIO')

# 5. Aplica a formatação para deixar o link clicável e o percentual com o símbolo '%'
# (Reutilizando a função 'tornar_clicavel' que definimos antes)
tabela_formatada_aviso = df_final_aviso.style.format({
    'LINK_EXEMPLO': tornar_clicavel,
    'PERCENTUAL (%)': '{:.2f}%'.format
})

print("--- Tabela Detalhada de Convênios (Apenas com CD_AVISO > 0) ---")
display(tabela_formatada_aviso)

--- Contagem de Convênios (Apenas com CD_AVISO > 0) ---
Total de guias com CD_AVISO válido: 6438
--------------------------------------------------
--- Tabela Detalhada de Convênios (Apenas com CD_AVISO > 0) ---

## PARTE DA LLM ##

In [24]:
import os
import json
import boto3
from dotenv import load_dotenv
import requests
import base64
import io # Necessário para manipulação de bytes em memória
from pdf2image import convert_from_bytes # A nova importação

# Carrega as variáveis do arquivo .env
load_dotenv()

# Lê as variáveis do ambiente
aws_access_key_id = os.getenv('AWS_ACCESS_KEY_ID')
aws_secret_access_key = os.getenv('AWS_SECRET_ACCESS_KEY')
aws_region = os.getenv('AWS_BEDROCK_REGION', 'us-east-1') # Valor padrão: us-east-1
model_id = os.getenv('BEDROCK_MODEL_ID')

# Validação para garantir que as variáveis foram carregadas
if not all([aws_access_key_id, aws_secret_access_key, model_id]):
    print("❌ Erro: Certifique-se de que o arquivo .env está criado e configurado corretamente.")
else:
    print("✅ Variáveis de ambiente carregadas com sucesso.")

try:
    bedrock_runtime = boto3.client(
        service_name='bedrock-runtime', 
        aws_access_key_id=aws_access_key_id,
        aws_secret_access_key=aws_secret_access_key,
        region_name=aws_region
    )
    print(f"✅ Cliente AWS Bedrock inicializado com sucesso na região '{aws_region}'.")
except Exception as e:
    print(f"❌ Erro ao inicializar o cliente Bedrock: {e}")


def carregar_imagem_da_url(url):
    """
    Baixa um arquivo de uma URL. Se for PDF, converte a primeira página para imagem (PNG).
    Se já for imagem, usa diretamente. Retorna os bytes e o formato de mídia.
    """
    try:
        response = requests.get(url, timeout=15)
        response.raise_for_status()
        
        file_bytes = response.content
        content_type = response.headers.get('content-type', '')

        # Verifica se o conteúdo é um PDF
        if 'application/pdf' in content_type or url.lower().endswith('.pdf'):
            print("📄 PDF detectado. Convertendo a primeira página para imagem PNG...")
            
            # Converte os bytes do PDF para uma lista de imagens (formato PIL)
            images = convert_from_bytes(file_bytes, first_page=1, last_page=1)
            
            if images:
                image = images[0]
                # Salva a imagem em um buffer de bytes em memória, no formato PNG
                buffer = io.BytesIO()
                image.save(buffer, format='PNG')
                image_bytes = buffer.getvalue()
                
                print("✅ Conversão de PDF para PNG concluída.")
                # O novo media type é sempre PNG após a conversão
                return image_bytes, 'image/png'
            else:
                print("❌ Não foi possível extrair imagens do PDF.")
                return None, None

        # Se for um tipo de imagem já aceito, usa diretamente
        elif content_type in ['image/jpeg', 'image/png', 'image/gif', 'image/webp']:
            print(f"✅ Imagem ({content_type}) baixada com sucesso de {url}")
            return file_bytes, content_type
        
        else:
            print(f"⚠️ Tipo de arquivo não suportado: {content_type}")
            return None, None

    except requests.exceptions.RequestException as e:
        print(f"❌ Erro ao baixar o arquivo: {e}")
        return None, None
    except Exception as e:
        print(f"❌ Erro no processamento do arquivo (verifique a instalação do Poppler): {e}")
        return None, None

print("Funções de apoio atualizadas para lidar com PDFs.")

ModuleNotFoundError: No module named 'pdf2image'

In [ ]:
def extrair_dados_da_guia(image_bytes, media_type):
    """
    Envia a imagem de uma guia médica para a LLM multimodal no Bedrock
    e pede para extrair informações específicas em formato JSON.
    """
    # ... (o início da função continua igual) ...

    if not image_bytes:
        return {"erro": "Bytes da imagem não fornecidos."}

    # Codifica a imagem para Base64
    base64_image = base64.b64encode(image_bytes).decode('utf-8')

    # Prompt detalhado para guiar a LLM
    prompt_texto = """
    Você é um assistente especialista em analisar guias de autorização de convênios médicos (modelo TISS).
    Sua tarefa é extrair as seguintes informações da imagem fornecida e retornar **apenas e tão somente um objeto JSON válido**.

    Extraia os seguintes campos:
    - "procedimento_autorizado": O nome completo do procedimento principal autorizado (campo 25).
    - "paciente": O nome completo do paciente (campo 10).
    - "codigo_autorizado": Uma string contendo o código do procedimento e a quantidade (Um numero de 8 digitos)
    - "senha": O número da senha de autorização.
    - "validade_senha": A data de validade da senha (campo 6).
    - "observacoes_opme": Se houver alguma observação sobre OPME, transcreva-a. Se não houver menção, retorne "Pedido sem OPME".
    - "observacoes_gerais": O texto do campo "Indicação Clínica" (campo 21).
    - "usuario_finalizador": O nome do profissional solicitante (campo 14). Se não estiver presente, retorne null.

    O JSON de saída deve ter exatamente essa estrutura. Não inclua nenhuma outra explicação ou texto antes ou depois do JSON.
    """

    # Corpo da requisição para o modelo Claude 3 (multimodal)
    body = json.dumps({
        "anthropic_version": "bedrock-2023-05-31",
        "max_tokens": 2048,
        "messages": [
            {
                "role": "user",
                "content": [
                    {
                        "type": "image",
                        "source": {
                            "type": "base64",
                            "media_type": media_type,
                            "data": base64_image
                        }
                    },
                    {
                        "type": "text",
                        "text": prompt_texto
                    }
                ]
            }
        ]
    })

    try:
        # Invoca o modelo Bedrock
        response = bedrock_runtime.invoke_model(body=body, modelId=model_id)
        response_body = json.loads(response.get('body').read())
        
        # Extrai o texto da resposta
        resposta_texto_bruto = response_body['content'][0]['text']
        
        # --- LÓGICA DE LIMPEZA ADICIONADA AQUI ---
        # Procura o início do JSON (primeiro '{') e o fim (último '}')
        inicio_json = resposta_texto_bruto.find('{')
        fim_json = resposta_texto_bruto.rfind('}') + 1
        
        if inicio_json != -1 and fim_json != 0:
            json_limpo_str = resposta_texto_bruto[inicio_json:fim_json]
            dados_extraidos = json.loads(json_limpo_str)
            return dados_extraidos
        else:
            # Se não encontrar um JSON, lança um erro para ser capturado abaixo
            raise ValueError("Nenhum objeto JSON válido encontrado na resposta da LLM.")

    except Exception as e:
        resposta_bruta_para_erro = ""
        if 'response_body' in locals():
            resposta_bruta_para_erro = response_body.get('content', [{}])[0].get('text', '')
        
        print(f"❌ Ocorreu um erro ao chamar a LLM ou processar a resposta: {e}")
        return {"erro": str(e), "resposta_bruta": resposta_bruta_para_erro}

print("Função principal de extração atualizada com limpeza de JSON.")

Função principal de extração atualizada com limpeza de JSON.

In [ ]:
from PIL import Image
import io

def redimensionar_imagem(image_bytes, fator_zoom=3.0, limite_mb=5):
    """
    Redimensiona uma imagem por um fator, mas respeita um limite de tamanho em MB.
    
    :param image_bytes: A imagem original em bytes.
    :param fator_zoom: Fator para aumentar a imagem (ex: 2.0 para 200%).
    :param limite_mb: O tamanho máximo permitido para a imagem final em megabytes.
    :return: Os bytes da imagem redimensionada, ou os bytes da imagem original se o limite for excedido.
    """
    try:
        limite_bytes = limite_mb * 1024 * 1024
        imagem = Image.open(io.BytesIO(image_bytes))

        # Calcula as novas dimensões
        nova_largura = int(imagem.width * fator_zoom)
        nova_altura = int(imagem.height * fator_zoom)

        print(f"Redimensionando imagem de {imagem.size} para {(nova_largura, nova_altura)}...")
        
        # Redimensiona usando um filtro de alta qualidade (LANCZOS)
        imagem_redimensionada = imagem.resize((nova_largura, nova_altura), Image.Resampling.LANCZOS)

        # Salva a nova imagem em um buffer para verificar o tamanho
        buffer = io.BytesIO()
        imagem_redimensionada.save(buffer, format='PNG')
        bytes_redimensionados = buffer.getvalue()

        # Verifica se o tamanho final respeita o limite
        if len(bytes_redimensionados) > limite_bytes:
            print(f"⚠️ Aviso: A imagem redimensionada ({len(bytes_redimensionados) / 1024 / 1024:.2f} MB) excedeu o limite de {limite_mb} MB.")
            print("Enviando a imagem original para a LLM.")
            return image_bytes # Retorna a original se o limite for estourado
        else:
            print(f"✅ Imagem redimensionada com sucesso ({len(bytes_redimensionados) / 1024 / 1024:.2f} MB).")
            return bytes_redimensionados

    except Exception as e:
        print(f"❌ Erro ao redimensionar a imagem: {e}")
        return image_bytes # Retorna a original em caso de erro

In [ ]:
# --- COLOQUE O CÓDIGO DO AVISO AQUI ---
aviso_cirurgico_desejado = '852687'

df_aviso_encontrado = df[df['CD_AVISO_CIRURGIA'] == aviso_cirurgico_desejado]

if not df_aviso_encontrado.empty:
    aviso_exemplo = df_aviso_encontrado.iloc[0]
    url_exemplo = aviso_exemplo['DS_GUIA_PATH']

    if pd.notna(url_exemplo):
        print(f"--- Iniciando teste com ZOOM para o Aviso Cirúrgico: {aviso_cirurgico_desejado} ---")
        
        # 1. Carregar a imagem da URL (converte PDF para imagem se necessário)
        bytes_da_imagem_original, tipo_de_midia = carregar_imagem_da_url(url_exemplo)

        if bytes_da_imagem_original:
            # 2. Tenta redimensionar a imagem (dar o "zoom")
            # Você pode ajustar o fator_zoom aqui. 2.0 = 200% do tamanho.
            bytes_para_llm = redimensionar_imagem(bytes_da_imagem_original, fator_zoom=3)
            
            # 3. Envia a imagem (original ou redimensionada) para a LLM
            print("\n--- Enviando imagem para a LLM para extração completa... ---")
            resultado_json = extrair_dados_da_guia(bytes_para_llm, 'image/png') # Usamos 'image/png' pois é o nosso formato padrão
            
            # 4. Exibir o resultado formatado
            print("\n--- DADOS EXTRAÍDOS (APÓS ZOOM) ---")
            print(json.dumps(resultado_json, indent=2, ensure_ascii=False))

else:
    print(f"❌ O Aviso Cirúrgico '{aviso_cirurgico_desejado}' não foi encontrado.")

NameError: name 'df' is not defined

In [ ]:
-- Pedido do medico -- SEGUNDO INPUT    
SELECT * from surgery_flow_prod.surgical_order so
where surgical_order_id = '852687'

In [ ]:
-- GROUND TRUTH          
SELECT * --rc.CD_REGISTRO_CONTATO, rc.CD_REGISTRO_VINCULADO, rc.DT_CONTATO, rc.HR_CONTATO, rc.CD_USUARIO, rc.DS_ASSUNTO
  FROM dbamv.registro_contato rc
  WHERE cd_registro_vinculado IN (852687) 
  --AND ds_assunto = 'PEDIDO FINALIZADO'
  --AND cd_usuario = 'MMD_INTEGRACAO'
    ORDER BY 1